from pathlib import Path
import hashlib,html,json,shutil,subprocess
r=Path(__file__).resolve().parent;w=r/'delivery-v1';repo=Path('/Users/motoricallc/Downloads/fluxara-drift');res=repo/'iosApp/FluxaraResources';track='fluxara-user-dust-cross-split-combat';final=r.parent/'fluxara-user-dust-cross-final';report=final/'report';app=Path(subprocess.check_output(['xcrun','simctl','get_app_container','3B2F19DC-4F76-4F61-9F8D-D5E914A6D123','io.fluxara.drift','app'],text=True).strip());pack=repo/'FLUXARA_TRACK_ASSET_PACK';info=lambda p:{'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
shots=w/'screenshots/closed-boundary';preview=w/'candidate/screenshot.jpg';subprocess.run(['sips','--resampleWidth','960','-s','format','jpeg','-s','formatOptions','75',str(shots/'overview.jpg'),'--out',str(preview)],check=True,capture_output=True)
for root in [res/'tracks'/track,app/'data/tracks'/track,final/'resources']:shutil.copy2(preview,root/'screenshot.jpg')
gui=res/'gui/fluxara/campaign-previews'/(track+'.jpg');gui.parent.mkdir(parents=True,exist_ok=True);subprocess.run(['sips','--resampleHeightWidthMax','512','-s','format','jpeg','-s','formatOptions','92',str(shots/'overview.jpg'),'--out',str(gui)],check=True,capture_output=True);shutil.copy2(gui,app/'data/gui/fluxara/campaign-previews'/gui.name)
weights=json.loads((w/'weight-verification.json').read_text());weights['candidateOwnBytes']=sum(x.stat().st_size for x in (w/'candidate').iterdir()if x.is_file());weights['previewCampaignThumbnailPending']=False;weights['campaignThumbnailBytesChargedInFull']=gui.stat().st_size;weights['candidateTotalBytes']=weights['candidateOwnBytes']+weights['newSharedGameBytes']+gui.stat().st_size;weights['savingBytes']=weights['originalBytes']-weights['candidateTotalBytes'];weights['savingPercent']=weights['savingBytes']*100/weights['originalBytes'];weights['sourcePreview']=info(preview);weights['campaignPreview']=info(gui);(w/'weight-verification.json').write_text(json.dumps(weights,indent=2))
boundary=json.loads((w/'boundary-verification.json').read_text());native=info(final/'Dust Cross Split Combat.blend');boundary['finalBlendSha256']=native['sha256'];(w/'boundary-verification.json').write_text(json.dumps(boundary,indent=2));integration=json.loads((w/'integration.json').read_text());integration['native']=native;integration['boundary']=boundary;integration['weight']=weights;integration['staticScreenshots']=json.loads((w/'closed-boundary-screenshots.json').read_text());(w/'integration.json').write_text(json.dumps(integration,indent=2))
(report/'screenshots').mkdir(exist_ok=True);evidence=report/'evidence/coordinate-reuse';evidence.mkdir(parents=True,exist_ok=True)
for p in shots.glob('*.jpg'):shutil.copy2(p,report/'screenshots'/('closed-boundary-'+p.name))
# Keep the earlier real gameplay frames as dated history, without claiming a new drive.
for p in (w/'screenshots/candidate').glob('game-*.png'):shutil.copy2(p,report/'screenshots'/('coordinate-draft-'+p.name))
for name in ['boundary-verification.json','integration.json','weight-verification.json','asset-registration.json','native-verification.json','canonical-reuse-verification.json','closed-boundary-screenshots.json','runtime-validation.json','candidate-capture.json']:shutil.copy2(w/name,evidence/name)
old=report/'index.html';prior=report/'before-coordinate-reuse.html'
if not prior.exists():shutil.copy2(old,prior)
s=prior.read_text();before,body=s.split('<main>',1);history,after=body.rsplit('</main>',1);fmt=lambda v:f'{v:,}'.replace(',',' ')
section=f'''<div class="label">FLUXARA DRIFT · КАРТА 03 · 02.10.2026</div><h1>Dust Cross Split Combat — замкнутая граница</h1>
<p class="lead">Остальное оформление арены согласовано пользователем и сохранено. Закрыты три отсутствовавшие секции исходного ограждения. Каждая новая секция имеет физическую коллизию static/exact; добавлена одна модель из 36 треугольников весом 1 607 байт, без новых текстур.</p>
<p>572 существующие части окружения вынесены в шесть общих моделей. Добавлены 18 деревьев из тех же общих моделей на существующих скальных площадках. Всего 680 размещений по координатам; индивидуальные модели для каждого экземпляра не добавлялись.</p>
<p>Исходное полотно, navmesh и игровые точки сохранены. Исходные видимые объекты, материалы, размеры, центры и направления сохранены; новые стены дополняют три разрыва между существующими концами ограждения.</p>
<table><tr><th>Вес ресурсов</th><th>Байты</th></tr><tr><td>Исходная карта перед переносом в пул</td><td>{fmt(weights['originalBytes'])}</td></tr><tr><td>Карта, включая закрытую границу и новое превью</td><td>{fmt(weights['candidateOwnBytes'])}</td></tr><tr><td>Все новые общие модели и алиасы существующих текстур</td><td>{fmt(weights['newSharedGameBytes'])}</td></tr><tr><td>Новое превью кампании, учтённое целиком</td><td>{fmt(gui.stat().st_size)}</td></tr><tr><td>Полный итог этапа</td><td>{fmt(weights['candidateTotalBytes'])}</td></tr><tr><td>Уменьшение</td><td>{fmt(weights['savingBytes'])} ({weights['savingPercent']:.2f}%)</td></tr></table>
<p>Новые секции сохранены в исходных ресурсах проекта, установленной копии iOS Simulator и итоговом Blender. Новая сборка приложения не выполнялась. По просьбе пользователя проверки попыток выезда отменены; физическое удержание машин новым ограждением не заявляется как проверенное.</p>
<figure><img src="screenshots/closed-boundary-overview.jpg"><figcaption>Общий вид арены с заполненным разрывом дальней стены. Кадр игрового движка со статичной камерой; не заезд.</figcaption></figure>
<figure><img src="screenshots/closed-boundary-west-wall.jpg"><figcaption>Западная сторона ограждения с закрытыми разрывами. Кадр игрового движка со статичной камерой; не проверка проезда.</figcaption></figure>
<p><a href="evidence/coordinate-reuse/boundary-verification.json">Сохранённые параметры трёх секций</a> · <a href="evidence/coordinate-reuse/weight-verification.json">Вес ресурсов</a> · <a href="evidence/coordinate-reuse/integration.json">Сохранение в проекте и симуляторе</a></p>
<details><summary>Предыдущий отчёт и ранее сохранённые игровые кадры</summary>{history}</details>'''
old.write_text(before+'<main>'+section+'</main>'+after)
lp=r.parent.parent/(track+'.asset-ledger.json');ledger=json.loads(lp.read_text());ledger['coordinateReusePhase'].update({'report':str(old),'weight':weights,'boundaryCorrection':boundary,'finalBlendFile':native,'screenshots':json.loads((w/'closed-boundary-screenshots.json').read_text()),'visualApproval':'User: the rest is perfect; retained unchanged.','drivingAndCollisionChecks':'Cancelled by user on 2026-10-02.','preview':info(preview),'campaignPreview':info(gui)});lp.write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n')
progresspath=r.parent/'shared-placement-1-10/progress.json';progress=json.loads(progresspath.read_text());progress['maps']['3']={'trackId':track,'status':'Coordinate scenery integrated; 18 grounded trees added; arena art approved by user; three missing boundary sections closed. Collision checks cancelled by user.','storageConversionInstances':572,'newTreeInstances':18,'newTreeCoordinateParts':108,'totalCoordinateInstances':680,'uniqueModels':6,'sourceAndInstalledIntegrated':True,'boundaryGapCountClosed':3,'boundaryNewBytes':1607,'originalWeightBytes':weights['originalBytes'],'trackPlusNewSharedAndCampaignPreviewBytes':weights['candidateTotalBytes'],'savingBytes':weights['savingBytes'],'visualApprovedByUser':True,'validationOwner':'user','assistantCollisionCheckRequested':False,'newBuildPerformed':False,'report':str(old)};progress['stage']='Map 3 coordinate delivery and three-section arena boundary fix saved. Cross-map work remains active.';progress['goalComplete']=False;progresspath.write_text(json.dumps(progress,ensure_ascii=False,indent=2)+'\n')
archive=pack/'sources/dust-cross-shared-placement-v1';archive.mkdir(parents=True,exist_ok=True)
for src in r.glob('*.py'):shutil.copy2(src,archive/src.name)
for src in w.glob('*.json'):shutil.copy2(src,archive/src.name)
shutil.copytree(shots,archive/'screenshots/closed-boundary',dirs_exist_ok=True);shutil.copytree(report,archive/'report',dirs_exist_ok=True);shutil.copy2(lp,archive/lp.name)
print('DUST_DELIVERY_REPORT_PREVIEWS_SAVED',weights['candidateTotalBytes'],weights['savingBytes'],flush=True)
