from pathlib import Path
import json,hashlib,shutil,re
from urllib.parse import unquote,urlsplit
r=Path(__file__).resolve().parent;w=r/'fidelity-v7b';out=r.parent/'fluxara-user-volcano-remake-final/report';page=out/'index.html';evidence=out/'evidence/fidelity-v7b';evidence.mkdir(parents=True,exist_ok=True);history=w/'report-history';history.mkdir(exist_ok=True)
shutil.copy2(page,history/(hashlib.sha256(page.read_bytes()).hexdigest()[:12]+'-index.html'))
for name in ['smoke-changes.json','layout-changes.json','preservation.json','budget.json','runtime-validation.json','drive-capture.json','smoke-diagnostic-all.json','final-blend-verification.json','canonical-bindings-verification.json','pool-audit.json']:shutil.copy2(w/name,evidence/name)
for name in ['drive-12s.png','drive-40s.png','drive-80s.png','drive-150s.png','smoke-diagnostic-all.png']:shutil.copy2(w/'screenshots'/name,out/'screenshots'/('fidelity-v7b-'+name))
for version in ['v6','v7']:
    old=r/('fidelity-'+version);dst=out/'evidence'/('fidelity-'+version);dst.mkdir(exist_ok=True)
    for name in ['budget.json','preservation.json','runtime-validation.json']:
        if(old/name).is_file():shutil.copy2(old/name,dst/name)
    for name in ['drive-40s.png','drive-80s.png']:shutil.copy2(old/'screenshots'/name,out/'screenshots'/('history-'+version+'-'+name))
b=json.loads((w/'budget.json').read_text());assert json.loads((w/'runtime-validation.json').read_text())['candidateOneLapTimeTrial']['naturalFinishObserved'];assert json.loads((w/'pool-audit.json').read_text())['newObjects']==6
section=f'''<section id="fidelity-v7b-draft"><h2>Последний эксперимент — V7B, объёмные клубы дыма</h2>
<p>Три дымовых меша пересобраны из 27 округлых объёмных клубов: 11 для AshCloud, 10 для AshColumn и 6 для PyroclasticFlow. Геометрия компенсирует неодинаковые масштабы размещений, чтобы отдельные клубы имели округлые пропорции в мире игры. Исходные локальные границы, центры этих границ, начала координат и оси сохранены с погрешностью менее 0,00002 единицы. Используются две существующие сливово-тёплые палитры; новых игровых текстур и материалов нет.</p>
<p>Восемь декоративных размещений прозрачных карточек объединены с тремя объёмными шлейфами. Изменены позиции и масштабы трёх оставшихся объектов, их направления выставлены в ноль; прежние кривые движения и прокрутка текстур именно этих декоративных эффектов удалены. Все затронутые объекты имеют interaction=ghost. Это явное изменение атмосферы и её размещений; оно не сохраняет старое движение дыма. Исходные игровые объекты и параметры не затронуты.</p>
<table><tr><th>Показатель</th><th>Результат V7B</th></tr>
<tr><td>Папка карты</td><td>{b['candidateTrackBytes']:,} байт; на {b['savedBytesAgainstPrevious']:,} байт меньше основной V1</td></tr>
<tr><td>Треугольники карты</td><td>{b['candidateTriangles']:,}; +{b['triangleChangePercentAgainstOriginal']:.2f}% к оригиналу</td></tr>
<tr><td>Треугольники трёх мешей</td><td>864 → 880; 768 → 800; 512 → 480</td></tr>
<tr><td>Вес трёх SPM к оригиналам</td><td>+8,70%; +0,81%; −0,59%</td></tr>
<tr><td>Новые общие игровые ресурсы сверх папки карты</td><td>0 байт</td></tr>
<tr><td>Общий пул</td><td>3 новых редактируемых прототипа и 3 SPM зарегистрированы физически; материалы и изображения повторно используются</td></tr></table>
<p>Проверка ±20% в этой таблице относится к весу самих трёх мешей. Исходные большие текстуры дыма ранее заменены малыми палитрами, поэтому это не проверка сохранения веса каждого меша вместе с оригинальной текстурой.</p>
<p>Полотно трассы, его вершины, нормали, UV, цвета и индексы совпадают с оригиналом. Track.xml, quads.xml, graph.xml, scripting.as и easter_eggs.xml совпадают побайтно. Другие модели, материалы, изображения и узлы сцены совпадают с V5 Alpha. Все три новых статических шлейфа находятся выше максимальной высоты дороги с запасом 3,5 единицы.</p>
<p>Blender-проект повторно открыт: геометрия, индексы и UV трёх прототипов совпадают с SPM, масштабы и координаты размещений — с XML. Проверены 85 частей общих размещений и пиксели использованных палитр. После добавления прототипов в каноническую библиотеку проверены привязки моделей карт 6–10, прошлых кандидатов и свечение окон домов.</p>
<p>Кандидат прошёл один круг Time Trial с одной машиной и естественным финишем #1 в iOS Simulator без принудительной победы. Сохранены <a href="screenshots/fidelity-v7b-drive-150s.png">финиш</a>, <a href="screenshots/fidelity-v7b-drive-12s.png">начало заезда</a> и <a href="screenshots/fidelity-v7b-smoke-diagnostic-all.png">отдельный статический обзор в движке</a>. Статический обзор не является кадром заезда; задержки в именах файлов не равны игровому таймеру.</p>
<p class="note"><strong>V7B остаётся экспериментом, карта 10 не завершена.</strong> В игровой камере отдельные клубы выглядят раздельными и слишком тёмными; плотный шлейф и его связь с вулканом ещё не соответствуют референсу. Замок, скалы, крупные лавовые формы и общая атмосфера требуют дальнейшей работы. Основная игровая карта, её итоговый Blender-файл и превью кампании сохраняют V1. Нового билда приложения не было. Полный заезд кампании, обратное направление и производительность не подтверждены.</p>
<p><a href="../../volcano-remake-rework/fidelity-v7b/native/Volcano%20Remake.blend">Редактируемый эксперимент V7B</a> · <a href="evidence/fidelity-v7b/preservation.json">Сохранность</a> · <a href="evidence/fidelity-v7b/layout-changes.json">Изменения атмосферы</a> · <a href="evidence/fidelity-v7b/budget.json">Вес</a> · <a href="evidence/fidelity-v7b/runtime-validation.json">Проверка заезда</a> · <a href="evidence/fidelity-v7b/final-blend-verification.json">Blender и SPM</a> · <a href="evidence/fidelity-v7b/pool-audit.json">Общий пул</a></p>
<figure><a href="screenshots/fidelity-v7b-drive-40s.png"><img src="screenshots/fidelity-v7b-drive-40s.png" alt="V7B: подъём, отдельные клубы дыма в фоне"></a><figcaption><strong>V7B — подъём</strong><span>Настоящий игровой кадр. Видны раздельные клубы, которые ещё требуют соединения в плотный шлейф.</span></figcaption></figure>
<figure><a href="screenshots/fidelity-v7b-drive-80s.png"><img src="screenshots/fidelity-v7b-drive-80s.png" alt="V7B: верхняя часть трассы"></a><figcaption><strong>V7B — верхняя часть маршрута</strong><span>Настоящий игровой кадр. Лава и формы скал пока отличаются от референса.</span></figcaption></figure>
<h3>Промежуточные проверки этого этапа</h3><p>V6 с поднятыми прозрачными карточками отклонена: дым слишком высоко и оторван от вулкана (<a href="screenshots/history-v6-drive-40s.png">кадр 1</a>, <a href="screenshots/history-v6-drive-80s.png">кадр 2</a>, <a href="evidence/fidelity-v6/runtime-validation.json">статус</a>). Первый объёмный V7 с 20 гранями на клуб заменён V7B: силуэт слишком угловатый (<a href="screenshots/history-v7-drive-40s.png">кадр 1</a>, <a href="screenshots/history-v7-drive-80s.png">кадр 2</a>, <a href="evidence/fidelity-v7/runtime-validation.json">статус</a>). Обе версии завершили один тестовый круг, что не означает визуального соответствия референсу.</p></section>'''
s=re.sub(r'<section id="fidelity-v7b-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v5-alpha-draft">',section+'<section id="fidelity-v5-alpha-draft">',1);s=s.replace('Последняя доработка — V5 Alpha','Предыдущая доработка — V5 Alpha');s=s.replace('V2, V3, V4E и V5 Alpha добавлены','V2, V3, V4E, V5 Alpha и V7B добавлены');page.write_text(s)
missing=[link for link in re.findall(r'(?:src|href)="([^"]+)"',s)if not urlsplit(link).scheme and not link.startswith('#')and not(out/unquote(link.split('#')[0])).exists()];assert not missing,missing
(out/'manifest.json').write_text(json.dumps({'brokenLocalLinks':missing,'files':[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}for p in out.rglob('*')if p.is_file()and p.name!='manifest.json']},indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for prefix in ['volcano-remake-reference-v1','volcano-remake-fidelity-v2','volcano-remake-fidelity-v3','volcano-remake-fidelity-v4e','volcano-remake-fidelity-v5','volcano-remake-fidelity-v5-alpha','volcano-remake-fidelity-v6','volcano-remake-fidelity-v7','volcano-remake-fidelity-v7b']:shutil.copytree(out,pack/'sources'/prefix/'report',dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v7b'/Path(__file__).name)
progress_path=r.parent/'shared-placement-1-10/progress.json';progress=json.loads(progress_path.read_text());progress['maps']['10'].update({'status':'V7B volumetric smoke experiment: 27 puffs, three plumes; eight old decorative sprite placements consolidated. Original course and gameplay exact, one TT lap natural finish, native/canonical/physical assets verified. Individual puffs detached/dark; castle, cliffs, lava and reference fidelity remain unfinished. Production and preview unchanged.','candidate':str(w),'candidateTrackBytes':b['candidateTrackBytes'],'candidateSavedBytesAgainstPrevious':b['savedBytesAgainstPrevious'],'candidateTriangleChangePercent':b['triangleChangePercentAgainstOriginal'],'candidateOneLapNaturalFinish':True,'candidateProductionIntegrated':False,'fullyAccepted':False});progress_path.write_text(json.dumps(progress,ensure_ascii=False,indent=2));print('V7B_REPORT_UPDATED',page)
