from pathlib import Path
import json,sys,math,struct,shutil,copy,collections,hashlib
r=Path(__file__).resolve().parent;w=r/'fidelity-v14';w.mkdir(exist_ok=True);old=r/'fidelity-v13/candidate';c=w/'candidate';shutil.copytree(old,c,dirs_exist_ok=True);sys.path.insert(0,str(r.parent/'shared-object-redesign'));from spm_io import parse
code=(r/'fidelity_v2.py').read_text();ns={'math':math,'struct':struct};exec(code[code.index('def encode_buffer'):code.index('new_vertices, new_indices')],ns);d=parse(c/'volcano_track.spm');b=d['buffers'][1];g=next(g for g in ns['component_triangles'](b)if len(g)==72)
def subset(tris,material):
 ii=[i for t in sorted(tris)for i in b['indices'][3*t:3*t+3]];vv=sorted(set(ii));mapping={v:i for i,v in enumerate(vv)};return {'vertices':[copy.deepcopy(b['vertices'][v])for v in vv],'indices':[mapping[v]for v in ii],'material':material}
rockmat=next(i for i,pair in enumerate(d['materials'])if pair[0]=='Rock13_col.jpg');other=subset(set(range(len(b['indices'])//3))-set(g),b['material']);mountain=subset(g,rockmat);(c/'volcano_track.spm').write_bytes(ns['replace_buffers'](d,{1:[other,mountain]}));new=parse(c/'volcano_track.spm')
def attrs(v):return {k:q for k,q in v.items()if not k.endswith('offset')}
def triangles(buf):return collections.Counter(tuple(json.dumps(attrs(buf['vertices'][j]),sort_keys=True)for j in buf['indices'][i:i+3])for i in range(0,len(buf['indices']),3))
assert triangles(other)+triangles(mountain)==triangles(b);assert d['bounds']==new['bounds'];assert d['materials']==new['materials'];assert all(triangles(x)==triangles(y)and x['material']==y['material']for x,y in zip(d['buffers'][2:],new['buffers'][3:]));assert all((c/p.name).read_bytes()==p.read_bytes()for p in old.iterdir()if p.is_file()and p.name!='volcano_track.spm');assert (c/'volcano_track.spm').stat().st_size<=(old/'volcano_track.spm').stat().st_size*1.2
proof={'baseCandidate':'V13','sourceModel':str(old/'volcano_track.spm'),'candidateModel':str(c/'volcano_track.spm'),'originalBuffer':1,'originalComponentTriangleIds':g,'centralMountainTriangles':72,'castlePortalAndOtherTrianglesKept':532,'newMountainBuffer':2,'oldCliffBufferMovedToIndex':3,'textureReused':'Rock13_col.jpg','textureBytes':(c/'Rock13_col.jpg').stat().st_size,'textureSha256':hashlib.sha256((c/'Rock13_col.jpg').read_bytes()).hexdigest(),'newTextureFiles':0,'newImagePixels':False,'positionsUVsNormalsColorsIndexedTrianglesExact':True,'collisionGeometryAndPhysicalMaterialBehaviorPreserved':True,'modelBytesBefore':(old/'volcano_track.spm').stat().st_size,'modelBytesAfter':(c/'volcano_track.spm').stat().st_size,'upper20PercentPassed':True,'sceneAndControlsAndOtherFilesExactV13':True,'nativeVerified':False,'runtimeViewed':False,'productionIntegrated':False,'referenceAcceptance':False,'status':'Early material split draft; no geometry or UV edits. Central mountain assigned existing rock material; castle portal material retained.'};(w/'central-rock-changes.json').write_text(json.dumps(proof,indent=2));print('V14_CENTRAL_MOUNTAIN_STONE_DRAFT',proof['modelBytesBefore'],proof['modelBytesAfter'])
