from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v14';repo=Path('/Users/motoricallc/Downloads/fluxara-drift');pack=repo/'FLUXARA_TRACK_ASSET_PACK';sources=pack/'sources/volcano-remake-fidelity-v14';sources.mkdir(exist_ok=True);mod=pack/'models/volcano-remake-fidelity-v14';canon=pack/'blender/FLUXARA_Track_Asset_Library.blend';pf=repo/'FLUXARA_TRACK_ASSET_POOL.json';a=json.loads((w/'asset-registration.json').read_text());pool=json.loads(pf.read_text());ledger=json.loads((r/'fidelity-v13/candidate-asset-ledger.json').read_text());assert json.loads((w/'canonical-registration.json').read_text())['newObjects']==1;assert json.loads((w/'final-blend-verification.json').read_text())['onlyCentral72TriangleMaterialChanged'];assert(w/'canonical-bindings-verification.json').is_file()
if not(w/'pool-before-v14.json').exists():shutil.copy2(pf,w/'pool-before-v14.json')
def info(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for name in ['build_fidelity_v14_central_rock.py','audit_fidelity_v14_budget.py','finalize_fidelity_v14.py','verify_fidelity_v14_native.py','register_fidelity_v14_canonical.py','verify_fidelity_v14_canonical.py','capture_fidelity_v14_drive.py','capture_fidelity_v14_inspection.py',Path(__file__).name]:shutil.copy2(r/name,sources/name)
for p in w.glob('*.json'):
 if not p.name.startswith('pool-before'):shutil.copy2(p,sources/p.name)
for folder in ['candidate','native','screenshots','original-component']:shutil.copytree(w/folder,sources/folder,dirs_exist_ok=True)
usage=[{'trackId':'fluxara-user-volcano-remake','candidate':'V14','status':'Central mountain assigned existing rock material. Existing original runtime model still contains this geometry; no extra app mesh or texture file. Candidate not integrated.'}];base={'sourceMap':'fluxara-user-volcano-remake','categories':['rock','lava'],'uses':usage};new=[]
for q in a['newPrototypes']:
 deps=[next(m['id']for m in ledger['materials']if m['name']==n)for n in q['materials']];new.append({**base,**q,'displayName':q['name'],'kind':'visual-object','reuseTier':'adapt','canonicalPackPath':str(canon)+'#Object/'+q['name'],'physicalSourcePath':a['visualLibrary'],'file':info(Path(a['visualLibrary'])),'dependencies':deps,'reason':'Source central decorative mountain geometry with original UVs, normals, bounds and axes; existing pooled Rock13 material replaces castle-arch material. Source prototype is not an extra runtime export.'});stored=mod/'volcano_track.spm';new.append({**base,'id':'volcano-fidelity-v14-runtime-volcano-track','displayName':stored.name,'kind':'map-runtime-model','reuseTier':'adapt','canonicalPackPath':str(stored),'physicalSourcePath':str(r/'fidelity-v13/candidate/volcano_track.spm'),'file':info(stored),'dependencies':deps,'sourceBuffer':2,'protectedGeometryScope':'Full runtime map mesh includes immutable road and gameplay geometry. Reusable Blender prototype contains only the 72-triangle decorative mountain.','reason':'Actual original runtime SPM has identical geometry and texture table; decorative component moved to its existing rock material. File bytes decrease; no new game model/texture files.'})
pool['objects']=[q for q in pool['objects']if not q['id'].startswith('volcano-fidelity-v14-')]+new;ledger['objects']=[q for q in ledger['objects']if not q['id'].startswith('volcano-fidelity-v14-')]+new;ci=info(canon)
def refresh(v):
 if isinstance(v,dict):
  if v.get('path')==str(canon)and'sha256'in v:v.update(ci)
  for x in v.values():refresh(x)
 elif isinstance(v,list):
  for x in v:refresh(x)
refresh(pool);pool['physicalPack']['blenderLibrary']=ci;pool['updated']=datetime.now(timezone.utc).isoformat();ids=[q['id']for key in ['objects','materials','textures']for q in pool[key]];assert len(ids)==len(set(ids));budget=json.loads((w/'budget-preservation.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());ledger.update({'candidate':'V14 central mountain with existing stone texture','status':'Current isolated material-only candidate. Protected course, collision and all source indexed geometry retained; two game frames and static engine view inspected. Reference fidelity unfinished.','finalBlend':a['finalBlend'],'nativeSharedParts':len(a['nativeSharedInstances']),'preservation':json.loads((w/'central-rock-changes.json').read_text()),'budget':budget,'runtimeValidation':run,'deltaAssetCounts':{'objects':2,'materials':0,'textures':0},'productionIntegrated':False,'newImagePixels':False});ledger['assets']=ledger['objects']+ledger['materials']+ledger['textures'];ledger['mapRuntimeFiles']=[info(p)for p in(sources/'candidate').iterdir()if p.is_file()]
for q in ledger['assets']:
 assert q['id']in ids;assert Path(q['canonicalPackPath'].split('#')[0]).is_file(),q['id'];assert Path(q['physicalSourcePath'].split('#')[0]).exists(),q['id'];assert all(dep in ids for dep in q.get('dependencies',[])),q['id']
 if q.get('file'):assert info(Path(q['file']['path']))==q['file'],q['id']
audit={'newObjects':2,'newNativePrototypes':1,'newMaterials':0,'newTextures':0,'newSharedGameFiles':0,'allPhysicalPathsAndFileHashesMatch':True,'uniquePoolIds':len(ids),'ledgerAssetsIncludingHistoricalSources':len(ledger['assets']),'unresolvedDependencies':[],'canonical':ci,'productionIntegrated':False};pf.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n');(w/'candidate-asset-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n');(w/'pool-audit.json').write_text(json.dumps(audit,indent=2))
for name in ['candidate-asset-ledger.json','pool-audit.json']:shutil.copy2(w/name,sources/name)
print('V14_STONE_REUSE_REGISTERED',audit,flush=True)
