from pathlib import Path
import collections,copy,hashlib,json,math,sys,xml.etree.ElementTree as E
r=Path(__file__).resolve().parent;w=r/'fidelity-v39';c=w/'candidate';old=r/'fidelity-v38/candidate';p=json.loads((w/'visual-batch-preflight.json').read_text());sys.path.insert(0,str(r.parent/'shared-object-redesign'));from spm_io import parse
sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
for f in old.iterdir():
 if f.is_file()and f.name not in ['volcano_track.spm','scene.xml','materials.xml',Path(p['removedUnreferencedImage']['path']).name]:assert f.read_bytes()==(c/f.name).read_bytes(),f.name
for n in ['track.xml','quads.xml','graph.xml','scripting.as','easter_eggs.xml']:assert(old/n).read_bytes()==(c/n).read_bytes()==(r/'fidelity-v2/baseline'/n).read_bytes()
def clean(v):return {k:q for k,q in v.items()if not k.endswith('offset')and k!='offset'}
a=parse(old/'volcano_track.spm');b=parse(c/'volcano_track.spm');assert a['bounds']==b['bounds']and a['flags']==b['flags'];assert len(a['buffers'])+1==len(b['buffers'])
def tris(d):return collections.Counter(tuple((tuple(buf['vertices'][i]['position']),buf['vertices'][i]['normal'])for i in buf['indices'][j:j+3])for buf in d['buffers']for j in range(0,len(buf['indices']),3))
assert tris(a)==tris(b);assert sum(len(x['vertices'])for x in a['buffers'])==sum(len(x['vertices'])for x in b['buffers']);assert a['materials'][:3]==b['materials'][:3]and a['materials'][4:]==b['materials'][4:]and b['materials'][3]==['','']
for i,buf in enumerate(a['buffers']):
 if i in [3,19]:continue
 new=b['buffers'][i if i<19 else i+1];assert buf['indices']==new['indices']and buf['material']==new['material']and list(map(clean,buf['vertices']))==list(map(clean,new['vertices'])),i
lake=a['buffers'][3];nlake=b['buffers'][3];assert lake['indices']==nlake['indices'];assert all(u['position']==v['position']and u['normal']==v['normal']for u,v in zip(lake['vertices'],nlake['vertices']))
wood=a['buffers'][19];newwood=b['buffers'][19];roof=b['buffers'][20];assert len(newwood['indices'])//3==95 and len(roof['indices'])//3==64
for j,i in enumerate(p['woodRoadOriginalVertexIds']):assert clean(wood['vertices'][i])==clean(newwood['vertices'][j]),i
for j,i in enumerate(p['woodRoofOriginalVertexIds']):assert wood['vertices'][i]['position']==roof['vertices'][j]['position']and wood['vertices'][i]['normal']==roof['vertices'][j]['normal']
assert b['materials'][roof['material']][0]=='fluxara_castle_brick_v15.jpg';assert b['materials'][newwood['material']][0]=='stktex_generic_WoodA.png'
# The previous conservative road count included64 decorative roof faces. All2032 positions/normals stay exact; only64roof UV/color/material change.
protectedNames=['track01.png','stktex_generic_WoodA.png','stkflag_blackBooster_a.png','stkflag_blackBooster_b.png','stk_generic_gridA.png','stk_generic_gravalSnow_a.png'];protectedNames[-1]='stk_generic_gravalSnow_a.png';protectedNames=[a['materials'][a['buffers'][i]['material']][0]for i in [14,15,17,18,19,22]]
roadOld=sum(len(buf['indices'])//3 for buf in a['buffers']if a['materials'][buf['material']][0]in protectedNames)+sum(len(z['indices'])//3 for z in parse(c/'ReverseRamp.spm')['buffers']);roadNew=sum(len(buf['indices'])//3 for buf in b['buffers']if b['materials'][buf['material']][0]in protectedNames)+sum(len(z['indices'])//3 for z in parse(c/'ReverseRamp.spm')['buffers']);assert roadOld==2032 and roadNew==1968
sceneold=E.parse(old/'scene.xml').getroot();scenenew=E.parse(c/'scene.xml').getroot();changed={q['after']['id']:q for q in p['cloudPoses']};assert len(sceneold)==len(scenenew)
for u,v in zip(sceneold,scenenew):
 if u.tag=='sun':assert u.attrib==p['sunBefore']and v.attrib==p['sunAfter']
 elif u.get('id')in changed:assert v.attrib==changed[u.get('id')]['after'];assert all(u.get(k)==v.get(k)for k in ['id','xyz','hpr','scale'])
 else:assert E.tostring(u)==E.tostring(v),u.attrib
oldmat=E.parse(old/'materials.xml').getroot();newmat=E.parse(c/'materials.xml').getroot();removed=p['removedUnreferencedMaterialEntries'];assert [dict(e.attrib)for e in oldmat if e.get('name')not in [m['name']for m in removed]]==[dict(e.attrib)for e in newmat];assert all('acid_lake.jpg'not in E.tostring(e,encoding='unicode')for e in oldmat)
# The installed global material definitions contain noacid_lake.jpg override; plain acid/default-color both use the same default solid material physics.
globalmat=Path('/Users/motoricallc/Library/Developer/CoreSimulator/Devices/3B2F19DC-4F76-4F61-9F8D-D5E914A6D123/data/Containers/Bundle/Application/30BBBB18-D57B-403B-B7C4-4EAF135EFA7D/Fluxara Drift.app/data/textures/materials.xml');assert E.parse(globalmat).getroot().find('material[@name="acid_lake.jpg"]')is None
cl0=parse(p['cloudSourceModel']['path']);cl1=parse(p['newCloudModel']['path']);assert cl0['bounds']==cl1['bounds']and cl0['flags']==cl1['flags']and cl0['materials']==cl1['materials']and len(cl0['raw'])==len(cl1['raw']);assert cl0['buffers'][0]['indices']==cl1['buffers'][0]['indices'];assert all(all(u.get(k)==v.get(k)for k in ['position','normal','uv','uv2'])for u,v in zip(cl0['buffers'][0]['vertices'],cl1['buffers'][0]['vertices']))
removedfile=p['removedUnreferencedImage'];assert sha(removedfile['preservedSource'])==removedfile['sha256']and not(c/Path(removedfile['path']).name).exists();res=Path('/Users/motoricallc/Downloads/fluxara-drift/iosApp/FluxaraResources');assert sha(res/'textures/fluxara_volcano_stone_shared_v16.jpg')=='6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd'
size=sum(f.stat().st_size for f in c.iterdir()if f.is_file());newbytes=sum(f.stat().st_size for f in(w/'shared-runtime').rglob('*')if f.is_file());total=size+newbytes+p['acceptedSharedHistoryIncludingV38Bytes'];assert total==p['allCandidateAndAcceptedHistoryBytes'];budget=[{'object':'fourOriginalConeRoofs','oldUsedTextureBytes':13633,'newUsedTextureBytes':5072,'modelGeometryByteBudgetReducedBySplitIndexPacking':True,'withinPlus20Percent':True},{'object':'oldAcidColoredFloor','oldUsedTextureBytes':6553,'newUsedTextureBytes':0,'modelBufferBytesReducedDespiteVertexColors':True,'withinPlus20Percent':True},{'object':'cloud','oldModelBytes':len(cl0['raw']),'newModelBytes':len(cl1['raw']),'usedTextures':0,'withinPlus20Percent':True}]
proof={'baseCandidate':'V38','protectedControlsExactV1':True,'allOriginalMainVertexPositionsNormalsTrianglesAndBoundsExactV38':True,'previousConservativeRoadTriangles':2032,'trueProtectedDrivingTriangles':1968,'decorativeRoofTrianglesSeparatedFromPreviousConservativeRoadCount':64,'allActualRoadUVColorsMaterialsAndGeometryExactV38':True,'allOtherCandidateFilesAndCollisionFilesExactV38':True,'allOriginalSceneObjectAndLibraryTransformsExactV38':True,'allMaterialPhysicsSettingsUnchanged':True,'globalAcidMaterialOverrideAbsent':{'path':str(globalmat),'sha256':sha(globalmat)},'sourceStonePixelsRetained':True,'noNewRasterPixels':True,'objectModelPlusUsedTextureBudgets':budget,'newCloudGeometryBoundsWeightAndNormalsExactV38':True,'candidateAllFilesBytes':size,'acceptedSharedHistoryIncludingV38Bytes':p['acceptedSharedHistoryIncludingV38Bytes'],'newSharedRuntimeAllFilesBytes':newbytes,'allCandidateAndAcceptedHistoryBytes':total,'savingVsV38Bytes':p['savingVsV38Bytes'],'v1Bytes':p['v1Bytes'],'savingVsV1Bytes':p['v1Bytes']-total,'productionIntegrated':False,'referenceAcceptance':False};(w/'preservation-verification.json').write_text(json.dumps(proof,indent=2));print('V39_INDEPENDENT_GEOMETRY_ROAD_PHYSICS_AND_WEIGHT_VERIFIED',total,flush=True)
