from pathlib import Path
import json,shutil,hashlib,re
r=Path(__file__).resolve().parent;w=r/'fidelity-v9';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v9';e.mkdir(exist_ok=True);page=out/'index.html';b=json.loads((w/'budget.json').read_text());skin=json.loads((w/'skin-changes.json').read_text())
for name in ['castle-changes.json','skin-changes.json','preservation.json','budget.json','runtime-validation.json','drive-capture.json','smoke-diagnostic-all.json','final-blend-verification.json','canonical-bindings-verification.json','pool-audit.json']:shutil.copy2(w/name,e/name)
shutil.copy2(w/'screenshots/smoke-diagnostic-all.png',out/'screenshots/fidelity-v9-castle-overview.png')
section=f'''<section id="fidelity-v9-draft"><h2>Доработка V9 — настоящие красные крыши</h2><p>Верх двух общих башен заменён шестнадцатигранной конической крышей. Красный цвет взят из существующей палитры; донор и его материалы не изменены. Основание и оси прототипа, его внешние локальные границы и габариты совпадают с донором. Нижняя геометрия башни сохранена, верхние зубцы и шест заменены крышей.</p><table><tr><th>Показатель</th><th>Результат</th></tr><tr><td>Модель вместе с текстурой</td><td>{skin['modelWithTextureBeforeBytes']:,} → {skin['modelWithTextureAfterBytes']:,} байт; {skin['weightChangePercent']:.2f}%</td></tr><tr><td>Карта с новыми общими файлами</td><td>{b['newBytesIncludingNewSharedRuntime']:,} байт; экономия {b['savedBytesAgainstPrevious']:,} байт к V1</td></tr><tr><td>Учёт новых общих файлов</td><td>{b['activeV9SharedRuntimeBytes']:,} байт активной библиотеки V9 и {b['retainedPreviousV8BSharedRuntimeBytes']:,} байт предыдущей библиотеки V8B, пока сохранённой в ресурсах проекта. Обе копии учтены.</td></tr><tr><td>Треугольники башни / карты</td><td>{skin['triangles']} / {b['candidateTriangles']:,}; справочно</td></tr></table><p>Исходные дорога и игровые XML совпадают, геометрия столкновений сохранена. Проверены Blender, SPM, матрицы размещений, общий каталог и неизменность свечения окон других карт.</p><p>Заезд завершился естественно; кадр результата после перезапуска симулятора оказался обрезан из-за портретной ориентации, поэтому читаемая позиция #1 и качественные игровые кадры V9 не заявляются. Ориентация исправлена, отдельный статический обзор переснят. Старые обрезанные кадры сохранены в истории и не используются для визуального согласования.</p><p class="note">V9 остаётся кандидатом. Стены замка, скалы, лава и дым требуют дальнейшей доработки. Основная карта, финальный .blend и превью остаются V1; нового билда не было.</p><p><a href="../../volcano-remake-rework/fidelity-v9/native/Volcano%20Remake.blend">Blender V9</a> · <a href="evidence/fidelity-v9/skin-changes.json">Модель и вес</a> · <a href="evidence/fidelity-v9/budget.json">Все игровые ресурсы</a> · <a href="evidence/fidelity-v9/runtime-validation.json">Ограничения проверки заезда</a> · <a href="evidence/fidelity-v9/pool-audit.json">Пул</a></p><figure><a href="screenshots/fidelity-v9-castle-overview.png"><img src="screenshots/fidelity-v9-castle-overview.png" alt="Красная крыша общей башни V9"></a><figcaption>Отдельная статическая камера в движке. Красная коническая крыша реализована; это не кадр заезда.</figcaption></figure></section>'''
s=re.sub(r'<section id="fidelity-v9-draft">.*?</section>','',page.read_text(),flags=re.S).replace('<section id="fidelity-v8b-draft">',section+'<section id="fidelity-v8b-draft">',1).replace('Последняя доработка — V8B','Предыдущая доработка — V8B');page.write_text(s)
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for p in [pack/'sources/volcano-remake-reference-v1/report']+list((pack/'sources').glob('volcano-remake-fidelity-*/report'))+[pack/'sources/volcano-remake-fidelity-v9/report']:shutil.copytree(out,p,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v9'/Path(__file__).name)
print('V9_REPORT_UPDATED')
