from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v30';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v30';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text())
assert run['naturalFinishObserved']and native['allOtherNativeMeshesAndMatricesExactV29']==626
for f in w.glob('*.json'):
    if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
figures=[]
for second,caption in [(40,'Справа вдоль дороги видны крупные каменные выступы и кроны деревьев. Исходная каменная фактура сохранена; новые группы заполняют промежутки между прежними небольшими уступами.'),(140,'Подъём на другом участке маршрута. Полотно, знак поворота и игровые точки сохранены; этот вид также показывает, что окружение ещё не везде соответствует референсу.')]:
    name=f'fidelity-v30-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name)
    figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V30"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
for name,src in [('fidelity-v30-overview.png',w/'screenshots/smoke-diagnostic-all.png'),('fidelity-v30-natural-finish.png',w/'screenshots/natural-finish.png'),('fidelity-v30-ramp-80.png',w/'screenshots/drive-80s.png'),('fidelity-v30-extra-result.png',w/'screenshots/drive-supplemental.png')]:shutil.copy2(src,out/'screenshots'/name)
tree=json.loads((w/'direct-tree-reuse.json').read_text());treebytes=sum(q['bytes']for q in tree['runtimeFiles']if q['path'].endswith(('.spm','.png')))+tree['globalLeaf']['bytes'];assert treebytes==126155
section=f'''<section id="fidelity-v30-draft"><h2>Последняя доработка — V30: крупные каменные группы и деревья из пула</h2>
<p>На десятую карту добавлены 24 крупные группы: каменное основание, зелёная шапка и объёмное лиственное дерево. Они выбирались по высоким декоративным граням существующих склонов вокруг маршрута. Большие каменные тела высотой от основания −40 м до выбранного верха заполняют промежутки между прежними маленькими выступами. Это добавленные декорации; исходные стены остались за ними. Замена всей видимой исходной массы в этой версии не выполнена.</p>
<p>Все три модели взяты из физического общего пула без изменения сеток, UV, нормалей, цветов, локальных габаритов, начала координат или осей. Камень — ранее адаптированный общий V29, зелёная шапка — компонент V27, дерево — существующая объёмная модель DP Motorsports. Для 72 частей записаны координаты, направление и масштаб; отдельная модель на каждое размещение не создавалась. Деревья поставлены на фактические треугольники зелёных шапок, а не на центры объектов; контакт всех 24 корней с поверхностью проверен независимо.</p>
<p>Текстура камня по замечанию пользователя сохранена: 39&nbsp;938 байт, SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Дерево, палитра и текстура листьев уже были в приложении; файлы установленной библиотеки, исходника и физического пакета совпали. Новых изображений, материалов или игровых моделей нет.</p>
<table><tr><th>Общая модель с используемыми текстурами</th><th>До, байт</th><th>После, байт</th></tr>
<tr><td>Каменное основание</td><td>42&nbsp;471</td><td>42&nbsp;471</td></tr>
<tr><td>Зелёная шапка с цветами вершин</td><td>3&nbsp;866</td><td>3&nbsp;866</td></tr>
<tr><td>Лиственное дерево с палитрой и листьями</td><td>{treebytes:,}</td><td>{treebytes:,}</td></tr></table>
<p>Вес каждой модели с её текстурами не изменился; верхний предел +20% соблюдён. Новые координаты добавили {b['changeBytesAgainstIntermediateV29']:,} байт. Общий вес рабочего варианта карты со всеми ранее добавленными общими игровыми ресурсами — {b['candidateIncludingNewSharedBytes']:,} байт: меньше интегрированного V1 ({b['v1Bytes']:,}) на {b['savingBytesVsV1']:,} байт, или {b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%. Добавленный игровой ресурсный payload — 0 байт; увеличение веса здесь относится только к описанию размещений. Размер свежей сборки приложения не измерялся.</p>
<p>Все исходные файлы карты кроме scene.xml совпадают с V29. Все прежние узлы scene.xml, включая физику, эффекты и игровые структуры, сохранены; добавлены только новые библиотечные экземпляры. Независимо проверены {b['independentlyCheckedNewRenderedTriangles']:,} новых видимых треугольников относительно 2&nbsp;032 защищённых треугольников проезда. Минимальный запас до дороги — {b['independentAllNewPartRoadMarginMeters']:.3f} м. Итоговый пользовательский проект и установленная основная карта по-прежнему соответствуют V1.</p>
<p>В Blender добавлены 72 части и один прямо переиспользованный прототип дерева. Все 626 прежних мешей и их матрицы совпали с V29. Геометрия, UV, нормали, все цветовые атрибуты и материалы дерева точно совпали с его донорским нативным файлом; позиции 588 экспортированных треугольников и локальный габарит также сопоставлены с игровой моделью. В ведомости 38 прототипов и 94 определения материалов, из них два добавленных в проект материала прямо переиспользованы с деревом. Всего 412 общих размещённых частей.</p>
<p>Каноническая библиотека не менялась: все используемые модели и материалы уже есть в ней. Ведомость теперь содержит {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов с историческими источниками; их реальные файлы, хеши и зависимости проверены. В общем индексе {audit['uniquePoolIds']} уникальных ID, новых ресурсов не добавлено. Существующим моделям отмечено применение на карте 10.</p>
<p>Полный круг Time Trial завершился естественным <a href="screenshots/fidelity-v30-natural-finish.png">результатом #1</a>, без принудительной победы. Проверены кадры 40, <a href="screenshots/fidelity-v30-ramp-80.png">80 — исходная наклонная рампа с ускорителем</a>, 140 и 190 секунд. Дополнительный кадр оказался уже <a href="screenshots/fidelity-v30-extra-result.png">экраном результата</a>; он не выдаётся за второй дорожный ракурс. Опасное прохождение рампы наблюдалось ранее и в V1; причина не исправлена и все регрессии не исключены. Временная карта и скопированные ресурсы убраны из установленного приложения; существующие деревья, факелы, эффекты и холмы не менялись. Предупреждения материалов совпали с предыдущей проверкой.</p>
<p>Два дорожных кадра ниже и <a href="screenshots/fidelity-v30-overview.png">обзор из игрового движка</a> сохранены без ретуши. Виды разных запусков не заявляются как одинаковые покадровые траектории. Крупные выступы и деревья видны вдоль дороги, но сходство с референсом ещё неполное: исходная большая центральная масса, дальние стены, замок, зелёные шапки и атмосфера требуют дальнейшей работы.</p>
<p class="note">Это проверенный промежуточный вариант. Основная карта, итоговый пользовательский .blend и превью пока V1. Новая сборка, производительность, обратный режим и вся кампания не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v30/native/Volcano%20Remake.blend">Blender V30</a> · <a href="evidence/fidelity-v30/preservation-verification.json">Размещения, дорога и вес</a> · <a href="evidence/fidelity-v30/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v30/direct-tree-reuse.json">Физический пул и дерево</a> · <a href="evidence/fidelity-v30/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v30/pool-audit.json">Ведомость</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v30-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V29','Предыдущая доработка — V29');s=s.replace('<section id="fidelity-v29-draft">',section+'<section id="fidelity-v29-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v30/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v30'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V30 adds24large grass/stone facade groups and24existing pooled leaf trees by coordinates. Source models/pixels/local dimensions and existing road/physics/control nodes unchanged. Native/canonical/direct reuse ledger and natural full lap #1 verified. Main terrain/castle/green caps/atmosphere/reference fidelity unfinished; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V30','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':38,'candidatePrototypeIdsReferencedByNativeSharedParts':22,'candidateNativeSharedParts':412,'candidateAdditionalLargeCliffGroups':24,'candidateAdditionalLeafTrees':24,'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V30';data.pop('inProgressCandidate',None);data['status']='V30 verified:24 large pooled cliff facade groups and24existing round leaf trees,72 coordinate parts. All source models/pixels/physics/controls retained. Weight6,668,587B, natural full lap#1; native/canonical/ledger/report checked. Reference fidelity and production/final/preview integration unfinished.';data['workingEvidence']['V30']='Terminal: source/independent road verification24,480triangles, min3.29903188m;24 tree roots on real cap triangles. Native626other meshes/matrices exactV29; reused source tree/native/runtime geometry verified; canonical unchanged. Pool4148IDs,335ledgerassets,0newassetpayload,14,342B scene coordinates. Full natural lap#1.'
data['nextVisibleTarget']='Improve reference composition beyond added scenery: green caps are too thin/flat, broad original central/distant terrain remains; castle gate proportions and red roof/flags, blue/gold sky and warm continuous plume need work. Preserve road, original collision, gameplay controls and current stone pixels; source references/donors untouched.'
for q in data['priorities']:
    if q['role']=='Rounded central cliff support and green terrain':q.update({'completedCandidate':'V30 partial','remaining':data['nextVisibleTarget']})
plan.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('V30_REPORT_UPDATED',len(m['files']),flush=True)
