from pathlib import Path
import json,shutil,re
r=Path(__file__).resolve().parent;w=r/'fidelity-v11';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v11';e.mkdir(exist_ok=True);page=out/'index.html';budget=json.loads((w/'budget.json').read_text());runtime=json.loads((w/'runtime-validation.json').read_text());assert runtime['candidateOneLapTimeTrial']['naturalFinishObserved'];assert json.loads((w/'final-blend-verification.json').read_text())['all23PrototypeGeometryUvsNormalsMatchV10B']
for p in w.glob('*.json'):shutil.copy2(p,e/p.name)
fig=[]
for second in [40,80]:
 name=f'fidelity-v11-game-{second}s.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name);fig.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V11"></a><figcaption>Заезд V11 в iOS Simulator, {second} секунд после запуска; каменная текстура сохранена.</figcaption></figure>')
overview='fidelity-v11-smoke-overview.png';shutil.copy2(w/'screenshots/smoke-diagnostic-all.png',out/'screenshots'/overview)
section=f'''<section id="fidelity-v11-draft"><h2>Последняя доработка — V11: дым над вулканами</h2><p>Три ранее оторванных от вулканов дымовых шлейфа уменьшены до 45% прежнего мирового масштаба. Их основания совмещены с верхними кольцами исходных вулканов и заглублены на два метра, чтобы убрать разрыв. Использованы прежние общие модели: новые модели и текстуры не добавлялись. Каменная текстура V10B и красные крыши сохранены.</p><p>Все SPM и текстуры побайтно совпадают с V10B. В scene.xml изменены только три размещения декоративного дыма с interaction=ghost. Полотно трассы, игровые точки, условные объекты и движущиеся препятствия совпадают с предыдущим вариантом. Все 23 прототипа Blender имеют прежние вершины, индексы, UV и нормали; новые матрицы трёх размещений проверены после открытия файла.</p><table><tr><th>Показатель</th><th>Результат</th></tr><tr><td>Модели с текстурами</td><td>0% изменения веса</td></tr><tr><td>Карта и новые общие ресурсы</td><td>{budget['newBytesIncludingNewSharedRuntime']:,} байт; экономия {budget['savedBytesAgainstPrevious']:,} байт к V1</td></tr><tr><td>Новые игровые файлы библиотеки</td><td>0; ранее созданные V8B/V9 включены в расчёт</td></tr><tr><td>Заезд</td><td>Один круг Time Trial, естественное завершение #1</td></tr></table><p class="note">Доработка к референсу продолжается. Старый столб лавы относится к исходным объектам; его роль и поведение сохраняются до отдельной проверки. Стены замка, силуэты скал, лава и форма дыма ещё требуют улучшения. Production, финальный .blend и превью остаются V1; новый билд не создавался. Полная кампания, обратный режим и FPS не проверены.</p><p><a href="../../volcano-remake-rework/fidelity-v11/native/Volcano%20Remake.blend">Blender V11</a> · <a href="evidence/fidelity-v11/smoke-placement-changes.json">Размещения дыма</a> · <a href="evidence/fidelity-v11/preservation.json">Сохранность</a> · <a href="evidence/fidelity-v11/budget.json">Вес</a> · <a href="evidence/fidelity-v11/runtime-validation.json">Заезд</a> · <a href="screenshots/{overview}">Общий статический обзор в движке</a></p>{''.join(fig)}</section>'''
s=re.sub(r'<section id="fidelity-v11-draft">.*?</section>','',page.read_text(),flags=re.S).replace('<section id="fidelity-v10b-draft">',section+'<section id="fidelity-v10b-draft">',1).replace('Последняя доработка — V10B','Предыдущая доработка — V10B');page.write_text(s)
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report']+list((pack/'sources').glob('volcano-remake-fidelity-*/report'))+[pack/'sources/volcano-remake-fidelity-v11/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v11'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';d=json.loads(progress.read_text());d['maps']['10'].update({'status':'V11 three smaller decorative smoke placements at volcano vents; stone texture retained. Models unchanged from verified V10B. One natural TT lap; native and asset reuse verified. Reference fidelity unfinished, production and preview unchanged.','candidate':str(w),'candidateTrackBytes':budget['candidateTrackBytes'],'candidateBytesIncludingNewSharedRuntime':budget['newBytesIncludingNewSharedRuntime'],'candidateSavedBytesAgainstPrevious':budget['savedBytesAgainstPrevious'],'candidateOneLapNaturalFinish':True,'candidateProductionIntegrated':False,'fullyAccepted':False});d['goalComplete']=False;progress.write_text(json.dumps(d,ensure_ascii=False,indent=2));print('V11_REPORT_UPDATED',flush=True)
