from pathlib import Path
import json,shutil
r=Path(__file__).resolve().parent;w=r/'delivery-v1';final=r.parent/'fluxara-user-spell-lab-final';report=final/'report';weights=json.loads((w/'weight.json').read_text());n=json.loads((w/'native-verification.json').read_text());shots=w/'screenshots/candidate';(report/'screenshots').mkdir(exist_ok=True);evidence=report/'evidence/coordinate-reuse';evidence.mkdir(parents=True,exist_ok=True)
for f in shots.glob('*.jpg'):shutil.copy2(f,report/'screenshots'/('coordinate-'+f.name))
for name in ['weight.json','native-verification.json','canonical-reuse-verification.json','preservation.json','asset-registration.json','integration.json','screenshots.json']:shutil.copy2(w/name,evidence/name)
old=report/'index.html';prior=report/'before-coordinate-reuse.html'
if not prior.exists():shutil.copy2(old,prior)
s=prior.read_text();before,body=s.split('<main>',1);history,after=body.rsplit('</main>',1);fmt=lambda x:f'{x:,}'.replace(',',' ')
section=f'''<div class="label">FLUXARA DRIFT · КАРТА 04 · 02.10.2026</div><h1>Spell Lab — общий пул и зелень на площадках</h1><p class="lead">284 существующие части окружения переведены в восемь общих моделей. На 36 существующих озеленённых площадках добавлены 180 кустов: каждый собран из трёх перекрывающихся крон из того же пула. Всего 824 части размещаются по координатам.</p>
<p>Сохраняются прежние размеры, центры и направления исходных моделей. Новые кусты стоят на существующем газоне; нижняя часть групп заглублена на 8 сантиметров. Полотно, контрольные точки, граф, игровые объекты, анимации и скрипты сохранены. Восемь геометрий и изображения уже есть в физической библиотеке; новые варианты их геометрии, материалов или текстур не создавались.</p>
<p>Палитра общая с Dust Cross: используется уже установленный алиас fluxara_pool_9f8d36974e14.png. Её 292 191 байт повторно не добавляются к приложению. 17 152 повторявшихся треугольника удалены из запечённой сборки и представлены экземплярами восьми моделей.</p>
<table><tr><th>Ресурсы этапа</th><th>Байты</th></tr><tr><td>Исходная папка карты</td><td>{fmt(weights['originalBytes'])}</td></tr><tr><td>Карта после изменений с новым превью</td><td>{fmt(weights['candidateOwnBytes'])}</td></tr><tr><td>Восемь новых общих экспортов моделей с XML</td><td>{fmt(weights['newSharedGameBytes'])}</td></tr><tr><td>Новое превью кампании, учтено целиком</td><td>{fmt(weights['campaignThumbnailBytesChargedInFull'])}</td></tr><tr><td>Итог: карта + новые общие ресурсы + превью кампании</td><td>{fmt(weights['candidateTotalBytes'])}</td></tr><tr><td>Уменьшение</td><td>{fmt(weights['savingBytes'])} ({weights['savingPercent']:.2f}%)</td></tr></table>
<p>Изменения сохранены в ресурсах проекта, установленном приложении iOS Simulator и единственном итоговом Spell Lab.blend. Новое превью в игре получено из текущей сцены игрового движка с техническим уменьшением и JPEG-конвертацией. Новая сборка приложения и новый заезд для проверки прохождения не выполнялись.</p>
<figure><img src="screenshots/coordinate-overview.jpg"><figcaption>Общий вид текущей карты. Кадр движка со статичной камерой; источник обновлённого превью.</figcaption></figure><figure><img src="screenshots/coordinate-garden-close.jpg"><figcaption>Кустовые группы из общего пула на существующей озеленённой площадке. Кадр движка со статичной камерой.</figcaption></figure><figure><img src="screenshots/coordinate-gardens.jpg"><figcaption>Лабораторная часть карты с дополненными площадками. Кадр движка со статичной камерой.</figcaption></figure>
<p><a href="evidence/coordinate-reuse/weight.json">Вес</a> · <a href="evidence/coordinate-reuse/preservation.json">Сохранность исходных ресурсов</a> · <a href="evidence/coordinate-reuse/native-verification.json">Размещения в Blender</a> · <a href="evidence/coordinate-reuse/integration.json">Сохранение в проекте и симуляторе</a></p><details><summary>Предыдущий отчёт, исходный референс и ранее сохранённые игровые кадры</summary>{history}</details>'''
old.write_text(before+'<main>'+section+'</main>'+after)
lp=r.parent.parent/'fluxara-user-spell-lab.asset-ledger.json';ledger=json.loads(lp.read_text());ledger['coordinateReusePhase']['report']=str(old);ledger['coordinateReusePhase']['screenshots']=json.loads((w/'screenshots.json').read_text());lp.write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n')
progressPath=r.parent/'shared-placement-1-10/progress.json';progress=json.loads(progressPath.read_text());progress['maps']['4']={'trackId':'fluxara-user-spell-lab','status':'Coordinate scenery integrated with 180 three-part shrubs on 36 existing pads; matching preview and report saved. User art review pending.','sourceAndInstalledIntegrated':True,'storageConversionInstances':284,'uniqueModels':8,'newShrubGroups':180,'newCoordinateParts':540,'totalCoordinateParts':824,'newSharedGameBytes':weights['newSharedGameBytes'],'newTextureBytes':0,'originalWeightBytes':weights['originalBytes'],'trackPlusNewSharedAndCampaignPreviewBytes':weights['candidateTotalBytes'],'savingBytes':weights['savingBytes'],'report':str(old),'newDrivingTestPerformed':False,'newBuildPerformed':False,'fullyAccepted':False};progress['stage']='Map 4 coordinate scenery, enrichment, preview and report saved. Cross-map work remains active.';progress['goalComplete']=False;progressPath.write_text(json.dumps(progress,ensure_ascii=False,indent=2)+'\n');archive=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK/sources/spell-lab-shared-placement-v1');archive.mkdir(parents=True,exist_ok=True)
for f in r.glob('*.py'):shutil.copy2(f,archive/f.name)
for f in w.glob('*.json'):shutil.copy2(f,archive/f.name)
shutil.copytree(shots,archive/'screenshots',dirs_exist_ok=True);shutil.copytree(report,archive/'report',dirs_exist_ok=True);shutil.copy2(lp,archive/lp.name);print('SPELL_REPORT_AND_PROGRESS_SAVED',weights['savingBytes'],flush=True)
