from pathlib import Path
import hashlib,json,re,shutil,subprocess
r=Path(__file__).resolve().parent;w=r/'fidelity-v39';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v39';e.mkdir(exist_ok=True);b=json.loads((w/'preservation-verification.json').read_text());n=json.loads((w/'final-blend-verification.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());assert run['naturalFinishObserved']and not n['canonicalPending']
for f in w.glob('*.json'):
 if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
for dest,src in [('fidelity-v39-game-40.png','drive-40s.png'),('fidelity-v39-game-80.png','drive-80s.png'),('fidelity-v39-game-140.png','drive-140s.png'),('fidelity-v39-natural-finish.png','natural-finish.png'),('fidelity-v39-overview.png','smoke-diagnostic-all.png'),('fidelity-v39-lake-inspection.png','smoke-diagnostic-lake.png')]:shutil.copy2(w/'screenshots'/src,out/'screenshots'/dest)
for folder,jsonfile in [('rejected-yellow-lake-diagnostic','rejection.json'),('interrupted-tint-capture','status.json')]:
 target=e/folder;target.mkdir(exist_ok=True);shutil.copy2(w/folder/jsonfile,target/jsonfile)
section=f'''<section id="fidelity-v39-draft"><h2>Рабочий V39: тёплый свет, черепица и нижняя лавовая площадка</h2>
<p>Каменная фактура сохранена без изменения пикселей: 39&nbsp;938 байт, SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Свет и окружающее освещение стали теплее, восемь облаков получили более светлые цвета вершин. Новых растровых изображений нет.</p>
<p>Четыре исходные конусные крыши получили фактуру уже используемой черепичной версии: тот же кирпичный рисунок 5&nbsp;072 байта, терракотовый цвет вершин и новые UV. Позиции всех вершин, нормали, 64 треугольника и мировые положения крыш сохранены. Деревянный мост и ограждения отделены от крыш только в таблице отрисовываемых буферов; их прежние UV, цвета и физический материал не менялись. Количество вершин и треугольников всего главного меша совпало с V38, его вес уменьшился на 484 байта.</p>
<p>Старая кислотно-зелёная acid_lake.jpg была назначена нижней плоскости из двух треугольников. Теперь её внешний вид задают красно-оранжевые цвета вершин без новой текстуры. Это решение снижает вес логического объекта с используемыми изображениями; новая большая лавовая текстура вышла бы за его бюджет +20%. Геометрия плоскости и физические настройки сохранены, слой сброса над ней не менялся. Первая попытка выглядела слишком жёлтой и <a href="evidence/fidelity-v39/rejected-yellow-lake-diagnostic/rejection.json">отклонена</a>. Пересмотренный цвет проверен в <a href="screenshots/fidelity-v39-lake-inspection.png">отдельном обзоре движка</a> и повторном игровом проезде. Нижняя площадка всё ещё выглядит проще, чем лава на референсе.</p>
<p>Полотно, точки, линии, quads/graph, сценарий, track.xml, игровые предметы и все исходные физические оболочки сохранены. Прежняя оценка 2&nbsp;032 «дорожных» треугольника включала 64 декоративных треугольника четырёх крыш в общем деревянном буфере. После их отделения фактических защищённых дорожных треугольников — 1&nbsp;968, включая условную обратную рампу. Ни один из прежних 2&nbsp;032 треугольников не потерян и не перемещён; изменены только UV, цвет и визуальный материал крыш. Материальные настройки физики не менялись. Все мировые матрицы прежних 821 Blender-объекта совпали с V38.</p>
<p>Неиспользуемая fluxara_drifttex_generic_lavaA.png (283&nbsp;993 байта) и её неиспользуемая запись материала убраны только из копии экспорта. Все собственные SPM, XML, сценарии и рекурсивные общие библиотеки проверены; исходный файл сохранён в V38 и пуле. Остальные файлы учитываются, даже когда не используются. Вес ресурсов карты с новыми общими файлами и принятой историей — <b>{b['allCandidateAndAcceptedHistoryBytes']:,} байт</b>: {b['candidateAllFilesBytes']:,} файлов карты + {b['acceptedSharedHistoryIncludingV38Bytes']:,} прежних общих ресурсов + {b['newSharedRuntimeAllFilesBytes']:,} новой общей версии облака/XML. Это на {b['savingVsV1Bytes']:,} байт ({b['savingVsV1Bytes']/b['v1Bytes']*100:.2f}%) меньше V1 и на {b['savingVsV38Bytes']:,} байт меньше V38. Ограничение +20% проверено для моделей с используемыми текстурами; размер новой сборки приложения не измерен.</p>
<p>Blender сохранён и открыт повторно: {n['meshObjects']} меш-объекта, {n['nativePrototypeCount']} прототипов, {n['nativeMaterialDefinitionCount']} определений материалов, {n['nativeSharedParts']} общих частей. {n['allOtherNativeMeshGeometryUVNormalsColorsMaterialsExactV38']} неизменённых мешей совпали с V38 по геометрии, UV, нормалям, цветам и материалам. В общий пул добавлена одна версия облака; прежние модели, 381 изображение и свечение окон домов сохранены. Пул содержит {audit['uniquePoolIds']} уникальных ID; реальные пути, размеры, хеши и зависимости проверены.</p>
<p>Окончательный вариант прошёл естественный полный круг Time Trial с <a href="screenshots/fidelity-v39-natural-finish.png">финишем #1</a>. Просмотрены игровые кадры 40, <a href="screenshots/fidelity-v39-game-80.png">80</a>, 140 и 190 секунд без ретуши. Один промежуточный захват кадра 140 секунд завершился ошибкой simctl; он <a href="evidence/fidelity-v39/interrupted-tint-capture/status.json">сохранён отдельно</a>, его старые кадры не выдаются за окончательный вариант. После очистки временной карты проведён новый полный заезд с записью статуса захвата каждого кадра. Прежние установленные факелы, деревья и холмы не менялись. На рампе AI по-прежнему выезжает за дорогу; это наблюдалось и в исходном V1. Полная проверка регрессий проезда не закрыта.</p>
<p class="note">Это рабочий вариант. Основная карта, итоговый пользовательский .blend и превью пока V1. Полное соответствие референсу ещё не подтверждено: зелёным краям и дальним зелёным площадкам нужен объём, лавовой площадке — более выразительный рисунок. Визуальное совпадение не заменяется проверками веса или проходимости. Новая сборка, вся кампания, обратный режим и производительность не проверены.</p>
<p><a href="../../volcano-remake-rework/fidelity-v39/native/Volcano%20Remake.blend">Blender V39</a> · <a href="evidence/fidelity-v39/preservation-verification.json">Полотно и вес</a> · <a href="evidence/fidelity-v39/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v39/runtime-validation.json">Заезд</a> · <a href="evidence/fidelity-v39/pool-audit.json">Пул</a></p>
<figure><a href="screenshots/fidelity-v39-game-40.png"><img src="screenshots/fidelity-v39-game-40.png" alt="Каменная фактура и тёплое освещение V39"></a><figcaption>Реальная камера гонщика: каменная фактура и прежнее полотно сохранены, освещение стало теплее.</figcaption></figure>
<figure><a href="screenshots/fidelity-v39-game-80.png"><img src="screenshots/fidelity-v39-game-80.png" alt="Каменные башни и черепичные крыши V39"></a><figcaption>Каменные башни, черепичные крыши и более светлые облака. Площадки зелёного окружения ещё требуют доработки по референсу.</figcaption></figure></section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v39-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v38-draft">',section+'<section id="fidelity-v38-draft">',1);s=re.sub(r'<div class="tags">.*?</div>','<div class="tags"><span>Рабочий V39</span><span>Вес −24.60% к V1</span><span>522 общих части</span></div>',s,count=1,flags=re.S);s=s.replace('fidelity-v38/native/Volcano%20Remake.blend">Рабочий Blender V38','fidelity-v39/native/Volcano%20Remake.blend">Рабочий Blender V39',1);page.write_text(s);manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
def clone(src,dst):
 dst=Path(dst)
 if dst.exists():
  if Path(src).read_bytes()==dst.read_bytes():return str(dst)
  dst.unlink()
 subprocess.run(['/bin/cp','-c',str(src),str(dst)],check=True);return str(dst)
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dst in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v39/report']:shutil.copytree(out,dst,dirs_exist_ok=True,copy_function=clone)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v39'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';a=json.loads(progress.read_text());a['maps']['10'].update({'status':'V39 source/native/canonical/pool/naturalTT#1 verified. Stonepixels, coursegeometry/worldposes retained. Warmlight/clouds, fourtexturedoriginalroofs, orange lowfloor.5,801,007B. Referencefidelity incomplete; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateAllFilesBytes'],'candidateBytesIncludingNewSharedRuntime':b['allCandidateAndAcceptedHistoryBytes'],'candidateSavedBytesAgainstPrevious':b['savingVsV1Bytes'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V39','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':50,'candidateNativeSharedParts':522,'fullyAccepted':False});a['goalComplete']=False;progress.write_text(json.dumps(a,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';a=json.loads(plan.read_text());a['baseCandidate']='V39';a['status']='V39 source/native/canonical/pool/finaltintnaturalTT#1 verified,5,801,007B. Allsourcepositions/normals/worldposes andactualroadUV/materials/controls/physics retained. Originalstonepixels unchanged. Fourcones textured. Initialyellow lake rejected; onecaptureerror archived, freshfullrun verified. Overallreferencefidelity andmain/final/previewintegration unfinished.';a['workingEvidence']['V39']='25mainbuffers same13,528tri/vertexcounts/geometrynorms source38; only4non-roadroof UV/material/color and2trianglelowfloor RGB/no texture changed. Previous2032roadcount included64rooftriangles; actual1968drivingincludingreverseRamp preserved. Warmambient and8cloudcolour-only sharedvariant same15446B; 2newpoolrecords,50nativeprotos99mats522parts. Unreferenced283993Balias preservedsource, removedonlycandidate. Native821allmatrixexact811othermeshattrsexact. Canonicalpriorassets381images/houseemissionretained. Finalfullrun#1. No integration/fidelity/performance/newbuildclaim.';a['nextVisibleTarget']='Finish coherent visible silhouettes/materials: sourcebound-preserving grass rolls and farterrain sidefaces within+20% model+usedtextures; oldorange lowfloor could use a compact vertexcoloured grid/flow pattern within its6553Boriginalusedtexture budget insteadofreturninglargeimage. Keep originalquad exactphysicalcollision ifretopologizingvisualfloor andallroad/control/stonepixels. Redwhitebendsidebarriers fromexistingSourceGeometry viaUV/RGB canimprove referencewithoutroadchanges. Verifywholegamecomposition thenintegrate10/final/preview. Do not substitute another compatibility-only colour/margin iteration for actualreference improvement; then finish3/4pendingintegrations/map7full11laps,1-10coordinateenrichment andpreviews.';a['diskHandling']='GeneratedV37report identical202files were replaced atomically byAPFSCOWclones with bytehashesandmetadata unchanged; original/data/native paths retained. Reclaimed~0.9GB; proof report-cow-compaction.json. UseCOW for backup/archive/reports, nooriginaldeletion. Canonicalcurrent39details in itscanonical-registration.json.';plan.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');print('V39_REPORT_SAVED',len(m['files']),flush=True)
