from pathlib import Path
import copy,hashlib,json,re,shutil,subprocess
r=Path(__file__).resolve().parent;w=r/'fidelity-v42';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v42';e.mkdir(exist_ok=True);b=json.loads((w/'preservation-verification.json').read_text());n=json.loads((w/'final-blend-verification.json').read_text());i=json.loads((w/'integration-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());assert i['workingSourceIntegrated']and run['naturalFinishObserved'];sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
for f in w.glob('*.json'):
 if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
for dest,src in [('fidelity-v42-game-40.png','integrated/drive-40s.png'),('fidelity-v42-game-80.png','integrated/drive-80s.png'),('fidelity-v42-natural-finish.png','integrated/drive-140s.png'),('fidelity-v42-overview.jpg','stone-scale-final/preview.jpg')]:shutil.copy2(w/'screenshots'/src,out/'screenshots'/dest)
percent=b['savingVsV1Bytes']/b['v1Bytes']*100
section=f'''<section id="fidelity-v42-stone-scale"><h2>V42: камень сохранён, мелкая фактура дальних скал укрупнена</h2>
<p>По замечанию пользователя эталоном служат крупные камни на скалах у решётчатого подъёма. Эти 97 отдельных скал сохранены без изменений. На шести дальних каменных массивах и каменных поверхностях основного ландшафта уменьшена частота повторения прежней текстуры в три раза: приблизительно с 28 до 84 метров на её полный повтор. Новое изображение не создавалось: прежние 39&nbsp;938 байт каменной текстуры сохранены побайтно. Это исправление двух групп мелкой развёртки, а не утверждение об идеальной геометрической равномерности всех UV на сложных поверхностях.</p>
<p>У двух изменённых моделей сохранился размер файла. Поменялись только байты UV каменных буферов: 210 вершин дальнего ландшафта и 743 вершины основного SPM. Геометрия, нормали, индексы, цвета, материальные слоты, границы, центры, оси и все матрицы сохранены. Полотно, физические материалы и программные точки совпадают с проверенной исходной трассой. При повторном открытии Blender подтверждены неизменность остальных 824 мешей и всех 826 прежних матриц.</p>
<p>Сохранены изменения рабочего V41: красно-белые цвета 128 существующих низких блоков у дороги и тёплая нижняя часть трёх дымовых объёмов. Геометрия этих объектов прежняя. Используется существующая палитра общего пула, без новых пикселей; увеличение веса каждой дымовой модели вместе с используемой текстурой составляет 13.64–14.34%, в пределах +20%.</p>
<p>Рабочая карта перенесена в основной каталог ресурсов и установленный iOS Simulator. Единственный пользовательский итоговый <a href="../Volcano%20Remake.blend">Volcano Remake.blend</a> обновлён; прежние исходники, установленная карта и прежний Blender сохранены вне итоговой папки. Превью теперь — настоящий обзор текущей карты, уменьшенный стандартным системным экспортом до 960 пикселей; исходный снимок движка сохранён без изменений. Общая библиотека содержит новый прототип и прежние материалы, изображения и свечение окон домов. Проверены 4194 уникальных ID общего пула.</p>
<p>Все файлы карты, новое превью, 67&nbsp;520 байт миниатюры кампании и вся принятая история общих игровых ресурсов: <b>{b['allCandidateAndAcceptedHistoryBytes']:,} байт</b> против {b['v1Bytes']:,} исходных. Экономия {b['savingVsV1Bytes']:,} байт ({percent:.2f}%). Превью изменилось со 101&nbsp;900 до 148,454 байт; эта разница включена в сумму. Исправление UV само по себе не увеличило модели. Общий размер новой сборки приложения не измерялся, новая сборка не выполнялась.</p>
<p>Проверен полный обычный круг Time Trial с естественным финишем #1. Ниже — два неретушированных игровых кадра основной карты, без временного ID трассы. <a href="screenshots/fidelity-v42-natural-finish.png">Финиш</a> · <a href="screenshots/fidelity-v42-overview.jpg">Обзор и новое превью</a> · <a href="evidence/fidelity-v42/preservation-verification.json">UV, геометрия и вес</a> · <a href="evidence/fidelity-v42/integration-verification.json">Интеграция</a>.</p>
<p class="note">Полное соответствие всей карты референсу и завершение общей работы по картам 1–10 ещё не заявлены. Один круг с одним участником не подтверждает все режимы, обратный проезд или производительность. Карты 6–9 в этом проходе не менялись. Нижние разделы сохраняют историю более ранних рабочих вариантов.</p>
<figure><a href="screenshots/fidelity-v42-game-40.png"><img src="screenshots/fidelity-v42-game-40.png" alt="Крупная каменная фактура дальних скал V42"></a><figcaption>Основная карта в игре: укрупнённая фактура дальних каменных поверхностей.</figcaption></figure>
<figure><a href="screenshots/fidelity-v42-game-80.png"><img src="screenshots/fidelity-v42-game-80.png" alt="Сохранённые эталонные скалы у подъёма V42"></a><figcaption>Эталонный участок: ближние скалы сохранены, геометрия подъёма прежняя.</figcaption></figure></section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v42-stone-scale">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v40-draft">',section+'<section id="fidelity-v40-draft">',1);s=re.sub(r'<div class="tags">.*?</div>',f'<div class="tags"><span>Рабочий V42 в игре</span><span>Вес −{percent:.2f}% к V1</span><span>522 общих части</span></div>',s,count=1,flags=re.S);page.write_text(s)
progress=r.parent/'shared-placement-1-10/progress.json';a=json.loads(progress.read_text());a['maps']['10'].update({'status':'V42 source/native/canonical/pool and ordinary natural TT verified. User stone-scale correction: mainstone and distantfield UV frequency /3, approved97 nearcliffs unchanged. Production source, simulator, sole finalblend and preview integrated. Fullreference acceptance remains open.','candidate':str(w),'candidateTrackBytes':b['candidateAllFilesBytes'],'candidateBytesIncludingNewSharedRuntime':b['allCandidateAndAcceptedHistoryBytes'],'candidateSavedBytesAgainstPrevious':b['savingVsV1Bytes'],'lastFullLapVerifiedCandidate':'V42','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':True,'candidateRegisteredNativePrototypes':55,'candidateNativeSharedParts':522,'fullyAccepted':False,'previewPath':i['preview']});a['goalComplete']=False;progress.write_text(json.dumps(a,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';a=json.loads(plan.read_text());a['baseCandidate']='V42';a['status']='Working V42 stone-scale correction integrated into source, simulator, sole finalblend and preview. Overallreference acceptance and complete1-10goal still pending.';a['nextVisibleTarget']='Preserve user-approved near-cliff stone texture appearance. Finish remaining reference discrepancies with concrete runtime evidence. Complete maps3/4 pending native/pool/runtime integration, map7 full11lap regression, then requested1-10coordinate enrichment and matching previews. Do not revert map10 source/final/preview to V1 or claim the overall goal complete.';plan.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n')
repo=Path('/Users/motoricallc/Downloads/fluxara-drift');pack=repo/'FLUXARA_TRACK_ASSET_PACK';poolfile=repo/'FLUXARA_TRACK_ASSET_POOL.json';pool=json.loads(poolfile.read_text());ledgerfile=w/'candidate-asset-ledger.json';ledger=json.loads(ledgerfile.read_text());ledger['productionIntegrated']=True;ledger['integration']=i;ledger['finalBlend']=i['finalBlend'];ledger['runtimeValidation']=run
for target in [pool,ledger]:
 for q in target['objects']:
  if q['id']in ['volcano-fidelity-v42-terrain-runtime']+[f'volcano-fidelity-v41-cloud-{stem}-runtime'for stem in ['ashcloud','ashcolumn','pyroclasticflow']]:q['productionIntegrated']=True
 target['assets']=target['objects']+target['materials']+target['textures']
poolfile.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n');ledgerfile.write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n');shutil.copy2(ledgerfile,e/ledgerfile.name)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':sha(f)}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
def clone(src,dst):
 dst=Path(dst)
 if dst.exists():
  if Path(src).read_bytes()==dst.read_bytes():return str(dst)
  dst.unlink()
 subprocess.run(['/bin/cp','-c',str(src),str(dst)],check=True);return str(dst)
arc=pack/'sources/volcano-remake-fidelity-v42'
for folder in ['candidate','native','screenshots','shared-runtime']:shutil.copytree(w/folder,arc/folder,dirs_exist_ok=True,copy_function=clone)
for f in w.glob('*.json'):
 if not f.name.startswith('pool-before'):shutil.copy2(f,arc/f.name)
for f in r.glob('*fidelity_v42*.py'):shutil.copy2(f,arc/f.name)
for f in r.glob('fidelity-v42*.log'):shutil.copy2(f,arc/f.name)
for dst in [pack/'sources/volcano-remake-reference-v1/report',arc/'report']:shutil.copytree(out,dst,dirs_exist_ok=True,copy_function=clone)
print('V42_INTEGRATED_REPORT_AND_ARCHIVES_SAVED',len(m['files']),flush=True)
