from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v13';repo=Path('/Users/motoricallc/Downloads/fluxara-drift');pack=repo/'FLUXARA_TRACK_ASSET_PACK';sources=pack/'sources/volcano-remake-fidelity-v13';sources.mkdir(exist_ok=True);mod=pack/'models/volcano-remake-fidelity-v13';canon=pack/'blender/FLUXARA_Track_Asset_Library.blend';pf=repo/'FLUXARA_TRACK_ASSET_POOL.json';a=json.loads((w/'asset-registration.json').read_text());pool=json.loads(pf.read_text());ledger=json.loads((r/'fidelity-v12/candidate-asset-ledger.json').read_text());assert json.loads((w/'canonical-registration.json').read_text())['newObjects']==1;assert json.loads((w/'final-blend-verification.json').read_text())['sharedLavaImagePixelsExactOriginal'];assert(w/'canonical-bindings-verification.json').is_file()
if not(w/'pool-before-v13.json').exists():shutil.copy2(pf,w/'pool-before-v13.json')
def info(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for name in ['build_fidelity_v13_fountain.py','verify_fidelity_v13_preservation.py','audit_fidelity_v13_model_weight.py','finalize_fidelity_v13.py','verify_fidelity_v13_native.py','register_fidelity_v13_canonical.py','verify_fidelity_v13_canonical.py','capture_fidelity_v13_drive.py','capture_fidelity_v13_inspection.py',Path(__file__).name]:shutil.copy2(r/name,sources/name)
for p in w.glob('*.json'):
 if not p.name.startswith('pool-before'):shutil.copy2(p,sources/p.name)
for folder in ['candidate','native','screenshots','iterations','original-component']:shutil.copytree(w/folder,sources/folder,dirs_exist_ok=True)
usage=[{'trackId':'fluxara-user-volcano-remake','candidate':'V13','instances':1,'status':'Lava fountain and connected smoke, source collision exact, stone texture retained. Candidate not integrated; overall reference fidelity unfinished.'}];base={'sourceMap':'fluxara-user-volcano-remake','categories':['lava'],'uses':usage};texture_name='fluxara_volcano_lava_shared_v13.jpg';tid='volcano-fidelity-v13-lava-texture-alias';oldtex=next(q for q in ledger['textures']if q.get('displayName')=='lava_2k_diffuse.jpg');texture=a['textures'][texture_name]
newtex={**base,'id':tid,'displayName':texture_name,'kind':'texture','reuseTier':'direct','canonicalPackPath':texture['packPath'],'physicalSourcePath':oldtex['canonicalPackPath'],'file':info(Path(texture['packPath'])),'dependencies':[oldtex['id']],'runtimePackagedPath':texture['source'],'runtimeIntegrated':False,'reason':'Original lava image bytes reused with a unique shared filename. Source images preserved; candidate-local duplicate omitted; shared alias bytes counted in budget.'};newmats=[]
for q in a['newMaterialVariants']:newmats.append({**base,**q,'displayName':q['name'],'kind':'material','reuseTier':'adapt','canonicalPackPath':str(canon)+'#Material/'+q['name'],'physicalSourcePath':a['visualLibrary'],'dependencies':[tid,q['sourceMaterialId']],'reason':'Source shader inputs and links retained in separate material variant; only shared texture filename changes.'})
newobj=[]
for q in a['newPrototypes']:
 deps=[next(m['id']for m in newmats if m['name']==n)for n in q['materials']];newobj.append({**base,**q,'displayName':q['name'],'kind':'visual-object','reuseTier':'authored','canonicalPackPath':str(canon)+'#Object/'+q['name'],'physicalSourcePath':a['visualLibrary'],'file':info(Path(a['visualLibrary'])),'dependencies':deps,'reason':'Reference-inspired curved lava jets and embers, authored in original effect bounds and origin axes. Gameplay collision remains exact in map-only proxy.'});source=Path(q['sourceModel']);stored=mod/source.name;newobj.append({**base,'id':'volcano-fidelity-v13-runtime-fountain','displayName':source.name,'kind':'runtime-model','reuseTier':'authored','canonicalPackPath':str(stored),'physicalSourcePath':str(source),'file':info(stored),'dependencies':deps,'runtimePackagedPath':str(source),'runtimeIntegrated':False,'libraryNode':str(source.parent/'node.xml'),'reason':'One exported shared scenery model, instantiated by coordinates. New shared source files are included in size budget.'})
new_by_key={'objects':newobj,'materials':newmats,'textures':[newtex]}
for key,items in new_by_key.items():
 pool[key]=[q for q in pool[key]if not q['id'].startswith('volcano-fidelity-v13-')]+items;ledger[key]=[q for q in ledger[key]if not q['id'].startswith('volcano-fidelity-v13-')]+items
ci=info(canon)
def refresh(v):
 if isinstance(v,dict):
  if v.get('path')==str(canon)and'sha256'in v:v.update(ci)
  for x in v.values():refresh(x)
 elif isinstance(v,list):
  for x in v:refresh(x)
refresh(pool);pool['physicalPack']['blenderLibrary']=ci;pool['updated']=datetime.now(timezone.utc).isoformat();ids=[q['id']for key in ['objects','materials','textures']for q in pool[key]];assert len(ids)==len(set(ids));pres=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text())if(w/'runtime-validation.json').is_file()else{'status':'Extended one-lap recording in progress','naturalFinishObserved':False}
ledger.update({'candidate':'V13 lava fountain with shared texture and connected plume','status':'Current isolated candidate. Original road and collision preserved; stone texture restored. Native and canonical bindings verified; overall visual fidelity unfinished.','finalBlend':a['finalBlend'],'nativeSharedParts':len(a['nativeSharedInstances']),'preservation':pres,'budget':pres,'runtimeValidation':run,'deltaAssetCounts':{'objects':2,'materials':6,'textures':1},'productionIntegrated':False,'newImagePixels':False,'newSharedLavaLibrary':a['runtimeLibrarySources']['fluxara_driftlib_volcano_fountain_v13']});ledger['assets']=ledger['objects']+ledger['materials']+ledger['textures'];ledger['mapRuntimeFiles']=[info(p)for p in(sources/'candidate').iterdir()if p.is_file()];ledger['mapOnlyProtectedCollision']=[q for q in ledger['mapOnlyProtectedCollision']if not isinstance(q,dict)or q.get('model')!='vr_v13_original_lava_column_collision.spm'];ledger['mapOnlyProtectedCollision'].append({'model':'vr_v13_original_lava_column_collision.spm','sourceColumnTriangles':72,'shape':'exact','interchangeableScenery':False})
for q in ledger['assets']:
 assert q['id']in ids;assert Path(q['canonicalPackPath'].split('#')[0]).is_file(),q['id'];assert Path(q['physicalSourcePath'].split('#')[0]).exists(),q['id'];assert all(dep in ids for dep in q.get('dependencies',[])),q['id']
 if q.get('file'):assert info(Path(q['file']['path']))==q['file'],q['id']
audit={'newObjects':2,'newNativePrototypes':1,'newMaterials':6,'newTextureAliases':1,'newImagePixels':False,'allPhysicalPathsAndFileHashesMatch':True,'uniquePoolIds':len(ids),'totalLedgerAssetsIncludingHistoricalSources':len(ledger['assets']),'unresolvedDependencies':[],'canonical':ci,'nativeSharedParts':152,'productionIntegrated':False};pf.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n');(w/'candidate-asset-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n');(w/'pool-audit.json').write_text(json.dumps(audit,indent=2))
for name in ['candidate-asset-ledger.json','pool-audit.json']:shutil.copy2(w/name,sources/name)
print('V13_POOL_REGISTERED',audit,flush=True)
