from pathlib import Path
import json,shutil,re
r=Path(__file__).resolve().parent;w=r/'fidelity-v13';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v13';e.mkdir(exist_ok=True);page=out/'index.html';b=json.loads((w/'preservation-verification.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text());f=json.loads((w/'fountain-changes.json').read_text());run=json.loads((w/'runtime-validation.json').read_text())if(w/'runtime-validation.json').is_file()else{};finished=run.get('candidateOneLapTimeTrial',{}).get('naturalFinishObserved',False)
for p in w.glob('*.json'):
 if not p.name.startswith('pool-before'):shutil.copy2(p,e/p.name)
figures=[]
for second in [40,80]:
 name=f'fidelity-v13-game-{second}s.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name);figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V13"></a><figcaption>Заезд V13 в iOS Simulator: {second} секунд после запуска. Каменная фактура и исходная дорога сохранены.</figcaption></figure>')
name='fidelity-v13-fountain-overview.png';shutil.copy2(w/'screenshots/smoke-diagnostic-all.png',out/'screenshots'/name);runtime='Полный круг Time Trial завершился естественно; результат #1. Сохранён читаемый экран завершения. Полная кампания, обратный режим и FPS этим заездом не проверены.'if finished else'Первый ограниченный заезд не успел закончить круг за 240 секунд записи; на последнем кадре игровое время 01:40. Повторный более длинный заезд ещё проверяется. Это не подтверждение полного прохождения.'
section=f'''<section id="fidelity-v13-draft"><h2>Последняя доработка — V13: извержение лавы</h2><p>Сплошной декоративный столб заменён тремя тонкими изогнутыми струями и 16 искрами. Существующий дымовой шлейф перенесён к струям. Общие габариты эффекта, исходная точка центра и оси сохранены. Прежняя геометрия столкновений хранится в отдельной скрытой модели этой карты и побайтно сохраняет ориентированные исходные треугольники.</p><p>Новая модель хранится в общей библиотеке fluxara_driftlib_volcano_fountain_v13; размещение записано координатами. Текстура лавы с прежними пикселями вынесена в общий файл fluxara_volcano_lava_shared_v13.jpg. Внутри варианта карты её дубликата нет. Шесть отдельных вариантов материалов сохраняют прежние настройки; материалы доноров не изменены. Текстура Rock13_col.jpg и исходные UV камня сохранены.</p><table><tr><th>Показатель</th><th>Результат</th></tr><tr><td>Карта с добавленными общими библиотеками и текстурой</td><td>{b['candidateIncludingNewSharedBytes']:,} байт против {b['v1Bytes']:,} в V1; уменьшение на {b['savingBytesVsV1']:,} байт</td></tr><tr><td>Модель извержения вместе с текстурой</td><td>{f['newModelWithTextureBytes']:,} против {f['sourceModelWithTextureBytes']:,} байт; +{f['modelWithTextureWeightChangePercent']:.2f}%, в пределах верхнего лимита +20%</td></tr><tr><td>Треугольники нового декоративного эффекта</td><td>452; количество справочное, лимит ±20% на сетку не применяется.</td></tr><tr><td>Общие части объектов в Blender</td><td>{native['sharedInstancesMatch']}; извержение ссылается на один новый общий меш.</td></tr></table><p>Проверены исходная геометрия дороги и индексированные атрибуты, игровые контрольные файлы, все неизменяемые меши, прежние UV и нормали. В остальных моделях лавы изменено только имя общей текстуры. В Blender подтверждены связанные меши, настройки материалов и прежние геометрия и размещения; исключения — удалённый визуальный столб и положение его дымового шлейфа. Общая библиотека проверена вместе с материалами карт 6–10 и светящимися окнами домов.</p><p>{runtime}</p><p class="note">Соответствие референсу ещё не достигнуто: светлая крупная форма в центре, замковые стены и состав дыма требуют доработки. Основная игровая карта, финальный .blend и превью остаются V1. Новый билд приложения не создавался.</p><p><a href="../../volcano-remake-rework/fidelity-v13/native/Volcano%20Remake.blend">Blender V13</a> · <a href="evidence/fidelity-v13/preservation-verification.json">Сохранение геометрии и вес</a> · <a href="evidence/fidelity-v13/fountain-changes.json">Извержение и источник</a> · <a href="evidence/fidelity-v13/final-blend-verification.json">Проверка Blender</a> · <a href="evidence/fidelity-v13/pool-audit.json">Общая библиотека</a> · <a href="screenshots/{name}">Общий статический вид в движке</a></p>{''.join(figures)}</section>'''
s=re.sub(r'<section id="fidelity-v13-draft">.*?</section>','',page.read_text(),flags=re.S).replace('<section id="fidelity-v12-draft">',section+'<section id="fidelity-v12-draft">',1).replace('Последняя доработка — V12','Предыдущая доработка — V12');page.write_text(s);pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
# Keep earlier candidate archives as historical evidence; update the authoritative report and current stage.
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v13/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v13'/Path(__file__).name);progress=r.parent/'shared-placement-1-10/progress.json';d=json.loads(progress.read_text());d['maps']['10'].update({'status':'V13 curved lava fountain with shared original texture and linked smoke. Stone retained; original road and collision preserved; native and canonical bindings verified. Overall reference fidelity unfinished; production and preview unchanged.','candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':finished,'candidateProductionIntegrated':False,'candidateSharedFountainLibrary':'fluxara_driftlib_volcano_fountain_v13','candidateFountainModelWithTextureChangePercent':f['modelWithTextureWeightChangePercent'],'fullyAccepted':False});d['goalComplete']=False;progress.write_text(json.dumps(d,ensure_ascii=False,indent=2));print('V13_REPORT_UPDATED',finished,flush=True)
