from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v32';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v32';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text())
assert run['naturalFinishObserved']and native['newSeamPrototypesTrianglePositionsMatchRuntime']==432
for f in w.glob('*.json'):
 if not f.name.startswith(('pool-before','ski-dash-ledger-before')):shutil.copy2(f,e/f.name)
reject=out/'evidence/fidelity-v31-rejected';reject.mkdir(exist_ok=True)
for name in ['visual-rejection.json','preservation-verification.json','runtime-validation.json']:shutil.copy2(r/'fidelity-v31'/name,reject/name)
figures=[]
for second,caption in [(40,'На крупных скалах справа сохранена каменная фактура. Стык 24 изменённых групп проверен отдельно; по верху некоторых форм всё ещё видны зелёные дуги, поэтому этот кадр не считается подтверждением готовности всего визуала.'),(140,'Проезд под каменной аркой. Текстура камня, исходное полотно и игровые точки сохранены. Этот ракурс также показывает оставшуюся разницу с референсом.')]:
 name=f'fidelity-v32-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name);figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V32"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
for name,src in [('fidelity-v32-overview.png',w/'screenshots/smoke-diagnostic-all.png'),('fidelity-v32-natural-finish.png',w/'screenshots/natural-finish.png'),('fidelity-v32-ramp-80.png',w/'screenshots/drive-80s.png'),('fidelity-v31-rejected-gap.png',r/'fidelity-v31/screenshots/drive-40s.png')]:shutil.copy2(src,out/'screenshots'/name)
section=f'''<section id="fidelity-v32-draft"><h2>Последняя доработка — V32: стык зелёной вершины и камня</h2>
<p>Каменная текстура сохранена по замечанию пользователя: 39&nbsp;938 байт, SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. На 24 крупных группах V30 зелёные вершины стали толще: 3.073 м вместо 0.768 м. Деревья подняты на действительные треугольники поверхности.</p>
<p>Одного увеличения масштаба оказалось недостаточно: V31 показал <a href="screenshots/fidelity-v31-rejected-gap.png">зазор и висящие зелёные дуги</a>. Этот вариант отклонён по визуалу, в основную карту и в принятый пул не перенесён. V32 использует две отдельные копии общих моделей: верхняя граница камня и открытая граница травы согласованы по контуру и высоте. В мировых координатах есть 0.08 м перекрытия, устраняющего щель. Исходные общие модели сохранены.</p>
<p>У копий изменены только вершины стыка и связанные нормали. Локальные габариты, центр, оси, UV, цвета, индексы и число треугольников сохранены. Текстура камня и материал травы переиспользованы без изменений. Общий вес двух моделей с используемой текстурой — 46&nbsp;337 байт до и после; верхний предел +20% соблюдён. Для 24 каменных частей сохранены прежние матрицы, для 24 шапок и 24 деревьев намеренно изменены масштаб или высота экземпляра.</p>
<p>Все исходные файлы карты кроме описания размещений совпали с V30. В scene.xml изменены только ранее добавленные декоративные группы; исходные дорога, коллизии, эффекты, игровые точки и линии сохранены. Независимо проверены {b['independentlyCheckedNewRenderedTriangles']:,} треугольников 72 частей относительно 2&nbsp;032 защищённых треугольников дороги; минимальное расстояние — {b['independentAllNewPartRoadMarginMeters']:.3f} м. Контакт всех 24 деревьев с поверхностью проверен отдельно.</p>
<p>В Blender 48 экземпляров используют две новые общие сетки; остальные 651 прежний меш точно совпали с V30 по геометрии, UV, нормалям, цветам и материалам. Остальные 651 матрица также совпали; наборы этих объектов различаются. Два новых прототипа сопоставлены с 432 игровыми треугольниками. Ведомость содержит 40 зарегистрированных прототипов, 94 определения материалов и 412 общих размещённых частей. Каноническая библиотека дополнена двумя копиями, прежние материалы и изображения сохранены. В общем индексе {audit['uniquePoolIds']} уникальных ID; в ведомости карты {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов. Реальные файлы, хеши и зависимости проверены.</p>
<p>Общий вес рабочего варианта с новыми и принятыми ранее общими игровыми ресурсами — {b['candidateIncludingNewSharedBytes']:,} байт, меньше интегрированного V1 ({b['v1Bytes']:,}) на {b['savingBytesVsV1']:,} байт ({b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%). Две общие библиотеки добавили {b['newGameAssetPayloadBytes']:,} байт; модели не дублируются для каждого размещения. Размер свежей сборки приложения не измерялся.</p>
<p>Полный круг Time Trial завершился естественным <a href="screenshots/fidelity-v32-natural-finish.png">результатом #1</a>. Просмотрены кадры 40, <a href="screenshots/fidelity-v32-ramp-80.png">80</a>, 140 и 190 секунд и <a href="screenshots/fidelity-v32-overview.png">обзор из игрового движка</a>, без ретуши. Временные карты и скопированные ресурсы убраны из установленного приложения; донорские деревья, холмы и факелы не менялись. Опасное прохождение исходной рампы наблюдалось ранее и в V1; причина не исправлена, все возможные регрессии не исключены.</p>
<p class="note">Это локальная доработка, не готовность всей карты. Крупная исходная масса, замок, крыши и атмосфера ещё отличаются от референса. Основная карта, итоговый пользовательский .blend и превью пока V1. Новая сборка, производительность, обратный режим и вся кампания не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v32/native/Volcano%20Remake.blend">Blender V32</a> · <a href="evidence/fidelity-v32/preservation-verification.json">Дорога и вес</a> · <a href="evidence/fidelity-v32/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v32/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v32/pool-audit.json">Пул</a> · <a href="evidence/fidelity-v31-rejected/visual-rejection.json">Отклонённый V31</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v32-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V30','Предыдущая доработка — V30');s=s.replace('<section id="fidelity-v30-draft">',section+'<section id="fidelity-v30-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v32/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v32'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V32 matching copied grass/stone boundaries on24 added groups; stone pixels and original course/physics/controls intact. Thickness-only V31 rejected. Independent road/tree/native/canonical/pool and full natural lap#1 verified. Main mass/castle/roof/sky fidelity unfinished; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V32','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':40,'candidatePrototypeIdsReferencedByNativeSharedParts':24,'candidateNativeSharedParts':412,'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V32';data.pop('inProgressCandidate',None);data['status']='V32 matched grass/stone seams, stone pixels/source bounds/UV/RGB/topology retained. Source/native/canonical/pool and natural full lap#1 verified. V31 thickness-only rejected. Main mass/castle/red roofs/sky/plume fidelity and final integration remain unfinished.';data['workingEvidence']['V31']='Visual rejection: thickness-only exposes gap at grass/stone boundaries. Natural full lap#1 and source-preservation check are not visual acceptance.';data['workingEvidence']['V32']='Two copied shared components, matching boundaries/0.08m world overlap, same46,337B model+texture total,24 groups by coordinates. Independent road/tree/native/canonical/pool/full natural lap checks; stone pixels retained.';data['nextVisibleTarget']='Work on large visible source mass and castle/red roofs/sky-plume composition. Preserve course/collision/gameplay nodes and current liked stone pixels. Readonly study shows existing V26 collider is only64 central triangles; any later large-wall render removal requires its own exact physics proxy first.';plan.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('V32_REPORT_SAVED',len(m['files']),flush=True)
