from pathlib import Path
import json,hashlib,shutil,re
from urllib.parse import unquote,urlsplit
r=Path(__file__).resolve().parent;w=r/'fidelity-v8b';out=r.parent/'fluxara-user-volcano-remake-final/report';page=out/'index.html';evidence=out/'evidence/fidelity-v8b';evidence.mkdir(parents=True,exist_ok=True);history=w/'report-history';history.mkdir(exist_ok=True);shutil.copy2(page,history/(hashlib.sha256(page.read_bytes()).hexdigest()[:12]+'-index.html'))
for name in ['castle-changes.json','skin-changes.json','preservation.json','budget.json','runtime-validation.json','drive-capture.json','smoke-diagnostic-all.json','final-blend-verification.json','canonical-bindings-verification.json','pool-audit.json']:shutil.copy2(w/name,evidence/name)
for name in ['drive-12s.png','drive-40s.png','drive-80s.png','drive-150s.png','smoke-diagnostic-all.png']:shutil.copy2(w/'screenshots'/name,out/'screenshots'/('fidelity-v8b-'+name))
b=json.loads((w/'budget.json').read_text());skin=json.loads((w/'skin-changes.json').read_text());assert json.loads((w/'runtime-validation.json').read_text())['candidateOneLapTimeTrial']['naturalFinishObserved'];assert json.loads((w/'pool-audit.json').read_text())['newObjects']==2
section=f'''<section id="fidelity-v8b-draft"><h2>Последняя доработка — V8B, две общие башни</h2>
<p>Два декоративных башенных блока заменены координатными размещениями варианта модели из пула Lap Catch. Стены и обод башен переведены на серую ячейку существующего атласа, тонкий шест — на красную. Пиксели исходной палитры не изменены. Применён отдельный вариант модели и материала; исходная общая башня и другие карты сохранены.</p>
<p><strong>Красная коническая крыша ещё не реализована.</strong> Двадцать граней коричневой детали источника сначала были ошибочно приняты за крышу; проверка геометрии и обзор в игре показали, что это тонкий шест. Старый деревянный конус верхней башни скрыт из видимой геометрии. Его исходные треугольники и треугольники двух старых башен сохранены в двух точных невидимых столкновительных мешах interaction=physicsonly. Геометрия столкновений основной модели вместе с ними совпадает с исходной V7B.</p>
<table><tr><th>Показатель</th><th>Результат V8B</th></tr>
<tr><td>Модель башни вместе с текстурой</td><td>{skin['modelWithTextureBeforeBytes']:,} → {skin['modelWithTextureAfterBytes']:,} байт; +{skin['weightChangePercent']:.3f}%, меньше разрешённого роста +20%</td></tr>
<tr><td>Геометрия общей башни</td><td>429 треугольников; вершины, индексы, нормали, локальные границы, начало координат и оси совпадают с донором. Изменены только UV и имя текстуры.</td></tr>
<tr><td>Папка карты</td><td>{b['candidateTrackBytes']:,} байт</td></tr>
<tr><td>Все новые общие игровые файлы</td><td>{b['newSharedRuntimeBytes']:,} байт: SPM, палитра под отдельным именем, node.xml и materials.xml. Отдельная копия палитры учтена, хотя её содержимое совпадает с донором.</td></tr>
<tr><td>Карта плюс новые общие ресурсы</td><td>{b['newBytesIncludingNewSharedRuntime']:,} байт; на {b['savedBytesAgainstPrevious']:,} байт меньше основной V1 ({b['previousTrackBytes']:,} байт)</td></tr>
<tr><td>Треугольники карты</td><td>{b['candidateTriangles']:,}; +{b['triangleChangePercentAgainstOriginal']:.2f}% к оригиналу. Справочно, без ограничения ±20% на полигоны; включает сохранённые столкновительные меши.</td></tr>
<tr><td>Редактируемый проект и пул</td><td>19 прототипов, 87 частей общих размещений. Добавлены 1 прототип и 1 материал в каноническую библиотеку, физический SPM и отдельный файл палитры сохранены в пакете.</td></tr></table>
<p>Позиции, нормали, UV, цвета и индексы полотна совпадают с оригиналом. Track.xml, quads.xml, graph.xml, scripting.as и easter_eggs.xml совпадают побайтно. Остальные буферы и старые игровые размещения совпадают с V7B. Модель плюс два невидимых меша содержит точно те же ориентированные треугольники столкновений, что и V7B; свойства использованных старых материалов для физики были стандартными.</p>
<p>Blender-проект повторно открыт. Проверены геометрия и UV изменённых буферов, двух столкновительных мешей и прототипа; UV преобразованы в Blender как u, 1−v. Совпадают все 87 матриц общих частей, исходные XML встроены, отсутствующих текстур нет. Нормали в новых авторских Blender-мешах пересчитываются Blender; неизменность упакованных нормалей проверена в игровом SPM. Пиксели палитры совпадают с донором. Канонические привязки карт 6–10, предыдущих кандидатов и четыре материала светящихся окон проверены.</p>
<p>Временная копия кандидата в iOS Simulator завершила один круг Time Trial с одной машиной, результат #1, без принудительной победы. Сохранены <a href="screenshots/fidelity-v8b-drive-150s.png">финиш</a>, <a href="screenshots/fidelity-v8b-drive-12s.png">начало</a> и <a href="screenshots/fidelity-v8b-drive-40s.png">поворот у лавы</a>. Временные карта и новая библиотека после заезда удалены из установленного приложения. Нового билда не было.</p>
<p class="note"><strong>Карта 10 ещё не завершена и не перенесена в основную игровую версию.</strong> Серые башни — промежуточный вариант. Конические красные крыши, форма замковых стен, скал, лавовых потоков и плотного дыма ещё не соответствуют референсу. Игровые кадры ниже подтверждают текущий проезд, а отдельный статический обзор показывает размещения башен. Основная карта, финальный .blend и превью сохраняют V1. Полное событие кампании, обратное направление и производительность не подтверждены.</p>
<p><a href="../../volcano-remake-rework/fidelity-v8b/native/Volcano%20Remake.blend">Редактируемый кандидат V8B</a> · <a href="evidence/fidelity-v8b/skin-changes.json">Вес башни с текстурой</a> · <a href="evidence/fidelity-v8b/budget.json">Вес карты</a> · <a href="evidence/fidelity-v8b/preservation.json">Сохранность</a> · <a href="evidence/fidelity-v8b/runtime-validation.json">Заезд</a> · <a href="evidence/fidelity-v8b/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v8b/pool-audit.json">Пул</a></p>
<figure><a href="screenshots/fidelity-v8b-drive-12s.png"><img src="screenshots/fidelity-v8b-drive-12s.png" alt="V8B: игровой кадр начала маршрута"></a><figcaption><strong>V8B — начало маршрута</strong><span>Настоящий игровой кадр тестового заезда в симуляторе.</span></figcaption></figure>
<figure><a href="screenshots/fidelity-v8b-drive-80s.png"><img src="screenshots/fidelity-v8b-drive-80s.png" alt="V8B: игровой кадр верхнего участка"></a><figcaption><strong>V8B — верхний участок</strong><span>Настоящий игровой кадр; формы скал и лавы ещё требуют доработки.</span></figcaption></figure>
<figure><a href="screenshots/fidelity-v8b-smoke-diagnostic-all.png"><img src="screenshots/fidelity-v8b-smoke-diagnostic-all.png" alt="V8B: статический обзор башен"></a><figcaption><strong>V8B — отдельный статический обзор</strong><span>Камера осмотра в движке, не игровой заезд. Видны две серые башни и незавершённая форма крыши. Игровые проверки и физические столкновения в диагностической копии отключены.</span></figcaption></figure>
</section>'''
s=re.sub(r'<section id="fidelity-v8b-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v7b-draft">',section+'<section id="fidelity-v7b-draft">',1);s=s.replace('Последний эксперимент — V7B','Предыдущий эксперимент — V7B');page.write_text(s)
missing=[link for link in re.findall(r'(?:src|href)="([^"]+)"',s)if not urlsplit(link).scheme and not link.startswith('#')and not(out/unquote(link.split('#')[0])).exists()];assert not missing,missing
(out/'manifest.json').write_text(json.dumps({'brokenLocalLinks':missing,'files':[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}for p in out.rglob('*')if p.is_file()and p.name!='manifest.json']},indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK');prefixes=['volcano-remake-reference-v1']+[p.name for p in(pack/'sources').glob('volcano-remake-fidelity-*')if p.is_dir()]
for prefix in prefixes:shutil.copytree(out,pack/'sources'/prefix/'report',dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v8b'/Path(__file__).name)
p=r.parent/'shared-placement-1-10/progress.json';progress=json.loads(p.read_text());progress['maps']['10'].update({'status':'V8B isolated pooled gray tower variant: two coordinate placements, old collision exact; model plus texture weight +0.125 percent, map weight decreased including new shared files. One natural TT lap, native/canonical/assets verified. Red cone roofs, castle walls, cliffs, lava and smoke unfinished. Production and preview unchanged.','candidate':str(w),'candidateTrackBytes':b['candidateTrackBytes'],'candidateBytesIncludingNewSharedRuntime':b['newBytesIncludingNewSharedRuntime'],'candidateSavedBytesAgainstPrevious':b['savedBytesAgainstPrevious'],'candidateTriangleChangePercent':b['triangleChangePercentAgainstOriginal'],'candidateOneLapNaturalFinish':True,'candidateProductionIntegrated':False,'fullyAccepted':False});progress['userWeightRequirement']={'modelPlusTexturesMaximumIncreasePercent':20,'polygonLimit':None,'mapBytesMustDecreaseIncludingNewSharedResources':True};p.write_text(json.dumps(progress,ensure_ascii=False,indent=2));print('V8B_REPORT_UPDATED',page)
