from pathlib import Path
import datetime,hashlib,json,shutil,subprocess
r=Path(__file__).resolve().parent;root=r.parents[2];repo=Path('/Users/motoricallc/Downloads/fluxara-drift');res=repo/'iosApp/FluxaraResources';report=root/'output/fluxara-summit-run-final/report';evidence=report/'evidence/model-texture-weight';evidence.mkdir(exist_ok=True);m=json.loads((root/'output/shared-placement-1-10/model-texture-weight/map-9.json').read_text());groups=json.loads((root/'output/shared-placement-1-10/model-texture-weight/library-groups.json').read_text());fir=next(q for q in groups if q['map']==9);fix=json.loads((r/'integration.json').read_text());track=res/'tracks/fluxara-summit-run';own=sum(p.stat().st_size for p in track.iterdir()if p.is_file());previous=json.loads((r.parent/'preservation-audit.json').read_text());app=Path(subprocess.check_output(['xcrun','simctl','get_app_container','3B2F19DC-4F76-4F61-9F8D-D5E914A6D123','io.fluxara.drift','app'],text=True).strip());gui=app/'data/gui/fluxara/campaign-previews/fluxara-summit-run.jpg';total=own+previous['newSharedBytes']+gui.stat().st_size;budget={'originalTrackBytes':previous['originalBytes'],'currentTrackBytes':own,'existingAttributedNewSharedBytes':previous['newSharedBytes'],'campaignThumbnailBytesChargedInFull':gui.stat().st_size,'currentTotalIncludingSharedAndThumbnailBytes':total,'savingAgainstOriginalBytes':previous['originalBytes']-total,'woodTextureSavingBytes':fix['savingBytes'],'mapLocalModels':m,'snowFirReplacement':fir,'newRuntimeTestsPerformed':False,'newBuildPerformed':False};(r/'weight.json').write_text(json.dumps(budget,ensure_ascii=False,indent=2)+'\n')
for p in [r/'integration.json',r/'weight.json',root/'output/shared-placement-1-10/model-texture-weight/map-9.json',root/'output/shared-placement-1-10/model-texture-weight/library-groups.json']:shutil.copy2(p,evidence/p.name)
p=report/'index.html';s=p.read_text();backup=r/'before/report-before-weight-update.html'
if not backup.exists():backup.write_text(s)
fmt=lambda n:f'{n:,}'.replace(',',' ');rows=''.join(f'<tr><td>{q["model"]}</td><td>{fmt(q["before"]["modelPlusUsedTextureBytes"])}</td><td>{fmt(q["current"]["modelPlusUsedTextureBytes"])}</td><td>{q["changePercent"]:+.2f}%</td></tr>'for q in m['models']);section=f'''<section id="model-texture-weight-current"><h2>Вес моделей с текстурами — 02.10.2026</h2><p>Игровая копия зимней древесины уменьшена с 512×512 до 256×256. Её вес: 501 708 → 116 272 байт. Изображение высокого разрешения сохранено в исходном пуле и архиве. Геометрия, размеры, центры, направления и размещения моделей не менялись. Итоговый Blender, ресурсы проекта, установленного симулятора и экспортная копия текстуры в библиотеке обновлены.</p><table><tr><th>Модель</th><th>До: модель + используемые текстуры, байты</th><th>Сейчас, байты</th><th>Изменение</th></tr>{rows}<tr><td>Семейство исходной ели → общая снежная ель</td><td>{fmt(fir['original']['totalModelAndTextureBytes'])}</td><td>{fmt(fir['current']['totalModelAndTextureBytes'])}</td><td>{fir['changePercent']:+.2f}%</td></tr></table><p>Каждый используемый файл текстуры учтён один раз для соответствующей модели; число размещений не умножает её файловый вес. Сопоставленные исходные модели и семейство новой снежной ели укладываются в максимум +20%.</p><p>Карта с ранее добавленными общими ресурсами и целиком миниатюрой кампании: {fmt(total)} байт против {fmt(previous['originalBytes'])} исходных. Уменьшение: {fmt(previous['originalBytes']-total)} байт. Отдельная экономия этого исправления — {fmt(fix['savingBytes'])} байт.</p><p>Новые заезды, проверки проезда и сборка приложения не выполнялись. Игровые кадры ниже относятся к предыдущему разрешению древесины; состав сцены сохранён.</p><p><a href="evidence/model-texture-weight/weight.json">Файловый расчёт веса</a> · <a href="evidence/model-texture-weight/integration.json">Сохранение экспортной текстуры и Blender</a></p></section>'''
s=s.replace('<main>','<main>'+section,1);p.write_text(s)
mp=report/'manifest.json'
if mp.exists():
 j=json.loads(mp.read_text());j['files']=[{'path':str(p.relative_to(report)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}for p in report.rglob('*')if p.is_file()and p.name!='manifest.json'];j['updatedForTextureWeightFix']=fix['timestamp'];mp.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
ledgerPath=root/'fluxara-summit-run.asset-ledger.json';j=json.loads(ledgerPath.read_text());j['modelTextureWeightCurrent']=budget;j['report']=str(p);ledgerPath.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');progressPath=root/'output/shared-placement-1-10/progress.json';j=json.loads(progressPath.read_text());j['maps']['9'].update({'status':'Winter map and 73 shared placements preserved; runtime timber export reduced to 256x256 to meet per-model texture-weight budget; final Blender and report updated.','sourceAndInstalledIntegrated':True,'modelTextureWeightMeasured':True,'matchingModelTextureBudgetPassed':True,'newRuntimeTestsPerformed':False,'trackPlusNewSharedAndCampaignPreviewBytes':total,'savingBytes':previous['originalBytes']-total,'report':str(report/'index.html')});j['stage']='Map 9 actual per-model texture-byte excess fixed. Three map 7 replacement groups need lightweight texture exports.';j['goalComplete']=False;progressPath.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');archive=repo/'FLUXARA_TRACK_ASSET_PACK/sources/summit-model-texture-weight-v1';archive.mkdir(exist_ok=True)
for p in r.glob('*.py'):shutil.copy2(p,archive/p.name)
for p in r.glob('*.json'):shutil.copy2(p,archive/p.name)
shutil.copy2(ledgerPath,archive/ledgerPath.name);shutil.copytree(evidence,archive/'evidence',dirs_exist_ok=True);shutil.copy2(report/'index.html',archive/'report.html');print('SUMMIT_MODEL_TEXTURE_WEIGHT_REPORT_SAVED',total,previous['originalBytes']-total)
