const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('/Users/motoricallc/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
(async()=>{
  const r=__dirname,input=path.join(r,'screenshots/preview-castle-wide.png');
  const raw=fs.readFileSync(input),meta=await sharp(raw).metadata();
  const cropWidth=Math.floor(meta.height*16/9);
  const output=await sharp(raw).extract({left:Math.floor((meta.width-cropWidth)/2),top:0,width:cropWidth,height:meta.height}).resize({width:1024,withoutEnlargement:true}).jpeg({quality:90}).toBuffer();
  const repo='/Users/motoricallc/Downloads/fluxara-drift';
  const targets=[path.join(r,'candidate/screenshot.jpg'),path.join(path.dirname(r),'fluxara-user-volcano-remake-final/screenshot.jpg'),path.join(repo,'iosApp/FluxaraResources/tracks/fluxara-user-volcano-remake/screenshot.jpg'),path.join(repo,'FLUXARA_TRACK_ASSET_PACK/textures/volcano-remake-reference-v1/screenshot.jpg')];
  for(const p of targets)fs.writeFileSync(p,output);
  fs.writeFileSync(path.join(r,'preview-update.json'),JSON.stringify({input,rawInputSha256:crypto.createHash('sha256').update(raw).digest('hex'),inputDimensions:[meta.width,meta.height],outputDimensions:[1024,576],kind:'Actual game-engine inspection camera, no HUD; technical centered 16:9 crop and resize only',sourcePreview:targets[2],bytes:output.length,sha256:crypto.createHash('sha256').update(output).digest('hex'),campaignPreview:'Generated by PrepareFluxaraCampaignPreviews.sh from the source track screenshot'},null,2));
})();
