from pathlib import Path
import json,hashlib,shutil,xml.etree.ElementTree as E
r=Path(__file__).resolve().parent;w=r/'fidelity-v5-alpha';repo=Path('/Users/motoricallc/Downloads/fluxara-drift');pack=repo/'FLUXARA_TRACK_ASSET_PACK';sources=pack/'sources/volcano-remake-fidelity-v5-alpha';mod=pack/'models/volcano-remake-fidelity-v5-alpha';pf=repo/'FLUXARA_TRACK_ASSET_POOL.json';canon=pack/'blender/FLUXARA_Track_Asset_Library.blend'
a=json.loads((w/'asset-registration.json').read_text());pool=json.loads(pf.read_text());ledger=json.loads((r/'fidelity-v4e/candidate-asset-ledger.json').read_text());assert len(a['objects'])==18;assert json.loads((w/'canonical-registration.json').read_text())['newObjects']==8;assert len(json.loads((w/'final-blend-verification.json').read_text())['threeSmokeEffectsAboveRoad'])==3;assert (w/'canonical-bindings-verification.json').is_file()
if not(w/'pool-before-v5-alpha.json').exists():shutil.copy2(pf,w/'pool-before-v5-alpha.json')
def info(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for name in ['fidelity_v5_alpha.py','tint_v5_alpha.py','layout_v5_alpha.py','verify_fidelity_v5_alpha.py','finalize_fidelity_v5_alpha.py','verify_fidelity_v5_alpha_native.py','register_fidelity_v5_alpha_canonical.py','verify_fidelity_v5_alpha_canonical.py','capture_fidelity_v5_alpha_drive.py','capture_fidelity_v5_alpha_inspection.py',Path(__file__).name]:shutil.copy2(r/name,sources/name)
for p in w.glob('*.json'):
 if not p.name.startswith('pool-before'):shutil.copy2(p,sources/p.name)
shutil.copytree(w/'screenshots',sources/'screenshots',dirs_exist_ok=True);shutil.copytree(w/'iterations',sources/'iterations',dirs_exist_ok=True);shutil.copy2(w/'candidate/materials.xml',sources/'materials.xml');shutil.copy2(w/'candidate/scene.xml',sources/'scene.xml')
usage=[{'trackId':'fluxara-user-volcano-remake','status':'V5 Alpha candidate; production and preview unchanged'}];base={'sourceMap':'fluxara-user-volcano-remake','categories':['lava'],'uses':usage};new_objects=[];new_materials=[];names={q['model']for q in json.loads((w/'tint-changes.json').read_text())};objects=[q for q in ledger['objects']if not('-effect-'in q['id']or q.get('displayName')in names)];tex=next(q for q in ledger['textures']if q['displayName']=='vr_volcanic_smoke.png')
old_mat=next(q for q in ledger['materials']if q.get('kind')=='material'and 'vr_volcanic_smoke.png'in q.get('textures',[]));materials=[q for q in ledger['materials']if q['id']!=old_mat['id']and not(q.get('kind')=='runtime-material-definition'and 'vr_volcanic_smoke.png'in q.get('sourceXml',''))]
row=next(q for q in a['materials']if q['name']=='VRV5A_Smoke');q={**base,**row,'displayName':row['name'],'kind':'material','reuseTier':'adapt','canonicalPackPath':str(canon)+'#Material/'+row['name'],'physicalSourcePath':a['visualLibrary'],'dependencies':[tex['id']],'reason':'Same pooled RGBA sprite; vertex colour multiplies RGB and alpha is linked in native material. Runtime uses alpha blend.'};materials.append(q);new_materials.append(q);material_id=q['id']
for row in a['newPrototypes']:
 q={**base,**row,'displayName':row['name'],'kind':'visual-object','reuseTier':'adapt','canonicalPackPath':str(canon)+'#Object/'+row['name'],'physicalSourcePath':a['visualLibrary'],'file':info(Path(a['visualLibrary'])),'dependencies':[material_id],'reason':'Original core smoke mesh restored, or V4E smoke cards reused; coordinates, normals, UV and indices retained for the corresponding source. Vertex tint added.'};new_objects.append(q);objects.append(q)
for row in json.loads((w/'tint-changes.json').read_text()):
 p=mod/row['model'];is_core=row['model']in['AshCloud.spm','AshColumn.spm','PyroclasticFlow.spm'];original=(pack/'sources/volcano-remake-reference-v1/original-runtime'/row['model'])if is_core else(pack/'models/volcano-remake-fidelity-v4e'/row['model']);assert original.is_file()
 q={**base,'id':'volcano-fidelity-v5a-model-'+hashlib.sha256(row['model'].encode()).hexdigest()[:12],'displayName':row['model'],'kind':'adapted-transparent-smoke','reuseTier':'adapt','canonicalPackPath':str(p),'physicalSourcePath':str(original),'file':info(p),'dependencies':[material_id],'adaptationScript':str(sources/'tint_v5_alpha.py'),'reason':'Original core geometry and UV restored'if is_core else'V4E full-sprite card geometry retained','adaptationProof':row};new_objects.append(q);objects.append(q)
xml=E.tostring(next(m for m in E.parse(w/'candidate/materials.xml').getroot()if m.get('name')=='vr_volcanic_smoke.png'),encoding='unicode');q={**base,'id':'volcano-fidelity-v5a-runtime-material-smoke','displayName':'Runtime vr_volcanic_smoke.png alpha blend','kind':'runtime-material-definition','reuseTier':'adapt','canonicalPackPath':str(sources/'materials.xml'),'physicalSourcePath':str(sources/'materials.xml'),'dependencies':[tex['id']],'sourceXml':xml,'reason':'Alpha blending; no image copy or change to physical parameters.'};materials.append(q);new_materials.append(q)
pool['objects']=[q for q in pool['objects']if not q['id'].startswith('volcano-fidelity-v5a-')]+new_objects;pool['materials']=[q for q in pool['materials']if not q['id'].startswith('volcano-fidelity-v5a-')]+new_materials;ci=info(canon)
def refresh(v):
 if isinstance(v,dict):
  if v.get('path')==str(canon)and'sha256'in v:v.update(ci)
  for x in v.values():refresh(x)
 elif isinstance(v,list):
  for x in v:refresh(x)
refresh(pool);pool['physicalPack']['blenderLibrary']=ci;ids=[q['id']for k in['objects','materials','textures']for q in pool[k]];assert len(ids)==len(set(ids))
ledger.update({'candidate':'V5 Alpha overhead layout','status':'Isolated candidate; smoke no longer opaque, decorative placement changed; castle/cliffs/lava still unfinished','objects':objects,'materials':materials,'finalBlend':a['finalBlend'],'preservation':json.loads((w/'preservation.json').read_text()),'budget':json.loads((w/'budget.json').read_text()),'runtimeValidation':json.loads((w/'runtime-validation.json').read_text()),'deltaAssetCounts':{'objects':16,'materials':2,'textures':0},'approval':'No final visual approval recorded','productionIntegrated':False});ledger['assets']=objects+materials+ledger['textures'];ledger['reusedAssetIds']=[q['id']for q in ledger['assets']if not q['id'].startswith('volcano-fidelity-v5a-')]
for q in ledger['assets']:
 assert Path(q['canonicalPackPath'].split('#')[0]).is_file(),q['id'];assert Path(q['physicalSourcePath'].split('#')[0]).exists(),q['id'];assert all(d in ids for d in q.get('dependencies',[])),q['id']
 if q.get('file'):assert info(Path(q['file']['path']))==q['file'],q['id']
pf.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n');(w/'candidate-asset-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n');audit={'newObjects':16,'newMaterials':2,'newTextures':0,'usedAssets':len(ledger['assets']),'uniquePoolIds':len(ids),'allPhysicalPathsExist':True,'unresolvedDependencies':[],'canonical':ci};(w/'pool-audit.json').write_text(json.dumps(audit,indent=2))
for name in['candidate-asset-ledger.json','pool-audit.json']:shutil.copy2(w/name,sources/name)
print('V5_ALPHA_POOL_REGISTERED',audit)
