from pathlib import Path
import json,shutil,re,hashlib
r=Path(__file__).resolve().parent;w=r/'fidelity-v10b';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v10b';e.mkdir(exist_ok=True);page=out/'index.html';b=json.loads((w/'budget.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());proof=json.loads((w/'final-blend-verification.json').read_text());assert len(proof['newCliffPrototypes'])==4
for name in ['stone-restoration.json','preservation.json','budget.json','runtime-validation.json','drive-capture.json','smoke-diagnostic-all.json','final-blend-verification.json','canonical-bindings-verification.json','pool-audit.json']:
 shutil.copy2(w/name,e/name)
shutil.copy2(r/'native-normal-repair.json',e/'native-normal-repair.json');shutil.copy2(r/'repaired-canonical.json',e/'repaired-canonical.json')
figures=[]
for second in [40,80]:
 source=w/f'screenshots/drive-{second}s.png';name=f'fidelity-v10b-game-{second}s.png';shutil.copy2(source,out/'screenshots'/name);figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V10B, {second} секунд после запуска"></a><figcaption>Реальный заезд в iOS Simulator; {second} секунд после запуска. Текстура камня восстановлена.</figcaption></figure>')
finish=run['candidateOneLapTimeTrial'];finish_text='Один круг Time Trial завершился естественно, на экране результата читается #1.' if finish['naturalFinishObserved'] else 'Естественное завершение круга пока не подтверждено; текущий заезд сохранён в доказательствах без заявления о полном прохождении.'
angle=max(q['maximumCustomNormalAngularErrorDegrees']for q in proof['newCliffPrototypes'])
section=f'''<section id="fidelity-v10b-draft"><h2>Последняя доработка — V10B: возвращена текстура камня</h2><p>По замечанию «С текстурой камня было лучше» восстановлены исходные каменные текстуры, их UV и материалы во всех четырёх затронутых моделях. Плоский вариант V10 отклонён и оставлен только в истории. Сглаженные декоративные нормали и красные конические крыши двух общих башен сохранены.</p><table><tr><th>Показатель</th><th>Результат</th></tr><tr><td>Вес каждой восстановленной модели с текстурами</td><td>Совпадает с V9: изменение 0%. Верхний предел +20% соблюдён.</td></tr><tr><td>Карта и все новые общие игровые файлы</td><td>{b['newBytesIncludingNewSharedRuntime']:,} байт; меньше V1 на {b['savedBytesAgainstPrevious']:,} байт ({b['savedBytesAgainstPrevious']/b['previousTrackBytes']*100:.2f}%)</td></tr><tr><td>Учёт общих файлов</td><td>{b['activeV9SharedRuntimeBytes']:,} байт V9 и {b['retainedPreviousV8BSharedRuntimeBytes']:,} байт сохранённой V8B; обе библиотеки учтены.</td></tr><tr><td>Треугольники</td><td>{b['candidateTriangles']:,}; справочный показатель, ограничение относится к весу.</td></tr></table><p>Позиции вершин, индексы, габариты и исходные UV восстановленных моделей проверены по SPM. Дорога, игровые точки и файлы управления совпадают с исходными. В Blender исправлены две нулевые нормали через границы сглаживания, без изменения геометрии; после повторного открытия максимальное отклонение от упакованных нормалей SPM {angle:.3f}°. Четыре прототипа используют прежние материалы и текстуры из пула.</p><p>{finish_text} Полная кампания, обратный заезд и производительность этим тестом не проверены.</p><p class="note">Карта ещё дорабатывается к референсу: дым, силуэты скал, замковые стены и лава требуют улучшения. Кандидат проверяется отдельно; основная карта, финальный .blend и превью пока остаются V1. Новый билд приложения не создавался.</p><p><a href="../../volcano-remake-rework/fidelity-v10b/native/Volcano%20Remake.blend">Blender V10B</a> · <a href="evidence/fidelity-v10b/stone-restoration.json">Восстановление текстуры</a> · <a href="evidence/fidelity-v10b/budget.json">Вес</a> · <a href="evidence/fidelity-v10b/runtime-validation.json">Заезд</a> · <a href="evidence/fidelity-v10b/final-blend-verification.json">Проверка Blender</a> · <a href="evidence/fidelity-v10b/pool-audit.json">Пул</a></p>{''.join(figures)}</section>'''
s=re.sub(r'<section id="fidelity-v10b-draft">.*?</section>','',page.read_text(),flags=re.S).replace('<section id="fidelity-v9-draft">',section+'<section id="fidelity-v9-draft">',1);page.write_text(s)
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for p in [pack/'sources/volcano-remake-reference-v1/report']+list((pack/'sources').glob('volcano-remake-fidelity-*/report'))+[pack/'sources/volcano-remake-fidelity-v10b/report']:shutil.copytree(out,p,dirs_exist_ok=True)
for name in [Path(__file__).name,'repair_cliff_native_normals.py','update_repaired_cliff_canonical.py']:shutil.copy2(r/name,pack/'sources/volcano-remake-fidelity-v10b'/name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V10B stone texture restored; red roofs and smooth decorative normals retained. Native, canonical and pool verified. Reference fidelity unfinished; production and preview unchanged.','candidate':str(w),'candidateTrackBytes':b['candidateTrackBytes'],'candidateBytesIncludingNewSharedRuntime':b['newBytesIncludingNewSharedRuntime'],'candidateSavedBytesAgainstPrevious':b['savedBytesAgainstPrevious'],'candidateTriangleChangePercent':b['triangleChangePercentAgainstOriginal'],'candidateOneLapNaturalFinish':finish['naturalFinishObserved'],'candidateProductionIntegrated':False,'report':str(page),'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
print('V10B_REPORT_UPDATED',flush=True)
