from pathlib import Path
import hashlib,json,re,shutil,subprocess
r=Path(__file__).resolve().parent;w=r/'fidelity-v38';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v38';e.mkdir(exist_ok=True);b=json.loads((w/'preservation-verification.json').read_text());n=json.loads((w/'final-blend-verification.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());assert run['naturalFinishObserved']and n['newCloudSharedInstances']==8
for f in w.glob('*.json'):
 if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
for name,src in [('fidelity-v38-game-40.png','drive-40s.png'),('fidelity-v38-game-80.png','drive-80s.png'),('fidelity-v38-game-140.png','drive-140s.png'),('fidelity-v38-natural-finish.png','natural-finish.png'),('fidelity-v38-overview.png','smoke-diagnostic-all.png')]:shutil.copy2(w/'screenshots'/src,out/'screenshots'/name)
rej=e/'rejected-skirt-normal-diagnostic';rej.mkdir(exist_ok=True);shutil.copy2(w/'rejected-skirt-normal-diagnostic/rejection.json',rej/'rejection.json')
section=f'''<section id="fidelity-v38-draft"><h2>Рабочий вариант V38: каменная фактура, объём травы и облака</h2>
<p>Каменная текстура сохранена: 39&nbsp;938 байт, прежние пиксели и SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Новых растровых изображений нет. Полотно и все 2&nbsp;032 дорожных треугольника, исходные физические оболочки, точки и линии, quads/graph, сценарий, track.xml и игровые предметы сохранены. Исходные файлы моделей из пула не изменялись; создано три общих варианта, которые используются по координатам.</p>
<p>К 82 травяным шапкам добавлен боковой бортик: 16 вершин и 32 треугольника на одну общую модель. Модель весит 4&nbsp;282 байта против 3&nbsp;866, рост 10.76%, используемых текстур у неё нет. Локальные габариты, начало координат и оси совпадают с источником. Все прежние позиции, UV и цвета вершин сохранены; изменены нормали кромки и добавлены нижние вершины. Верхняя высота каждого экземпляра и стык со скалой сохранены. Максимальная ошибка XZ стыка — {b['maximumWorldRimXZErrorMeters']:.9f} м, перекрытия 0.08 м — {b['maximum0p08mInterfaceOverlapErrorMeters']:.11f} м. В начальной диагностике нормали нового бортика смотрели внутрь; вариант <a href="evidence/fidelity-v38/rejected-skirt-normal-diagnostic/rejection.json">отклонён</a>, все 16 нижних нормалей исправлены до окончательного проезда.</p>
<p>Дальний зелёный рельеф стал волнистым: изменена только высота 1&nbsp;232 вершин общей модели. Её вес, число треугольников, UV, цвета, локальные габариты и оси сохранились. Все треугольники ближе 60 м к полотну заблокированы от изменения; независимая проверка дала нижнюю оценку {b['changedFarTerrainXZDistanceToRoadLowerBoundMeters']:.2f} м для изменённых треугольников. 64 дерева и 20 холмов из V37 заново посажены на реальный рельеф; корни деревьев совпали с поверхностью с ошибкой менее {b['backgroundTreeRootsOnTerrainOrMoundMaxErrorMeters']:.9f} м. Также пересчитаны высоты прежних растений на травяных шапках.</p>
<p>В небе размещено 8 общих объёмных облаков. Это вариант существующей модели дыма с бело-золотистыми цветами вершин: локальная геометрия, нормали, габариты и вес 15&nbsp;446 байт сохранены. Для 334 изменённых или добавленных размещений проверены все отрисовываемые треугольники относительно дороги: нижний предел 0.25 м для прежнего окружения, 2 м для дальних растений, 5 м для облаков. Эти числа — гарантированные нижние пределы, а не точный минимум для всей карты.</p>
<p>Вес карты со всеми новыми файлами и принятой историей общих ресурсов — <b>{b['allCandidateAndAcceptedHistoryBytes']:,} байт</b>: {b['candidateAllFilesBytes']:,} файлов карты, {b['acceptedSharedHistoryIncludingV37Bytes']:,} прежних общих ресурсов и {b['newSharedRuntimeAllFilesBytes']:,} новых общих моделей/XML. Экономия относительно V1 ({b['v1Bytes']:,}) — {b['savingVsV1Bytes']:,} байт, {b['savingVsV1Bytes']/b['v1Bytes']*100:.2f}%; относительно V37 — {b['savingVsV37Bytes']:,} байт. Неиспользуемая stktex_generic_lavaA.png (283&nbsp;993 байта) убрана только из копии экспорта после проверки SPM, XML, сценария и рекурсивных зависимостей общих библиотек; исходное изображение сохранено. Все другие файлы, включая неиспользуемые, учтены. Ограничение +20% относится к весу логического объекта с используемыми текстурами. Размер новой сборки приложения не измерен.</p>
<p>Blender сохранён и открыт повторно: {n['nativePrototypeCount']} прототипов, {n['nativeMaterialDefinitionCount']} определений материалов, {n['nativeSharedParts']} общих частей. Все прежние объекты сохранены; геометрия и остальные атрибуты {n['allOtherNativeMeshGeometryUVNormalsColorsMaterialsExactV37']} неизменённых мешей совпали с V37. Три новых прототипа зарегистрированы в канонической библиотеке; прежние модели, изображения и свечение окон домов проверены без изменений. Пул содержит {audit['uniquePoolIds']} уникальных ID, физические пути, хеши и зависимости проверены.</p>
<p>Просмотрены реальные игровые кадры 40, <a href="screenshots/fidelity-v38-game-80.png">80</a>, 140 и 190 секунд и <a href="screenshots/fidelity-v38-overview.png">обзор движка</a>, без ретуши. Полный круг Time Trial естественно завершился <a href="screenshots/fidelity-v38-natural-finish.png">финишем #1</a>. Временная карта и добавленные тестовые ресурсы очищены; прежние установленные факелы, деревья и холмы не менялись. Это один заезд, а не проверка всех режимов или производительности; все возможные регрессии исходной рампы не исключены.</p>
<p class="note">Рабочий вариант ещё не заменил основную карту, итоговый пользовательский .blend и превью V1. Полное соответствие референсу не подтверждено: освещение (включая слишком тёмные нижние стороны облаков), старые яркие зелёные/лавовые поверхности и четыре крыши без фактуры остаются в работе. Новая сборка, обратный режим и вся кампания не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v38/native/Volcano%20Remake.blend">Blender V38</a> · <a href="evidence/fidelity-v38/preservation-verification.json">Габариты, стыки, полотно и вес</a> · <a href="evidence/fidelity-v38/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v38/runtime-validation.json">Полный круг</a> · <a href="evidence/fidelity-v38/pool-audit.json">Пул</a></p>
<figure><a href="screenshots/fidelity-v38-game-40.png"><img src="screenshots/fidelity-v38-game-40.png" alt="Каменные колонны V38"></a><figcaption>Реальный игровой кадр iOS Simulator: сохранённая каменная фактура, объёмные травяные края и облака. Полотно сохранено.</figcaption></figure>
<figure><a href="screenshots/fidelity-v38-game-140.png"><img src="screenshots/fidelity-v38-game-140.png" alt="Нижний поворот V38"></a><figcaption>Реальный игровой кадр нижнего поворота. Старые лавовые и зелёные поверхности ещё требуют визуальной доработки.</figcaption></figure></section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v38-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v37-draft">',section+'<section id="fidelity-v37-draft">',1);s=re.sub(r'<div class="tags">.*?</div>', '<div class="tags"><span>Рабочий V38</span><span>Вес −21.10% к V1</span><span>522 общих части</span></div>',s,count=1,flags=re.S);s=s.replace('FLUXARA DRIFT · КАРТА 10 · 01.10.2026','FLUXARA DRIFT · КАРТА 10 · 02.10.2026');s=s.replace('<a href="../Volcano%20Remake.blend">Изменённый Blender-проект</a>','<a href="../../volcano-remake-rework/fidelity-v38/native/Volcano%20Remake.blend">Рабочий Blender V38</a> · <a href="../Volcano%20Remake.blend">Основной проект V1 (ещё не заменён)</a>',1);page.write_text(s);manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
# APFS copy-on-write snapshots preserve independent report files without consuming another half gigabyte.
def clonefile(src,dst):
 dst=Path(dst)
 if dst.exists():
  if Path(src).read_bytes()==dst.read_bytes():return str(dst)
  dst.unlink()
 subprocess.run(['/bin/cp','-c',str(src),str(dst)],check=True);return str(dst)
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dst in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v38/report']:shutil.copytree(out,dst,dirs_exist_ok=True,copy_function=clonefile)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v38'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V38 source/native/pool/naturalTT#1 verified. Source stone pixels retained,82side-skirt caps, rolling far terrain beyond60mroad margin,8clouds;6,069,839B. Reference fidelity incomplete, production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateAllFilesBytes'],'candidateBytesIncludingNewSharedRuntime':b['allCandidateAndAcceptedHistoryBytes'],'candidateSavedBytesAgainstPrevious':b['savingVsV1Bytes'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V38','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':n['nativePrototypeCount'],'candidateNativeSharedParts':n['nativeSharedParts'],'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V38';data['status']='V38 shape/sky batch source/native/canonical/pool/naturalTT#1 verified,6,069,839B. Stone pixels retained. Sourcebounds originaxes andprotectedcourse preserved. Reference fidelity notcomplete; production/final/preview V1.';data['workingEvidence']['V38']='Grass4282B +10.76%,16bottomverts32faces within sourcebounds,normaldiagnostic corrected/rejected archived.82interfaces/peaks retained,160old+84farplants grounded. Field58857BsameUVcolorsindexcountbounds,Ychangesoutside60mroadzone.8clouds15446Bsamegeo normalsbounds RGBvariant.3newphysicalprotos6poolrecords, no newpixels. NaturalTT#1, cleanupverified, report2gameframes.';data['nextVisibleTarget']='Complete a coherent whole-view visual correction for remaining legacyneongreen/lava/fourplaincones/lighting without changing road/control/physics or stonepixels. Avoid another coordinates-only or seam-only loop. Then integrate10 source/final/preview. Finish3/4 pendingnative/game/pool integrations; retainmap5approvedfreeze, checkmap7full11laps, then1-10enrichmentcoordinatephase andpreviewupdates.';data.pop('plannedNextBatchOnly',None);data.pop('inProgressCandidate',None);plan.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('V38_REPORT_SAVED',len(m['files']),flush=True)
