from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v29';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v29';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text())
assert run['naturalFinishObserved']and native['allOtherNativeMeshGeometryUVsNormalsColorsAndMaterialsExactV28']==567
for f in w.glob('*.json'):
    if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
figures=[]
for second,caption in [(40,'Каменные группы справа: нижняя часть расширена, исходная каменная фактура сохранена. Геометрия дорожного полотна не менялась.'),(140,'Подъём у каменного склона после правки общей модели. Дорога, знаки поворота и игровые точки сохранены.')]:
    name=f'fidelity-v29-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name)
    figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V29"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
for name,src in [('fidelity-v29-overview.png',w/'screenshots/smoke-diagnostic-all.png'),('fidelity-v29-natural-finish.png',w/'screenshots/natural-finish.png'),('fidelity-v29-ramp-80.png',w/'screenshots/drive-80s.png')]:shutil.copy2(src,out/'screenshots'/name)
section=f'''<section id="fidelity-v29-draft"><h2>Последняя доработка — V29: каменная текстура и более широкие основания</h2>
<p>По замечанию «С текстурой камня было лучше» сохранена прежняя каменная фактура: 39&nbsp;938 байт, SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Новые пиксели и материалы не создавались.</p>
<p>У общей модели каменного основания расширены 43 нижние вершины. Сетка осталась прежней: 95 вершин и 152 треугольника. Верхняя часть с её нормалями, индексированная топология, UV, цвета, локальный активный габарит, начало координат и оси сохранены; нормали нижней части пересчитаны. Это отдельная копия объекта из пула, исходная модель не менялась. Все 58 каменных экземпляров ссылаются на один новый общий экспорт. Их позиции, масштаб и направления совпадают с V28; зелёные шапки и прочий декор не изменены.</p>
<p>Независимая проверка подтвердила отсутствие вырожденных или перевёрнутых треугольников. У модели сохранены 220 общих рёбер и 16 исходных открытых рёбер у верхней границы, которую закрывает отдельная зелёная шапка. Все каменные экземпляры проверены относительно 2&nbsp;032 защищённых треугольников дороги; минимальное расстояние — {b['independentAllNewStoneTriangleRoadMarginMeters']:.3f} м. Полотно, физические модели, контрольные файлы и остальные узлы карты совпадают с V28.</p>
<table><tr><th>Вес</th><th>До</th><th>После</th></tr>
<tr><td>Общая каменная модель с используемой текстурой, байт</td><td>{b['sourceModelWithTextureBytes']:,}</td><td>{b['targetModelWithTextureBytes']:,}</td></tr>
<tr><td>Карта со всеми новыми общими ресурсами, включая сохранённые ранние варианты, байт</td><td>{b['v1Bytes']:,} (интегрированный V1)</td><td>{b['candidateIncludingNewSharedBytes']:,}</td></tr></table>
<p>Модель с текстурой не выросла; верхний предел +20% по весу соблюдён. Новый вариант библиотеки с XML добавил {b['changeBytesAgainstIntermediateV28']:,} байт относительно V28. Карта с новыми общими ресурсами легче V1 на {b['savingBytesVsV1']:,} байт ({b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%). Размер новой сборки приложения не измерялся.</p>
<p>В Blender 58 экземпляров используют один новый меш. Все прежние 625 матриц размещения и остальные 567 мешей совпали с V28 по геометрии, UV, нормалям, цветам и материалам. Добавлен один скрытый прототип; прежний донорский прототип сохранён. Всего в ведомости 37 прототипов, 92 определения материалов и 340 общих размещённых частей. Новый прототип проверен в канонической библиотеке; все {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов ведомости разрешаются в реальные файлы с совпадающими хешами и зависимостями. Новых текстур или материалов нет.</p>
<p>Полный круг Time Trial завершился естественным <a href="screenshots/fidelity-v29-natural-finish.png">результатом #1</a> без принудительной победы. Проверены четыре игровых кадра: 40, <a href="screenshots/fidelity-v29-ramp-80.png">80 — исходная наклонная рампа с ускорителем</a>, 140 и 190 секунд. Опасное прохождение рампы ранее наблюдалось и в V1; эта правка не исправляет его и не исключает все регрессии. Временные игровые ресурсы убраны из установленного приложения; доноры и существующие эффекты сохранены, предупреждения материалов совпали с предыдущими.</p>
<p>Игровые кадры ниже и <a href="screenshots/fidelity-v29-overview.png">диагностический вид</a> сохранены без ретуши. На диагностике слева остаётся чёрная системная/UI-плашка. Расширение улучшило нижний силуэт; посадка каждого выступа на поверхность ещё не подтверждена. Общая композиция по-прежнему отличается от референса: центральная масса, дальние стены, замок, растительность и атмосфера требуют работы.</p>
<p class="note">Это проверенный промежуточный вариант. Основная карта, итоговый пользовательский .blend и превью пока V1; новая версия туда не перенесена. Новая сборка, производительность, обратный режим и вся кампания не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v29/native/Volcano%20Remake.blend">Blender V29</a> · <a href="evidence/fidelity-v29/preservation-verification.json">Сохранность и вес</a> · <a href="evidence/fidelity-v29/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v29/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v29/pool-audit.json">Пул</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v29-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V28','Предыдущая доработка — V28');s=s.replace('<section id="fidelity-v28-draft">',section+'<section id="fidelity-v28-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v29/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v29'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V29 stone pixels retained and copied lower bodies broadened for58 coordinate instances. Model bytes/local bounds/UV/topology/poses retained, protected road/physics exact. Native/canonical/pool and natural full lap #1 verified. Ground contact, broad terrain/castle/vegetation/atmosphere/reference fidelity unfinished; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V29','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':37,'candidatePrototypeIdsReferencedByNativeSharedParts':21,'fullyAccepted':False});data['maps']['10'].pop('candidateActiveNativePrototypes',None);data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V29';data.pop('inProgressCandidate',None);data['status']='V29 verified: stone pixels retained, broader lower body on58 copied instances. Original local dimensions/topology/UV/poses and road/physics preserved. Source/native/canonical/pool, natural full lap and report verified. Reference fidelity and production/final/preview integration unfinished.';data['workingEvidence']['V29']='Terminal source/native/canonical/runtime verified.43 lower vertices adapted, model2533B/95vertices/152triangles,42,471B with texture unchanged.58 instances,567 other meshes/625 matrices exactV28. Total6,654,245B, full natural lap#1.'
data['nextVisibleTarget']='Improve large-scale reference composition: replace or reshape copied decorative stone silhouettes without covering or changing the road, add suitable pooled vegetation by coordinates, improve castle proportions and blue/gold sky/atmosphere. Stone pixels retained. Broader feet alone do not establish reference match or verified ground contact for every group.'
for q in data['priorities']:
    if q['role']=='Rounded central cliff support and green terrain':q.update({'completedCandidate':'V29 partial','remaining':data['nextVisibleTarget']})
plan.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('V29_REPORT_UPDATED',len(m['files']),flush=True)
