from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v28';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v28';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text())
p26=json.loads((r/'fidelity-v26/preservation-verification.json').read_text());p27=json.loads((r/'fidelity-v27/preservation-verification.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text())
assert run['naturalFinishObserved']and native['allNativeMeshGeometryUVsNormalsColorsAndMaterialsExactV26']==625 and audit['newTextures']==0
for version in [26,27,28]:
    target=e/f'v{version}';target.mkdir(exist_ok=True)
    for f in(r/f'fidelity-v{version}').glob('*.json'):
        if not f.name.startswith('pool-before'):shutil.copy2(f,target/f.name)
shutil.copy2(r/'fidelity-v25/rejected-candidate.json',e/'rejected-v25.json')
figures=[]
for second,caption in [(40,'Высокие каменные группы справа стали видны с дороги после переноса к внешней стороне склонов. Каменная фактура сохранена; нижние части пока слишком сужены.'),(140,'Проезд под каменной аркой. Исходная дорога, арка и игровые точки сохранились.')]:
    name=f'fidelity-v28-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name)
    figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V28"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
for name,src in [('fidelity-v28-overview.png',w/'screenshots/smoke-diagnostic-all.png'),('fidelity-v27-overview.png',r/'fidelity-v27/screenshots/smoke-diagnostic-all.png'),('fidelity-v28-natural-finish.png',w/'screenshots/natural-finish.png'),('fidelity-v28-ramp-80.png',w/'screenshots/drive-80s.png')]:shutil.copy2(src,out/'screenshots'/name)
section=f'''<section id="fidelity-v28-draft"><h2>Последняя доработка — V28: высокие каменные группы по координатам</h2>
<p>Каменная текстура размером 39&nbsp;938 байт сохранена по замечанию пользователя. Её пиксели не менялись: SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Новых изображений или материалов нет.</p>
<p>Центральная каменная опора в V26 сглажена: 64 исходные грани декоративного камня заменены 1&nbsp;024 гранями. Её активный габарит, начало координат, оси и размещение прежние; сдвиг вершин — до 3,14 м. Точная исходная физическая сетка камня сохранена отдельной невидимой моделью. Остальные поверхности, включая 532 грани арки, сохранились. UV исходных вершин оставлены, для новых вершин интерполированы. Независимая проверка перемещённых граней дала нижнюю границу расстояния до дороги 5,000 м.</p>
<p>58 ранее добавленных общих уступов разделены на две части: зелёную шапку и каменное основание. Их сетки, UV, нормали, цвета, локальные габариты и центры точно переиспользованы из пула; это отдельные игровые экспорты существующих компонентов. Высота размещённых каменных оснований увеличена в 2,8 раза, ширина уменьшена до 90%; верх оснований остался на прежней высоте. Это изменение размеров экземпляров ранее добавленного декора; размеры самих исходных общих моделей не менялись. Всего карта хранит 116 ссылок на две общие библиотеки вместо 58 ссылок на объединённую библиотеку. Геометрия каждого размещения не записывается в карту отдельным файлом.</p>
<p>Первый вид показал, что основания скрываются внутри старых стен. В V28 47 подходящих групп вынесены к наружной стороне склонов; шапки и основания перемещены вместе по X/Z, их высота, масштаб и направление сохранены относительно V27. Остальные группы оставлены после проверки расстояний. Все {b['independentlyCheckedMovedPartTriangles']:,} грани перенесённых частей проверены относительно 2&nbsp;032 защищённых треугольников проезда. Минимальное расстояние для этих 47 групп — {b['independentMovedPartTriangleRoadMarginMeters']:.3f} м. Для более раннего удлинения всех оснований отдельно проверена сетка, минимальный запас составлял 1,282 м.</p>
<table><tr><th>Модель с используемой текстурой</th><th>Исходный вес, байт</th><th>Новый вес, байт</th><th>Изменение</th></tr>
<tr><td>Центральная каменная опора; новый вес включает точную исходную физическую копию</td><td>{p26['originalStoneRegionWithOriginalTextureBytes']:,}</td><td>{p26['adaptedModelOriginalCollisionAndStoneTextureBytes']:,}</td><td>{p26['modelWithTextureChangePercent']:.2f}%</td></tr>
<tr><td>Общий компонент зелёной шапки</td><td>{p27['sourceComponentWithTextureBytes'][0]:,}</td><td>{p27['targetComponentWithTextureBytes'][0]:,}</td><td>{(p27['targetComponentWithTextureBytes'][0]/p27['sourceComponentWithTextureBytes'][0]-1)*100:.2f}%</td></tr>
<tr><td>Общий каменный компонент с используемой текстурой</td><td>{p27['sourceComponentWithTextureBytes'][1]:,}</td><td>{p27['targetComponentWithTextureBytes'][1]:,}</td><td>{(p27['targetComponentWithTextureBytes'][1]/p27['sourceComponentWithTextureBytes'][1]-1)*100:.2f}%</td></tr></table>
<p>Верхний предел +20% проверен по весу модели с используемой текстурой, без ограничения количества полигонов этим процентом. Для центральной опоры исходный вес сопоставлен с точно выделенными 64 гранями до переделки и их реально использованной Lava_004_COLOR.jpg. Для разделённых компонентов небольшое увеличение — заголовки отдельных SPM; сами индексированные данные не менялись.</p>
<table><tr><th>Вес карты</th><th>Результат</th></tr>
<tr><td>Карта + все новые общие игровые ресурсы, включая сохранённые ранние варианты</td><td>{b['candidateIncludingNewSharedBytes']:,} байт</td></tr>
<tr><td>Интегрированный V1</td><td>{b['v1Bytes']:,} байт</td></tr>
<tr><td>Уменьшение относительно V1</td><td>{b['savingBytesVsV1']:,} байт; {b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%</td></tr>
<tr><td>Изменение относительно V24</td><td>+{b['candidateIncludingNewSharedBytes']-json.loads((r/'fidelity-v24/preservation-verification.json').read_text())['candidateIncludingNewSharedBytes']:,} байт</td></tr></table>
<p>Предварительный V25 отвергнут: 564&nbsp;532 дополнительных байта дали слишком слабое изменение контура. Его новая библиотека перемещена из ресурсов приложения в архив с проверкой всех байтов; она не используется и не входит в текущий игровой вес. Оригиналы и донорские библиотеки сохранены. Размер свежей сборки приложения здесь не измерялся.</p>
<p>В Blender активны 36 прототипов, 92 определения материалов и 340 общих частей. Все 625 мешей совпали с V26 по геометрии, UV, нормалям, цветам и материалам. Относительно V26 намеренно изменены матрицы 105 частей; у прочих максимальная погрешность сохранения матрицы — {native['otherMatrixMaxFloatRoundoffVsV26']:.9f}. Центральная опора проверена отдельно: 621 другой меш совпал с V24, геометрия/UV/цвета арки и исходного физического камня сохранены; повторная запись нормалей выделенных частей в Blender дала погрешность компонентов до 0,0000471, угловая погрешность менее 0,01°. В игровых SPM нормали оставшихся поверхностей и исходного физического камня совпали точно.</p>
<p>Один новый прототип центральной опоры добавлен в каноническую библиотеку; две части уступов используют существующие прототипы. Все {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов ведомости имеют реальные файлы, совпадающие размеры/хеши и разрешённые зависимости. Новых пикселей, материалов или модели на каждый экземпляр нет.</p>
<p>Полный круг Time Trial в симуляторе завершился естественным результатом <a href="screenshots/fidelity-v28-natural-finish.png">#1</a>, без принудительной победы. Проверены четыре кадра: дорога на 40-й секунде, <a href="screenshots/fidelity-v28-ramp-80.png">наклонная исходная рампа с ускорителем на 80-й</a>, дорога под аркой на 140-й, результат на 190-й. Ранее в исходном V1 наблюдалось опасное прохождение рампы; его причина не исправлена, все регрессии не исключены. Временные карты и скопированные ресурсы удалены из установленного приложения; донорские факелы, эффекты и холмы не менялись. Предупреждения материалов совпали с V24.</p>
<p>Два игровых кадра ниже сохранены без ретуши. Диагностические виды из той же камеры: <a href="screenshots/fidelity-v27-overview.png">V27, основания преимущественно скрыты</a> и <a href="screenshots/fidelity-v28-overview.png">V28, группы вынесены наружу</a>. На диагностике V28 слева видна чёрная системная/UI-плашка; она оставлена без ретуши. Дорожные кадры не заявляются как покадрово одинаковые траектории разных запусков.</p>
<p class="note">Сходство с референсом ещё не достигнуто. Нижние части высоких групп слишком сужены, некоторые читаются как подвешенные; нужно исправить основание и посадку. Большая центральная масса, дальние стены, замок и атмосфера также требуют работы. Основная карта, итоговый пользовательский .blend и превью пока V1. Новая сборка, производительность, обратный режим и вся кампания здесь не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v28/native/Volcano%20Remake.blend">Blender V28</a> · <a href="evidence/fidelity-v28/v26/preservation-verification.json">Центральная опора</a> · <a href="evidence/fidelity-v28/v27/preservation-verification.json">Общие части</a> · <a href="evidence/fidelity-v28/v28/preservation-verification.json">Размещения и вес</a> · <a href="evidence/fidelity-v28/v28/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v28/v28/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v28/v28/pool-audit.json">Общий пул</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v28-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V24','Предыдущая доработка — V24');s=s.replace('<section id="fidelity-v24-draft">',section+'<section id="fidelity-v24-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v28/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v28'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V28 rounded central support and visible47tall copied cliff groups. Exact pooled part geometry and stone pixels reused, original collision/controls retained. Native/canonical/pool and natural one-lap #1 verified. Tapered feet/ground contact, large walls and reference composition unfinished; production/final/preview V1.',
    'candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V28','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateActiveNativePrototypes':36,'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V28';data.pop('inProgressCandidate',None)
data['status']='V28 verified. Stone pixels retained; central support softened and47copied groups moved outward so tall stone forms visible. Model/texture +20% passed; total6651447B. Full natural one-lap #1, source/canonical/ledger complete. Reference fidelity still unfinished.'
data['nextVisibleTarget']='Fix narrow/tapered stone feet and apparent hanging placement, using a copied pooled stone component within its original local bounds, matching original stone pixels. Do not repeat costly weak outer-wall subdivision. Then major central/distant-wall composition, castle proportions, blue/gold atmosphere and suitable vegetation. Preserve protected road, collision and controls.'
for q in data['priorities']:
    if q['role']=='Rounded central cliff support and green terrain':q.update({'completedCandidate':'V28 partial','remaining':data['nextVisibleTarget']})
plan.write_text(json.dumps(data,indent=2));print('V28_REPORT_UPDATED',len(m['files']),flush=True)
