from pathlib import Path
import json,struct,copy,math,sys,hashlib,xml.etree.ElementTree as E
from PIL import Image
r=Path(__file__).resolve().parent;w=r/'fidelity-v18';p=json.loads((w/'hill-placements.json').read_text());base=json.loads((r/'fidelity-v17/preservation-verification.json').read_text());sys.path.insert(0,str(r.parent/'shared-object-redesign'));from spm_io import parse
source=Path(p['sourceModel']);d=parse(source);assert len(d['buffers'])==1;buf=copy.deepcopy(d['buffers'][0]);buf['material']=0;palette=r/'fidelity-v17/candidate/vr_moss_palette.jpg';im=Image.open(palette).convert('RGB');green=im.getpixel((int(im.width*.75),int(im.height*.5)))
for v in buf['vertices']:
 t=max(0,min(1,v['position'][1]));v['color']=tuple(round(q*(.94+.12*t))for q in green);v.pop('uv',None)
code=(r/'fidelity_v2.py').read_text();ns={'math':math,'struct':struct};exec(code[code.index('def encode_buffer'):code.index('new_vertices, new_indices')],ns)
lib=Path('/Users/motoricallc/Downloads/fluxara-drift/iosApp/FluxaraResources/library/fluxara_driftlib_volcano_green_mound_v18');lib.mkdir(exist_ok=True);model=lib/'vr_v18_green_mound.spm';model.write_bytes(b'SP'+bytes([10,3])+struct.pack('<6f',*d['bounds'])+struct.pack('<H',1)+bytes([0,0])+struct.pack('<HH',1,1)+ns['encode_buffer'](buf,[['','']]))
(lib/'node.xml').write_text('<scene><object id="GreenMound" type="animation" model="vr_v18_green_mound.spm" xyz="0 0 0" hpr="0 0 0" scale="1 1 1" interaction="ghost" skeletal-animation="false" /></scene>');(lib/'materials.xml').write_text('<materials />')
new=parse(model);assert new['bounds']==d['bounds'];assert new['buffers'][0]['indices']==d['buffers'][0]['indices'];assert all(a['position']==b['position']and a['normal']==b['normal']for a,b in zip(d['buffers'][0]['vertices'],new['buffers'][0]['vertices']));after=model.stat().st_size;assert after<=p['sourceModelWithTextureBytes']*1.2;scene=E.parse(w/'candidate/scene.xml')
for q in p['placements']:
 e=scene.getroot().find(f"library[@id='{q['id']}']");assert e.get('name')==Path(p['sourceLibrary']).name;e.set('name',lib.name);q['library']=lib.name
scene.write(w/'candidate/scene.xml',encoding='unicode');libbytes=sum(q.stat().st_size for q in lib.iterdir()if q.is_file());mapbytes=sum(q.stat().st_size for q in(w/'candidate').iterdir()if q.is_file());total=mapbytes+base['newSharedLibraryBytesIncludingRetainedHistoricalVariants']+libbytes+base['newGlobalTextureBytes'];assert total<base['v1Bytes']
p.update({'adaptedModel':str(model),'adaptedLibrary':str(lib),'adaptedModelSha256':hashlib.sha256(model.read_bytes()).hexdigest(),'modelWithTextureChangePercent':(after/p['sourceModelWithTextureBytes']-1)*100,'targetModelWithTextureBytes':after,'newRuntimeModelAndTextureFiles':1,'newRuntimeTextureFiles':0,'vertexColorsDerivedFromExistingPalette':str(palette),'sampledGreenRGB':green,'sourcePositionsIndicesNormalsBoundsExact':True,'copiedSourceUVsRemovedForVertexColorVariant':True,'nativeMaterialReused':'VRV16_GrassLipVertexColor','newSharedLibraryBytesIncludingRetainedHistoricalVariants':base['newSharedLibraryBytesIncludingRetainedHistoricalVariants']+libbytes,'candidateMapBytes':mapbytes,'candidateIncludingNewSharedBytes':total,'savingBytesVsV1':base['v1Bytes']-total,'allPriorModelTextureAndControlBytesExact':True,'allSourceLocalGeometryBoundsOriginsAxesUnchanged':True,'weightAccounting':'Candidate map plus all new shared volcano runtime files, including prior variants and this one green mound library. Existing brown hill source is retained for other maps.'})
(w/'hill-placements.json').write_text(json.dumps(p,indent=2));(w/'preservation-verification.json').write_text(json.dumps(p,indent=2));print('V18_GREEN_HILL_VARIANT_READY',len(p['placements']),total,p['modelWithTextureChangePercent'],flush=True)
