from pathlib import Path
import bpy,json,math,hashlib,sys,xml.etree.ElementTree as E
from mathutils import Matrix,Euler,Vector
r=Path(__file__).resolve().parent;w=r/'fidelity-v18';pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK');mod=pack/'models/volcano-remake-fidelity-v18';mod.mkdir(exist_ok=True);native=w/'native';native.mkdir(exist_ok=True);a=json.loads((r/'fidelity-v17/asset-registration.json').read_text());proof=json.loads((w/'hill-placements.json').read_text());bpy.ops.wm.open_mainfile(filepath=a['finalBlend']);bpy.context.preferences.filepaths.save_version=0;sys.path.insert(0,str(r.parent/'shared-object-redesign'));from spm_io import parse
helper=(r/'finalize_fidelity_v9.py').read_text();exec(helper[helper.index('def mesh_from_buffer'):helper.index('updates=a')]);helper=(r/'finalize_fidelity_v15.py').read_text();exec(helper[helper.index('def native_mesh'):helper.index('newrows=[]')]);mat=bpy.data.materials[proof['nativeMaterialReused']];d=parse(proof['adaptedModel']);mesh=native_mesh('VRV18_GreenMoundMesh',d['buffers'][0],[mat]);proto=bpy.data.objects.new('VRV18_Prototype_GreenMound',mesh);bpy.data.collections['Volcano Remake Asset Prototypes'].objects.link(proto);proto.hide_set(True);proto.hide_render=True;proto['asset_id']='volcano-fidelity-v18-green-mound';proto['source_model']=proof['adaptedModel'];proto['source_buffer']=0;row={'id':proto['asset_id'],'name':proto.name,'sourceModel':proof['adaptedModel'],'sourceBuffer':0,'triangles':360,'materials':[mat.name],'sourcePoolObjectId':proof['sourcePoolObjectId'],'role':'Separate green variant of existing grassy hill: source positions, normals, indices, axes and bounds retained. Source soil palette UVs replaced with mesh colors sampled from existing green terrain palette. Existing grass vertex-color material reused; no new image.'};a['objects'].append(row);a['newPrototypes']=[row];a['newMaterialVariants']=[];a['runtimeLibrarySources'][Path(proof['adaptedLibrary']).name]=proof['adaptedLibrary'];scene=E.parse(w/'candidate/scene.xml').getroot();new=[]
for place in proof['placements']:
 xml=scene.find(f"library[@id='{place['id']}']");xyz=list(map(float,xml.get('xyz').split()));sc=list(map(float,xml.get('scale').split()));hpr=list(map(float,xml.get('hpr').split()));rot=Euler(tuple(math.radians(-v)for v in [hpr[0],hpr[2],hpr[1]]),'XZY');matrix=Matrix.Translation((xyz[0],xyz[2],xyz[1]))@rot.to_matrix().to_4x4()@Matrix.Diagonal((sc[0],sc[2],sc[1],1));o=bpy.data.objects.new(place['id'],proto.data);bpy.data.collections['Volcano Remake Shared Instances'].objects.link(o);o.matrix_world=matrix;o['source_prototype']=proto.name;o['shared_runtime_library']=Path(proof['adaptedLibrary']).name;o['asset_id']=row['id'];o['source_xml']=E.tostring(xml,encoding='unicode');a['nativeSharedInstances'].append({'name':o.name,'prototype':proto.name,'library':Path(proof['adaptedLibrary']).name,'matrix':[list(v)for v in matrix],'sourcePlacementId':place['id']});new.append(o.name)
bpy.data.texts['scene.xml'].clear();bpy.data.texts['scene.xml'].write((w/'candidate/scene.xml').read_text());lib=Path(proof['adaptedLibrary'])
for name in ['node.xml','materials.xml']:bpy.data.texts.new(lib.name+'/'+name).write((lib/name).read_text())
a['visualLibrary']=str(mod/'Volcano Remake Green Mound Library.blend');bpy.data.libraries.write(a['visualLibrary'],{proto},fake_user=True,compress=True);(mod/Path(proof['adaptedModel']).name).write_bytes(Path(proof['adaptedModel']).read_bytes());a.update({'finalBlend':str(native/'Volcano Remake.blend'),'newRoundedHillNativeObjects':new,'status':'V18 32 green variants of pooled grassy hill aligned with terrain slopes. All prior geometry, stone UVs, materials, physics and placements retained. New hill geometry/normals/bounds exact source, colors adapted; one new mesh, no new image, existing vertex-color material. Isolated candidate.'});bpy.ops.wm.save_as_mainfile(filepath=a['finalBlend']);(w/'asset-registration.json').write_text(json.dumps(a,indent=2));print('V18_NATIVE_SHARED_GREEN_MOUNDS_SAVED',len(a['objects']),len(a['materials']),len(a['nativeSharedInstances']),flush=True)
