from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v36';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v36';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());a=json.loads((w/'pool-audit.json').read_text());n=json.loads((w/'final-blend-verification.json').read_text());assert run['naturalFinishObserved']and not n['canonicalPending']
for f in w.glob('*.json'):
 if not f.name.startswith(('pool-before','ski-dash-ledger-before')):shutil.copy2(f,e/f.name)
for name,source in [('fidelity-v36-overview.png','smoke-diagnostic-all.png'),('fidelity-v36-natural-finish.png','natural-finish.png'),('fidelity-v36-game-140.png','drive-140s.png'),('fidelity-v36-game-40.png','drive-40s.png'),('fidelity-v36-game-80.png','drive-80s.png')]:shutil.copy2(w/'screenshots'/source,out/'screenshots'/name)
section=f'''<section id="fidelity-v36-draft"><h2>Текущий рабочий вариант V36: каменная фактура сохранена</h2>
<p>Камень оставлен с исходной текстурой 39&nbsp;938 байт, SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Полотно, игровые точки и линии, сценарий, quads/graph и точные коллизии сохранены. Координаты, индексы, нормали и UV основного меша совпадают с V35. Изменены только цвета четырёх старых конических крыш и имя текстуры грязевых площадок; физические свойства дороги сохранены.</p>
<p>104 старых куста и 32 холма размещены на реальных поверхностях 82 поддержанных камнем уступов. Кусты перестали быть сплющенными дисками; масштаб и координаты этих декоративных экземпляров изменены намеренно. Сами общие модели, их локальные размеры, центр, оси и текстуры не менялись. Независимо проверены полные ограничивающие сферы относительно 2&nbsp;032 дорожных треугольников: минимальный запас {b['minimumFullBoundingSphereRoadMarginMeters']:.3f} м. У новых координат нет отдельной копии геометрии или изображения.</p>
<p>Для девяти грязевых объектов и старых площадок переиспользована существующая лавовая картинка: новых пикселей нет. У скопированного общего объекта грязевых пузырей сохранён весь бинарный скелетный/анимационный payload, размеры и исходные размещения. Его модели и используемые текстуры: {b['mudModelUsedTexturesBefore']:,} → {b['mudModelUsedTexturesAfter']:,} байт (+{(b['mudModelUsedTexturesAfter']/b['mudModelUsedTexturesBefore']-1)*100:.2f}%, меньше +20%). У десяти составных башен новая крыша использует уже имеющуюся кирпичную фактуру и красный цвет; тело, положение и размеры не менялись. Полный объект башни с телом, крышей и используемой текстурой: {b['roofedTowerRootModelsAndUsedTextureBefore']:,} → {b['roofedTowerRootModelsAndUsedTextureAfter']:,} байт. Сохранились габариты самой крыши; небольшой шест упростился с восьми до четырёх сторон, основная крыша и флаг сохранены. Подсчёт не выдаёт отдельно взятую крышу без её используемой текстуры за полный объект.</p>
<p>Дым наклонён вокруг прежнего нижнего якоря; исходный локальный меш не менялся. Небо использует шесть изображений из пула первой карты, солнце и туман настроены теплее. Все новые имена текстур посчитаны как реальные дополнительные файлы игры, даже при переиспользовании пикселей. Удалены только семь ставших ненужными файлов из копии рабочего варианта; прежние исходники и архив V35 сохранены.</p>
<table><tr><th>Состав веса</th><th>Байты</th></tr><tr><td>Все файлы рабочего варианта карты</td><td>{b['candidateAllFilesBytes']:,}</td></tr><tr><td>Все файлы двух новых общих библиотек</td><td>{b['newSharedRuntimeAllFilesBytes']:,}</td></tr><tr><td>Новые общие имена изображений</td><td>{b['newSharedGlobalAliasesAllFilesBytes']:,}</td></tr><tr><td>Сохранённые ранее принятые общие модели и изображения</td><td>{b['acceptedSharedHistoryBytes']+b['acceptedSharedTextureHistoryBytes']:,}</td></tr><tr><td>Итого V36</td><td>{b['allCandidateAndAcceptedHistoryBytes']:,}</td></tr><tr><td>Прежний интегрированный V1</td><td>{b['integratedV1BaselineBytes']:,}</td></tr></table>
<p>Экономия относительно V1 — {b['savingVsV1Bytes']:,} байт ({b['savingVsV1Bytes']/b['integratedV1BaselineBytes']*100:.2f}%), относительно V35 — {b['savingVsV35Bytes']:,}. Размер приложения после новой сборки здесь не измерялся.</p>
<p>В Blender сохранены все {n['allPriorNativeObjectsRetained']} прежних меш-объекта; изменены 137 матриц декоративных объектов, материалы лавы и крыш и цвета четырёх конусов. Остальные {n['allOtherNativeAttributesExactV35']} наборов геометрии, UV, нормалей, цветов и материалов совпали с V35; остальные {n['allOtherNativeMatricesExactV35']} матрицы совпали. Каменные пиксели проверены и внутри .blend. Каноническая библиотека сохранена и открыта повторно: прежние геометрия, изображения и свечение окон зимних домов проверены. Ведомость: {a['nativePrototypes']} прототипов, {a['nativeMaterialDefinitions']} материалов и {a['nativeSharedParts']} общих размещённых частей; пул содержит {a['uniquePoolIds']} уникальных ID с проверенными физическими путями, хешами и зависимостями.</p>
<p>Полный круг Time Trial естественно завершился <a href="screenshots/fidelity-v36-natural-finish.png">результатом #1</a>. Просмотрены кадры 40, 80, <a href="screenshots/fidelity-v36-game-140.png">140</a> и 190 секунд и <a href="screenshots/fidelity-v36-overview.png">общий обзор движка</a>. Скриншоты сохранены без ретуши, включая чёрную аппаратную плашку симулятора на кадре 140 секунд. Временная карта и скопированные ресурсы после теста убраны; прежние факелы, деревья и холмы в установленной игре не изменены. Опасное прохождение исходной рампы ранее наблюдалось в V1; все возможные регрессии не исключены.</p>
<p class="note">Это рабочая доработка, соответствие всему референсу ещё не принято: остаются тонкие травяные края, плоский дальний фон, старые слишком яркие зелёные и лавовые поверхности и композиция неба. Четыре старые крыши пока окрашены без фактуры. Основная карта, пользовательский итоговый .blend и превью всё ещё V1. Новая сборка, производительность, обратный режим и вся кампания не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v36/native/Volcano%20Remake.blend">Blender V36</a> · <a href="evidence/fidelity-v36/preservation-verification.json">Полотно и вес</a> · <a href="evidence/fidelity-v36/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v36/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v36/pool-audit.json">Пул</a></p>
<figure><a href="screenshots/fidelity-v36-game-40.png"><img src="screenshots/fidelity-v36-game-40.png" alt="Игровой кадр V36 — каменные колонны"></a><figcaption>iOS Simulator, реальный проезд среди каменных колонн. Каменная фактура сохранена; на уступах — общие кусты и холмы.</figcaption></figure>
<figure><a href="screenshots/fidelity-v36-game-80.png"><img src="screenshots/fidelity-v36-game-80.png" alt="Игровой кадр V36 — исходная наклонная рампа"></a><figcaption>iOS Simulator, исходная наклонная рампа рядом с башнями. Геометрия рампы сохранена; под ней лава. Кадр не выдаётся за проезд под аркой.</figcaption></figure></section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v36-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V35','Предыдущая доработка — V35');s=s.replace('<section id="fidelity-v35-draft">',section+'<section id="fidelity-v35-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v36/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v36'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V36 source/native/canonical/pool and natural full lap#1 checked. Stone pixels retained;136plants grounded, lava/roof texture variants, leaned smoke/reusedsky. Thin greenedges/distantflatbackground/legacygreenlava/sky fidelity unfinished; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateAllFilesBytes'],'candidateBytesIncludingNewSharedRuntime':b['allCandidateAndAcceptedHistoryBytes'],'candidateSavedBytesAgainstPrevious':b['savingVsV1Bytes'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V36','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':a['nativePrototypes'],'candidateNativeSharedParts':a['nativeSharedParts'],'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V36';data['status']='V36 source/native/canonical/pool/natural#1 working checkpoint. Stone39938bytes exact.136plants grounded on82supportedcaps, newmudlava aliases withanimationpayloadexact, tiledroofroot10023B vs10067, new reusedsky/diagonal visualsmoke.6,299,754B vs7,693,535 integratedV1. Remaining thin greenedge, distantflatfield, legacyneon-green/lava surfaces and4originalredcones/backgroundsky fidelity beforeproduction/previews/enrichment1-10.';data['workingEvidence']['V36']='Source road2032tri/control/physics geometry exact;136plant bounding spheres roadclearance min2.6448m. Native726meshes/46prototypes/99materials/430sharedparts; all723priorobjects retained. Full naturalTT#1. New2runtimeLibraries+8reusedtexturealiases physicallyregistered/canonicalpreviousmesh/image andhousewindowemission exact. Source stonepixels preserved. Fullreferenceacceptance unfinished.';data['nextVisibleTarget']='Thicken82matchedgrass rims by existing source instance scales while keeping interface anchor/no newmodels, updateplant grounding if needed, replace distant flat silhouettes by pooledcliffs/trees, retainstone/course, no duplicateper-placement meshes. Assess actualgameviews before finalintegration/previews/enrichment1-10.';data.pop('inProgressCandidate',None);plan.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('V36_REPORT_SAVED',len(m['files']),flush=True)
