from pathlib import Path
import bpy,json,sys,math,hashlib,xml.etree.ElementTree as E
from mathutils import Matrix,Euler,Vector
r=Path(__file__).resolve().parent;w=r/'fidelity-v16';pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK');mod=pack/'models/volcano-remake-fidelity-v16';mod.mkdir(exist_ok=True);native=w/'native';native.mkdir(exist_ok=True);a=json.loads((r/'fidelity-v15/asset-registration.json').read_text());proof=json.loads((w/'terrain-changes.json').read_text());bpy.ops.wm.open_mainfile(filepath=a['finalBlend']);bpy.context.preferences.filepaths.save_version=0;sys.path.insert(0,str(r.parent/'shared-object-redesign'));from spm_io import parse
helper=(r/'finalize_fidelity_v9.py').read_text();exec(helper[helper.index('def mesh_from_buffer'):helper.index('updates=a')]);helper=(r/'finalize_fidelity_v15.py').read_text();exec(helper[helper.index('def native_mesh'):helper.index('newrows=[]')])
# Keep the actual existing packed stone shader/image; the runtime alias has exactly the same bytes.
stone=bpy.data.materials['VRV4E_Rock13_col.jpg'];stoneimage=next(n.image for n in stone.node_tree.nodes if n.type=='TEX_IMAGE'and n.image);alias=Path(proof['globalStoneAlias']);assert hashlib.sha256(stoneimage.packed_file.data).hexdigest()==hashlib.sha256(alias.read_bytes()).hexdigest();aliasdest=pack/'textures/volcano-remake-fidelity-v16'/alias.name;aliasdest.parent.mkdir(exist_ok=True);aliasdest.write_bytes(alias.read_bytes());a['runtimeTextureAliases']={alias.name:{'originalNativeImage':'Rock13_col.jpg','existingNativeMaterial':'VRV4E_Rock13_col.jpg','samePixelsAndShader':True,'source':str(alias),'packPath':str(aliasdest),'bytes':alias.stat().st_size,'sha256':hashlib.sha256(alias.read_bytes()).hexdigest()}}
mat=bpy.data.materials.new('VRV16_GrassLipVertexColor');mat.use_nodes=True;mat['asset_id']='volcano-fidelity-v16-grass-material';bsdf=next(n for n in mat.node_tree.nodes if n.type=='BSDF_PRINCIPLED');col=mat.node_tree.nodes.new('ShaderNodeVertexColor');col.layer_name='Color';mat.node_tree.links.new(col.outputs['Color'],bsdf.inputs['Base Color']);bsdf.inputs['Roughness'].default_value=.9;newmat={'id':mat['asset_id'],'name':mat.name,'textures':[],'adaptation':'Soft green lip uses exported mesh vertex colors; no new raster image.'};a['materials'].append(newmat);a['newMaterialVariants']=[newmat];d=parse(proof['adaptedSharedModel']);new=[];protos=[]
for i,(label,m)in enumerate([('GrassLip',mat),('StoneBody',stone)]):
 mesh=native_mesh('VRV16_'+label+'Mesh',d['buffers'][i],[m]);o=bpy.data.objects.new('VRV16_Prototype_'+label,mesh);bpy.data.collections['Volcano Remake Asset Prototypes'].objects.link(o);o.hide_set(True);o.hide_render=True;o['asset_id']='volcano-fidelity-v16-'+label.lower();o['source_model']=proof['adaptedSharedModel'];o['source_buffer']=i;row={'id':o['asset_id'],'name':o.name,'sourceModel':proof['adaptedSharedModel'],'sourceBuffer':i,'triangles':len(d['buffers'][i]['indices'])//3,'materials':[m.name],'sourcePoolObjectId':proof['sourcePoolObjectId'],'role':'Copied pooled grass-earth shelf, adapted as rounded stone cliff with compressed grass lip. Original local overall bounds, horizontal coordinates, origin and axes retained. Existing source stone pixels reused.'};new.append(row);protos.append(o)
a['objects']+=new;a['newPrototypes']=new;scene=E.parse(w/'candidate/scene.xml').getroot();added=[]
for row in proof['placements']:
 assert row['kind']=='cliff';xml=scene.find(f"library[@id='{row['id']}']");xyz=list(map(float,xml.get('xyz').split()));sc=list(map(float,xml.get('scale').split()));hpr=list(map(float,xml.get('hpr').split()));rot=Euler(tuple(math.radians(-v)for v in [hpr[0],hpr[2],hpr[1]]),'XZY');matrix=Matrix.Translation((xyz[0],xyz[2],xyz[1]))@rot.to_matrix().to_4x4()@Matrix.Diagonal((sc[0],sc[2],sc[1],1))
 for proto in protos:
  o=bpy.data.objects.new(row['id']+'_'+proto.name,proto.data);bpy.data.collections['Volcano Remake Shared Instances'].objects.link(o);o.matrix_world=matrix;o['shared_runtime_library']=row['library'];o['source_prototype']=proto.name;o['asset_id']=proto['asset_id'];o['source_xml']=E.tostring(xml,encoding='unicode');a['nativeSharedInstances'].append({'name':o.name,'prototype':proto.name,'library':row['library'],'matrix':[list(v)for v in matrix],'sourcePlacementId':row['id']});added.append(o.name)
for o in bpy.data.objects:
 if o.get('source_model')and 'fidelity-v15/candidate'in o['source_model']:o['source_model']=o['source_model'].replace('fidelity-v15/candidate','fidelity-v16/candidate')
 if o.get('source_xml'):o['source_xml']=o['source_xml'].replace('Rock13_col.jpg',alias.name)
for row in a['nativeOriginalObjects']:
 if 'sourceXml'in row:row['sourceXml']=row['sourceXml'].replace('Rock13_col.jpg',alias.name)
for filename in ['scene.xml','materials.xml']:
 bpy.data.texts[filename].clear();bpy.data.texts[filename].write((w/'candidate'/filename).read_text())
lib=Path(proof['adaptedSharedLibrary']);a['runtimeLibrarySources'][lib.name]=str(lib)
for filename in ['node.xml','materials.xml']:bpy.data.texts.new(lib.name+'/'+filename).write((lib/filename).read_text())
a['visualLibrary']=str(mod/'Volcano Remake Rounded Terrain Library.blend');bpy.data.libraries.write(a['visualLibrary'],set(protos)|{mat},fake_user=True,compress=True);(mod/Path(proof['adaptedSharedModel']).name).write_bytes(Path(proof['adaptedSharedModel']).read_bytes());a.update({'finalBlend':str(native/'Volcano Remake.blend'),'newRoundedTerrainNativeObjects':added,'status':'V16 58 rounded stone-cliff placements from one copied pooled shelf. Stone pixels retained; runtime aliases share one global file. Existing native stone shaders/images intentionally reused unchanged. All prior geometry, UVs, matrices, physics and control meshes unchanged. Isolated candidate.'});bpy.ops.file.pack_all();bpy.ops.wm.save_as_mainfile(filepath=a['finalBlend']);(w/'asset-registration.json').write_text(json.dumps(a,indent=2));print('V16_NATIVE_ROUNDED_TERRAIN_SAVED',len(a['objects']),len(a['materials']),len(a['nativeSharedInstances']),flush=True)
