// Generated by tools/motorica_assets/build_assets.py. Do not edit.
#ifndef HEADER_DOWNLOAD_ASSETS_SIZE_HPP
#define HEADER_DOWNLOAD_ASSETS_SIZE_HPP
inline unsigned long long getDownloadAssetsSize()
{
    return 105149585ull;
}
#endif
