from pathlib import Path
import json,shutil,html,re,hashlib
from PIL import Image,ImageStat
r=Path(__file__).resolve().parent;out=r.parent/'fluxara-summit-run-final/report'
for sub in ['screenshots','references','evidence']:(out/sub).mkdir(parents=True,exist_ok=True)
a=json.load(open(r/'preservation-audit.json'));d=json.load(open(r/'delivery-verification.json'));MB=lambda n:f'{n/1e6:.2f}'.replace('.',',');layout=json.load(open(r/'layout-summary.json'))['counts']
def fig(src,title,note):return f'<figure><a href="{src}"><img src="{src}" alt="{html.escape(title)}" loading="lazy"></a><figcaption><strong>{title}</strong><span>{note}</span></figcaption></figure>'
shutil.copy2(r/'references/figma-ninth.png',out/'references/reference.png');shots=[]
for name,title,note in [('final-normal-lap-25s.png','Каменная часть маршрута','Последняя версия; форма исходной дороги сохранена.'),('final-normal-lap-80s.png','Ледяная часть маршрута','Игровая камера; свойства льда и снега исходные.'),('final-campaign-440s.png','Финиш гонки кампании','Три круга, естественный финиш. Проверка до последней правки цвета снежных скал и добавления декоративного потока; игровые данные и физика те же.'),('final-normal-lap-150s.png','Полный круг итоговой версии','Обычная гонка с одним картом и одним кругом, после последних декоративных изменений.'),('preview-ice.png','Ледяной поворот','Камера осмотра в игровом движке; исходник нового превью.'),('section-cascade.png','Поток на скале','Декоративная полоса воды следует поверхности исходной скалы; полотно трассы не изменено.'),('section-bridge.png','Мост','Исходная геометрия и размещение деревянного моста сохранены.'),('section-valley.png','Нижняя долина','Камера осмотра в игровом движке.')]:
 p=r/'screenshots'/name
 if p.is_file():
  im=Image.open(p).convert('RGB');w,h=im.size
  if max(ImageStat.Stat(im.crop((w*.15,h*.15,w*.85,h*.85))).stddev)>6:shutil.copy2(p,out/'screenshots'/name);shots.append((name,title,note))
evidence=['preservation-audit.json','delivery-verification.json','final-blend-verification.json','layout-verification.json','arrow-verification.json','pool-audit.json','fir-compatibility.json','waterfall-conformance.json','snow-cliff-shading.json','runtime-validation.json','final-campaign-capture.json','final-normal-lap-capture.json','final-section-captures.json','preview-update.json','campaign-preview-verification.json']
for n in evidence:
 if (r/n).exists():shutil.copy2(r/n,out/'evidence'/n)
style=(r.parent/'spell-lab-rework/report-style.css').read_text()
s=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Summit Run — отчёт</title><style>{style}</style></head><body><main><div class="label">FLUXARA DRIFT · КАРТА 09 · 01.10.2026</div><h1>Summit Run</h1><p class="lead">Единый альпийский зимний стиль: голубой лёд, светлые скалы, снежные ели и каменные столбики, красно-белые блоки, флажки и полосатый воздушный шар. Исходная дорога и игровые структуры сохранены.</p><div class="tags"><span>Вес −{abs(a['byteChangePercent']):.2f}%</span><span>Треугольники +{a['triangleChangePercent']:.2f}%</span><span>{a['newSharedPlacementCount']} общих размещения по координатам</span></div><p><a href="../Summit%20Run.blend">Изменённый Blender-проект</a> · <a href="evidence/preservation-audit.json">Геометрия и бюджет</a> · <a href="evidence/delivery-verification.json">Проверка ресурсов</a></p><h2>Референс</h2>{fig('references/reference.png','Figma 378:49','Снежные скалы и ели, ледяной поворот, столбики с белыми шапками, красно-белое ограждение, флажки и водопад.')}<p><a href="https://www.figma.com/design/Pws4Hw0fwwTmTMf6OJvil8/Fluxara-drift?node-id=378-49">Референс в Figma</a></p><table><tr><th>Элемент</th><th>Результат</th></tr><tr><td>Ели</td><td>32 исходных дерева получили объёмные снежные кроны из общего пула, добавлены ещё 3 ели. Геометрия и координаты исходных коллайдеров сохранены отдельно.</td></tr><tr><td>Окружение</td><td>20 столбиков со снежными шапками, 4 общих красно-белых блока, 5 гирлянд, 1 декоративный поток на скале.</td></tr><tr><td>Навигация</td><td>8 направляющих щитов только у поворотов. Они обращены к приближающемуся потоку прямого направления. Игровые ускорители со своей разметкой сохранены.</td></tr><tr><td>Подвижные объекты</td><td>Ледяные блоки и падающий камень исходные. У воздушного шара изменена ткань; форма, центр, направление и кривые движения сохранены.</td></tr></table><p class="note">Окончательное визуальное согласование не записано. Исходная трасса имеет каменные, ледяные и снежные участки и другую композицию, чем иллюстрация. Игровой свет и отражения проще референса; точное совпадение с ним не заявляется.</p><h2>Игровые кадры</h2>'''
for name,title,note in shots:s+=fig('screenshots/'+name,title,note)
s+=f'''<h2>Вес</h2><table><tr><th>Измерение</th><th>Результат</th></tr><tr><td>Исходная папка карты</td><td>{MB(a['originalBytes'])} МБ</td></tr><tr><td>Текущая папка карты</td><td>{MB(a['trackFolderBytes'])} МБ</td></tr><tr><td>Все новые общие ресурсы</td><td>{a['newSharedBytes']:,} байт; уже существующие общие файлы не скрыты в измерении</td></tr><tr><td>Карта с новыми общими ресурсами</td><td>{MB(a['trackAndNewSharedBytes'])} МБ, уменьшение на {MB(a['originalBytes']-a['trackAndNewSharedBytes'])} МБ</td></tr><tr><td>Отображаемые треугольники при подробном LOD</td><td>{a['originalTriangles']:,} → {a['newTriangles']:,}; +{a['triangleChangePercent']:.2f}%</td></tr><tr><td>Распакованное приложение</td><td>{MB(d['live']['appBytes'])} МБ, Debug iOS Simulator. Это не размер IPA или скачивания.</td></tr></table><p>Каждое новое размещение ссылается на общую игровую модель. Отдельный меш для каждого экземпляра в карту не записан. Исходные скалы и дорога остаются в основном меше; общий этап дальнейшей оптимизации карт 1–10 выполняется после готовности всех десяти. Музыка и её быстрый вариант сохранены.</p><h2>Проверки сохранности</h2><p>Все позиции вершин, нормали и индексы основного меша совпадают с исходными. UV исходные во всех буферах, кроме снежных скал №9, где палитра убирает пёстрый рисунок и выделяет снег на верхних гранях. Дорожный лёд, снег, мост, ускорители и невидимые контрольные поверхности сохраняют UV и геометрию.</p><p>track.xml, graph.xml и quads.xml совпадают побайтово. Предметы, старты, контрольные линии, анимации и свойства подвижных препятствий сохранены. Все исходные определения физических материалов совпадают. Старые меши деревьев работают через штатный путь physics-only: движок сохраняет треугольный коллайдер и удаляет его визуальный узел. Вариант новой ели удаляет только служебный канал силы ветра, который делал крону чёрной в режиме совместимости; форма, нормали, UV и индексы исходной модели пула не изменены.</p><p>У новых размещений не найдены вершины в дорожном коридоре до высоты 3,5 м над исходными квадрами. Некоторые верхние кроны находятся выше него. Дополнительно проверялись периметры при размещении. Это проверка вершин и выборок, а не непрерывный расчёт столкновений по всей поверхности.</p><p>Итоговый Blender-файл повторно открыт: недостающих текстур нет, связанные экземпляры совпадают с экспортом, исходные XML встроены в проект. Подвижные объекты представлены реальными мешами и сохранёнными кривыми анимации. Содержимое проекта, сборки и установленного приложения сверено по SHA-256. Новое превью взято из движка и попало в карту и кампанию.</p><p>Зафиксирован естественный финиш трёх кругов кампании. После последних декоративных изменений отдельно проверен полный круг. Принудительный финиш не применялся. Все сложности и обратное направление не проверены; производительность не измерялась.</p></main></body></html>'''
(out/'index.html').write_text(s);missing=[v for v in re.findall(r'(?:src|href)="([^"]+)"',s) if not v.startswith('http') and not (out/v.replace('%20',' ')).exists()];assert not missing,missing
(out/'manifest.json').write_text(json.dumps({'brokenLocalLinks':missing,'screenshots':len(shots),'files':[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in out.rglob('*') if p.is_file() and p.name!='manifest.json']},indent=2));print('REPORT_READY',out)
