from pathlib import Path
import json,hashlib,shutil,collections
r=Path(__file__).resolve().parent;repo=Path('/Users/motoricallc/Downloads/fluxara-drift');pack=repo/'FLUXARA_TRACK_ASSET_PACK';pf=repo/'FLUXARA_TRACK_ASSET_POOL.json';pool=json.load(open(pf));reg=json.load(open(r/'asset-registration.json'));track='fluxara-summit-run';canon=pack/'blender/FLUXARA_Track_Asset_Library.blend';mod=pack/'models/summit-run-reference-v1';sources=pack/'sources/summit-run-reference-v1'
def info(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
if not (r/'pool-before-summit-run.json').exists():shutil.copy2(pf,r/'pool-before-summit-run.json')
reuse={x['target']:x for x in json.load(open(r/'reuse.json'))};textures=[]
for name,row in reg['textures'].items():
 p=Path(row['packPath']);source=Path(row['source']);alias=source.name;svg=sources/(name+'.svg');authored=svg.is_file() or name=='screenshot.png';variant=reuse.get(alias,reuse.get(name));before=r/'before'/alias;unchanged=before.is_file() and info(before)['sha256']==row['sha256'];tier='authored' if authored else 'adapt' if variant and variant.get('sourceSha256') else 'direct'
 sourcepath=str(sources/'screenshots/preview-ice.png') if name=='screenshot.png' else str(svg) if svg.is_file() else variant['source'] if variant else row['source']
 reason='Actual engine screenshot; technical resize only' if name=='screenshot.png' else 'Uniform native SVG stone color or striped balloon fabric based on Figma 378:49' if authored else variant.get('adaptation','Pooled pixels reused') if variant else 'Unmodified existing pooled or original image; renderer aliases resolved explicitly'
 textures.append({'id':'summit-v1-texture-'+hashlib.sha256(name.encode()).hexdigest()[:12],'displayName':name,'kind':'texture','sourceMap':track,'reuseTier':tier,'canonicalPackPath':str(p),'physicalSourcePath':sourcepath,'file':info(p),'sourceRelationship':variant,'categories':['winter','alpine'],'reason':reason,'uses':[{'trackId':track,'status':'Integrated; final visual acceptance pending'}]})
tmap={q['displayName']:q['id'] for q in textures};materials=[]
for q in reg['materials']:materials.append({**q,'displayName':q['name'],'kind':'material','sourceMap':track,'reuseTier':'adapt','canonicalPackPath':str(canon)+'#Material/'+q['name'],'physicalSourcePath':reg['visualLibrary'],'dependencies':[tmap[n] for n in q['textures']],'categories':['winter','alpine'],'uses':[{'trackId':track,'status':'Integrated'}]})
mmap={q['name']:q['id'] for q in materials};counts=collections.Counter(q['prototype'] for q in reg['nativeSharedInstances']);objects=[]
for q in reg['objects']:
 src=q['sourceModel'];authored=any(w in src for w in ['alpine_snow_column','summit_cascade']);adapt=any(w in src for w in ['summit_snow_fir','alpine_coral_barrier'])
 reason='Surface-conforming cascade ribbon based on reference; existing pooled water material reused' if 'summit_cascade' in src else 'Small snow-capped stone column based on reference; pooled large mesa meshes do not fit this detail budget' if authored else 'Approved winter fir reused; only wind vertex-color channel removed for renderer compatibility; shape/normals/UV/topology retained' if 'summit_snow_fir' in src else 'Pooled coral-white barrier shape and vertex colors retained; palette UV variant' if adapt else 'Existing shared runtime scenery reused unchanged'
 objects.append({**q,'displayName':q['name'],'kind':'visual-object','sourceMap':track,'reuseTier':'authored' if authored else 'adapt' if adapt else 'direct','canonicalPackPath':str(canon)+'#Object/'+q['name'],'physicalSourcePath':reg['visualLibrary'],'file':info(Path(reg['visualLibrary'])),'dependencies':[mmap[n] for n in q['materials']],'reason':reason,'categories':['winter','alpine'],'uses':[{'trackId':track,'instances':counts[q['name']],'status':'Integrated; visual acceptance pending'}]})
for name,kind in [('ancient-summits_track.spm','protected-track-assembly'),('Balloon.spm','animated-decoration'),('iceCube.spm','protected-gameplay-object'),('fallRock.spm','protected-gameplay-object'),('treeMod1_LOD80.spm','protected-tree-collider'),('treeMod1_LOD170.spm','legacy-tree-lod')]:
 p=mod/name;shutil.copy2(r/'candidate'/name,p);objects.append({'id':'summit-v1-model-'+hashlib.sha256(name.encode()).hexdigest()[:12],'displayName':name,'kind':kind,'sourceMap':track,'reuseTier':'adapt' if name in ['Balloon.spm','ancient-summits_track.spm'] else 'direct','canonicalPackPath':str(p),'physicalSourcePath':str(sources/'original-runtime'/name),'file':info(p),'dependencies':[q['id'] for q in materials],'reason':'Original shape, normals, UVs, topology, pivot and animation retained; fabric texture-name variant only' if name=='Balloon.spm' else 'Original positions/normals/topology/physical material assignment retained; UV variant only on snow-cliff buffer 9' if name=='ancient-summits_track.spm' else 'Original model retained byte-for-byte; gameplay/control models are not interchangeable scenery','uses':[{'trackId':track,'status':'Integrated'}]})
for key,values in [('objects',objects),('materials',materials),('textures',textures)]:pool[key]=[q for q in pool[key] if not q['id'].startswith('summit-v1-')]+values
ci=info(canon)
def refresh(v):
 if isinstance(v,dict):
  if v.get('path')==str(canon) and 'sha256' in v:v.update(ci)
  for x in v.values():refresh(x)
 elif isinstance(v,list):
  for x in v:refresh(x)
refresh(pool);pool['physicalPack']['blenderLibrary']=ci;ids=[q['id'] for k in ['objects','materials','textures'] for q in pool[k]];assert len(ids)==len(set(ids));assets=objects+materials+textures
for q in assets:assert Path(q['canonicalPackPath'].split('#')[0]).is_file();assert Path(q['physicalSourcePath'].split('#')[0]).exists();assert all(n in ids for n in q.get('dependencies',[]))
pf.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n');ledger={'trackId':track,'displayName':'Summit Run','campaignPosition':9,'visualTheme':'One winter alpine style','reference':{'fileKey':'Pws4Hw0fwwTmTMf6OJvil8','nodeId':'378:49','local':str(r/'references/figma-ninth.png')},'objects':objects,'materials':materials,'textures':textures,'assets':assets,'finalBlend':reg['finalBlend'],'runtimeStorage':'Shared visible scenery models with coordinates; original track and dynamic gameplay models preserved separately','placements':json.load(open(r/'placements.json')),'preservation':json.load(open(r/'preservation-audit.json')),'approval':'No final user visual acceptance recorded','runtimeValidation':'Full campaign run in progress','report':None};(r.parent.parent/(track+'.asset-ledger.json')).write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n');(r/'pool-audit.json').write_text(json.dumps({'usedAssets':len(assets),'uniquePoolIds':len(ids),'allPhysicalPathsExist':True,'unresolvedDependencies':[],'canonical':ci},indent=2));print('POOL_REGISTERED',len(assets),len(ids))
