from pathlib import Path
import hashlib,json,re,shutil,subprocess
r=Path(__file__).resolve().parent;w=r/'fidelity-v40';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v40';e.mkdir(exist_ok=True);b=json.loads((w/'preservation-verification.json').read_text());n=json.loads((w/'final-blend-verification.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());assert run['naturalFinishObserved']and not n['canonicalPending'];sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
for f in w.glob('*.json'):
 if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
for dest,src in [('fidelity-v40-game-40.png','drive-40s.png'),('fidelity-v40-game-80.png','drive-80s.png'),('fidelity-v40-game-140.png','drive-140s.png'),('fidelity-v40-natural-finish.png','natural-finish.png'),('fidelity-v40-overview.png','smoke-diagnostic-all.png')]:shutil.copy2(w/'screenshots'/src,out/'screenshots'/dest)
section=f'''<section id="fidelity-v40-draft"><h2>Рабочий V40: каменные массивы вместо открытых дальних площадок</h2>
<p>Шесть дальних зелёных листов превращены в закрытые округлые массивы: зелёные вершины, каменные боковины и нижние грани. Каменная фактура прежняя — 39&nbsp;938 байт, без изменения пикселей. У каждого массива сохранены прежние крайние размеры, у всей модели — действующие и записанные границы, начало координат и оси. Дальняя геометрия упрощена: модель 26&nbsp;319 байт и 999 треугольников вместо 58&nbsp;857 байт и 2&nbsp;710 треугольников. Все 615 ближних треугольников сохранены с прежними вершинами, UV, нормалями, цветами и материалом. <a href="screenshots/fidelity-v39-overview.png">Обзор до</a> · <a href="screenshots/fidelity-v40-overview.png">обзор после</a>, одинаковая камера движка.</p>
<p>82 уже размещённых зелёных шапки стали объёмнее за счёт масштаба декоративных экземпляров. Их общая модель не менялась; нижний стык с камнем остался на прежнем месте, ошибка высоты не больше {b['grassStoneMaximumSeamHeightErrorMeters']:.2e}&nbsp;м. 160 связанных деревьев, кустов и холмов пересажены по новой высоте. Ещё 84 дальних экземпляра проверены по фактическим поверхностям: 8 сдвинуты внутрь округлого контура, чтобы всё основание опиралось на землю. Новых экземпляров в этом проходе нет.</p>
<p>Модель дальнего ландшафта вместе с двумя используемыми изображениями весит {b['newLogicalFieldWeightBytes']:,} байт против {b['sourceLogicalFieldWeightBytes']:,} исходных: <b>+{b['logicalModelPlusUsedTexturesIncreasePercent']:.2f}%</b>, в пределах +20%. Большой каменный рисунок уже присутствует в общем пуле и игре; новое растровое изображение не создавалось. Новый общий экспорт с XML — {b['newSharedRuntimeAllFilesBytes']:,} байт. Все файлы карты, включая неиспользуемые, и принятая история общих ресурсов суммарно занимают <b>{b['allCandidateAndAcceptedHistoryBytes']:,} байт</b>: на {b['savingVsV1Bytes']:,} ({b['savingVsV1Bytes']/b['v1Bytes']*100:.2f}%) меньше V1. Относительно рабочего V39 добавлено {b['deltaVsV39Bytes']:,} байт; это не уменьшение относительно V39. Размер новой сборки приложения не измерен.</p>
<p>Полотно и главный SPM полностью совпали с V39. track.xml, quads/graph, сценарий и игровые точки совпали с V1. Прежние физические оболочки сохранены; новые массы находятся минимум в {b['minimumFarFieldRoadAABBLowerBoundMeters']:.2f}&nbsp;м от дорожных треугольников по нижней оценке. Повторены {b['grassAndLinkedPlantAndBackgroundClearanceChecks']} проверки фактической геометрии зелёных шапок и растительности. Сохраняется физический смысл решёток, бустеров и гравийного участка.</p>
<p>Blender сохранён и повторно открыт: {n['meshObjects']} меш-объекта, {n['nativePrototypeCount']} общих прототипов, {n['nativeMaterialDefinitionCount']} определений материалов, {n['nativeSharedParts']} общих частей. Геометрия и атрибуты 821 прежнего меша не менялись; только один существующий экземпляр дальнего ландшафта переключён на новый общий прототип. 326 декоративных матриц изменены намеренно для объёма травы и посадки растений; остальные 496 совпали с V39. В каноническом пуле сохранены прежние модели, 381 изображение и свечение окон домов. Новых определений материалов и пикселей нет; {audit['uniquePoolIds']} уникальных ID проверены по реальным файлам, хешам и зависимостям.</p>
<p>Просмотрены четыре настоящих игровых кадра и <a href="screenshots/fidelity-v40-natural-finish.png">естественный финиш #1</a> полного круга Time Trial. Скриншоты не ретушировались, принудительная победа не использовалась. Это один режим с одним участником. Небезопасное поведение AI на рампе ранее наблюдалось в V1; все регрессии проезда, обратный режим и производительность этим заездом не исключаются.</p>
<p class="note">Рабочий вариант, полное соответствие референсу ещё не подтверждено. Основная карта, пользовательский итоговый .blend и превью всё ещё V1. Окружение стало объёмнее, но замок, ограждения, вулкан и атмосфера ещё требуют общей визуальной проверки по референсу. Карты 6–9 и их отчёты в этом проходе не изменялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v40/native/Volcano%20Remake.blend">Blender V40</a> · <a href="evidence/fidelity-v40/preservation-verification.json">Геометрия и вес</a> · <a href="evidence/fidelity-v40/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v40/runtime-validation.json">Заезд</a> · <a href="evidence/fidelity-v40/pool-audit.json">Общий пул</a> · <a href="screenshots/fidelity-v40-game-80.png">Кадр 80 секунд</a></p>
<figure><a href="screenshots/fidelity-v40-game-40.png"><img src="screenshots/fidelity-v40-game-40.png" alt="Поворот у каменных скал V40"></a><figcaption>Реальная камера гонщика. Каменная фактура и игровая решётка сохранены.</figcaption></figure>
<figure><a href="screenshots/fidelity-v40-game-140.png"><img src="screenshots/fidelity-v40-game-140.png" alt="Нижний участок и дальние каменные боковины V40"></a><figcaption>Нижний участок с прежним полотном; дальние зелёные площадки получили закрытые каменные боковины.</figcaption></figure></section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v40-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v39-draft">',section+'<section id="fidelity-v39-draft">',1);s=re.sub(r'<div class="tags">.*?</div>','<div class="tags"><span>Рабочий V40</span><span>Вес −24.25% к V1</span><span>522 общих части</span></div>',s,count=1,flags=re.S);s=s.replace('fidelity-v39/native/Volcano%20Remake.blend">Рабочий Blender V39','fidelity-v40/native/Volcano%20Remake.blend">Рабочий Blender V40',1);page.write_text(s);manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':sha(f)}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
def clone(src,dst):
 dst=Path(dst)
 if dst.exists():
  if Path(src).read_bytes()==dst.read_bytes():return str(dst)
  dst.unlink()
 subprocess.run(['/bin/cp','-c',str(src),str(dst)],check=True);return str(dst)
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dst in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v40/report']:shutil.copytree(out,dst,dirs_exist_ok=True,copy_function=clone)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v40'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';a=json.loads(progress.read_text());a['maps']['10'].update({'status':'V40 source/native/canonical/pool/naturalTT#1 verified. SixclosedStoneGreenfarvolumes,615neartri exact.82grass copies thicker,244plants grounded,8inset.5827632B(-24.25%V1,+26625BV39). Fieldmodel+usedtextures66578B(+12.50%). Overallref incomplete, production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateAllFilesBytes'],'candidateBytesIncludingNewSharedRuntime':b['allCandidateAndAcceptedHistoryBytes'],'candidateSavedBytesAgainstPrevious':b['savingVsV1Bytes'],'lastFullLapVerifiedCandidate':'V40','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':51,'candidateNativeSharedParts':522,'fullyAccepted':False});a['goalComplete']=False;progress.write_text(json.dumps(a,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';a=json.loads(plan.read_text());a['baseCandidate']='V40';a['status']='V40 terrain-volume batch source/native/canonical/pool/fullnaturalTT#1 verified.5827632B inclallacceptedhistory. No newpixels/materialdefinitions. Main/final/preview V1; completegoal/refacceptance unfinished.';a['workingEvidence']['V40']='Sixoldfar2095tri sheets replaced by sixclosed64tri green/stone bodies, samecomponentbbox/wholeactiveandheaderbounds/origin/axes.615near triangles attributes exact; newField999tri908vertices26319B+321BgrayMoss+39938Stone=66578B(+12.50% source).82samegrassinstances scaled1.75x aboutoldseam,160linkedplants affinegrounded;84farplants actual9pointfootprints,8XZinsets. Roadgeometry/control/physics/mainallotherfiles exact39. Native823meshes51protos99mats522parts,821oldmeshattrs/496othermatrices exact39,326posesintentionallychanged. Canonical381oldimages/houseemission retained; pool4184uniqueIDs new1native+1runtime. NaturalTT#1, game40/80/140/190 andsamecameraoverview inspected.';a['nextVisibleTarget']='Finish reference composition and integrate map10 instead of indefinite isolated checkpoints: retain current stone pixels and source driving/control geometry. Prioritize red/white bend-side barrier appearance without changing protectedroad/physicalgeometry, volcanic plume warmth/torch scale/sky composition, castle gate material proportions and local lava visualpattern. Validate coherent finalgameviews then replace production10, solefinalblend andpreview; finish3/4pendingnative/game/poolintegration,map7full11laps,then userrequested1-10coordinateenrichment andpreviews. Do not markgoalcomplete whilethese remain.';a['diskHandling']='V35generatedreport184identicalfiles replaced atomically with APFS COW clones, retaining content/path/metadata, reclaimed~464MB. Canonicalbackup andnewreportarchives use COW; originals preserved.';plan.write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n');print('V40_REPORT_SAVED',len(m['files']),flush=True)
