from pathlib import Path
import json,shutil,html,hashlib,re
from PIL import Image,ImageStat
r=Path(__file__).resolve().parent;out=r.parent/'fluxara-user-motorsport-land-final/report'
for sub in ['screenshots','references','evidence']:(out/sub).mkdir(parents=True,exist_ok=True)
a=json.load(open(r/'preservation-audit.json'));d=json.load(open(r/'delivery-verification.json'));layout=json.load(open(r/'layout-summary.json'))['counts'];MB=lambda v:f'{v/1e6:.2f}'.replace('.',',')
def valid(p):
 if not p.exists():return False
 im=Image.open(p).convert('RGB');w,h=im.size;return max(ImageStat.Stat(im.crop((w*.15,h*.15,w*.85,h*.85))).stddev)>6
def fig(src,title,note=''):return f'<figure><a href="{src}"><img src="{src}" alt="{html.escape(title)}" loading="lazy"></a><figcaption><strong>{title}</strong><span>{note}</span></figcaption></figure>'
shutil.copy2(r/'references/figma-eighth.png',out/'references/reference.png');shots=[]
for name,title,note in [('final-campaign-20s.png','Гоночное окружение','Кадр события кампании Lap Trial, итоговые ресурсы.'),('final-campaign-35s.png','Поворот и зелень','Игровой кадр; знаки обращены к приближающемуся потоку.'),('final-campaign-90s.png','Завершение события','Естественное завершение режима по его правилам. Принудительный финиш не применялся.'),('final-normal-lap-95s.png','Проверка полного круга','Обычная гонка с одним кругом; это отдельная проверка проезда.'),('preview-start.png','Стартовая зона','Камера осмотра в игровом движке, без дорисовки. Используется как новое превью карты.'),('preview-stands.png','Трибуны','Камера осмотра; исходные конструкции сохранены.')]:
 p=r/'screenshots'/name
 if valid(p):shutil.copy2(p,out/'screenshots'/name);shots.append((name,title,note))
for n in ['preservation-audit.json','delivery-verification.json','final-blend-verification.json','layout-verification.json','arrow-verification.json','pool-audit.json','final-campaign-capture.json','final-normal-lap-capture.json','final-section-captures.json','runtime-validation.json','preview-update.json','campaign-preview-verification.json']:
 if (r/n).exists():shutil.copy2(r/n,out/'evidence'/n)
style=(r.parent/'spell-lab-rework/report-style.css').read_text()
s=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Motorsport Land — отчёт</title><style>{style}</style></head><body><main><div class="label">FLUXARA DRIFT · КАРТА 08 · 01.10.2026</div><h1>Motorsport Land</h1><p class="lead">Единый стиль гоночного фестиваля: округлые деревья, цветные шины, коралловые ограждения, трибуны со стилизованными зрителями, флажки и воздушные шары. Дорога и игровые данные сохранены.</p><div class="tags"><span>Вес −{abs(a['byteChangePercent']):.2f}%</span><span>Треугольники +{a['triangleChangePercent']:.2f}%</span><span>{a['newSharedPlacementCount']} размещений по координатам</span></div><p><a href="../Motorsport%20Land.blend">Изменённый Blender-проект</a> · <a href="evidence/preservation-audit.json">Геометрия и бюджет</a> · <a href="evidence/delivery-verification.json">Проверка ресурсов</a></p><h2>Референс</h2>{fig('references/reference.png','Figma 390:124','Гоночный фестиваль, округлые кроны, синее небо, зрители и цветные шины. Стрелки на стартовой ферме из референса не перенесены.')}<p><a href="https://www.figma.com/design/Pws4Hw0fwwTmTMf6OJvil8/Fluxara-drift?node-id=390-124">Референс в Figma</a></p><table><tr><th>Элемент</th><th>Изменение</th></tr><tr><td>Зелень</td><td>{layout['tree']} деревьев, {layout['bush']} кустов, {layout['detail']} цветочных и травяных деталей. Общие модели шестой карты переиспользованы.</td></tr><tr><td>Фон</td><td>{layout['hill']} общих холмов, {layout['balloon']} воздушных шара, {layout['pennants']} гирлянд флажков.</td></tr><tr><td>Трибуны и окружение</td><td>Исходные конструкции сохранены. Фотографические зрители и лист рекламы заменены компактными авторскими векторными атласами.</td></tr><tr><td>Направление</td><td>{layout['turn']} знаков только у поворотов. На ферме и рекламных щитах нет направляющих стрелок.</td></tr></table><p class="note">Окончательное визуальное согласование не записано. Игровой свет проще иллюстрации; зрители на трибунах остаются текстурными плоскостями. Это адаптация референса к исходной трассе, не точная копия изображения.</p><h2>Игровые кадры</h2>'''
for name,title,note in shots:s+=fig('screenshots/'+name,title,note)
s+=f'''<h2>Вес</h2><table><tr><th>Измерение</th><th>Результат</th></tr><tr><td>Исходная папка карты</td><td>{MB(a['originalBytes'])} МБ</td></tr><tr><td>Текущая папка карты</td><td>{MB(a['trackFolderBytes'])} МБ</td></tr><tr><td>Новые общие ресурсы</td><td>{a['newSharedBytes']:,} байт; модель шара использует уже существующую палитру</td></tr><tr><td>Карта вместе со всеми новыми общими ресурсами</td><td>{MB(a['trackAndNewSharedBytes'])} МБ, уменьшение на {MB(a['originalBytes']-a['trackAndNewSharedBytes'])} МБ</td></tr><tr><td>Треугольники с каждым размещением</td><td>{a['originalTriangles']:,} → {a['newTriangles']:,}; +{a['triangleChangePercent']:.2f}%, в пределах ±20%</td></tr><tr><td>Распакованное приложение</td><td>{MB(d['live']['appBytes'])} МБ, Debug iOS Simulator. Это не размер IPA или скачивания.</td></tr></table><p>Новые экземпляры используют реальные игровые библиотеки и координаты. Копия меша для каждого дерева или куста в карту не записана. Старые встроенные конструкции этой трассы ещё остаются в основном меше; общий этап их переноса в пул предусмотрен после готовности всех десяти карт. Музыка сохранена.</p><h2>Проверки</h2><p>Вершины, нормали и индексы всех сохранённых буферов сверены с исходником. UV дороги и бордюров также исходные. track.xml, graph.xml, quads.xml, игровые предметы, стартовые параметры и контрольные линии сохранены. Физические свойства поверхностей совпадают с исходными. Изменены текстуры декора и грунта; удалены старые декоративные плоскости леса, дополнительные плакаты-зрители и старые знаки.</p><p>Вершины всех новых общих моделей проверены в игровых координатах: проекция на полотно дороги не обнаружена. При размещении дополнительно проверялись центр и периметр объектов. Итоговый Blender-файл повторно открыт, недостающих текстур нет, связанные экземпляры совпадают с экспортом. Ресурсы проекта, сборки и установленного приложения сверены по SHA-256.</p><p>Для Lap Trial зафиксировано естественное завершение события. Отдельная обычная гонка проверяет полный круг. Осмотр камерой дополняет игровые кадры, но не заменяет прохождение. Все сложности и обратное направление не проверены, замер производительности не выполнялся.</p><p>Превью карты взято из игрового движка. Превью кампании собрано из него штатным скриптом упаковки.</p></main></body></html>'''
(out/'index.html').write_text(s);missing=[v for v in re.findall(r'(?:src|href)="([^"]+)"',s) if not v.startswith('http') and not (out/v.replace('%20',' ')).exists()];assert not missing,missing
(out/'manifest.json').write_text(json.dumps({'brokenLocalLinks':missing,'screenshots':len(shots),'files':[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in out.rglob('*') if p.is_file() and p.name!='manifest.json']},indent=2));print('REPORT_READY',out)
