from pathlib import Path
import json,html,shutil,re,hashlib
r=Path(__file__).resolve().parent;out=r.parent/'fluxara-canyon-final/report';out.mkdir(exist_ok=True)
for sub in ['screenshots','evidence']:(out/sub).mkdir(exist_ok=True)
a=json.load(open(r/'canyon-extraction.json'));d=json.load(open(r/'delivery-verification.json'));MB=lambda n:f'{n/1e6:.2f}'.replace('.',',');shots=['canyon-before-40s.png','canyon-enriched-12s.png','canyon-enriched-40s.png','canyon-enriched-120s.png','preview-canyon-start.png']
for n in shots:shutil.copy2(r/'screenshots'/n,out/'screenshots'/n)
for n in ['canyon-extraction.json','canyon-enrichment.json','enrichment-layout-verification.json','delivery-verification.json','runtime-validation.json','preview-update.json','campaign-preview-verification.json','canonical-bindings-verification.json','pool-audit.json']:shutil.copy2(r/n,out/'evidence'/n)
style=(r.parent/'spell-lab-rework/report-style.css').read_text();s=f'<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Fluxara Canyon — общий пул</title><style>{style}</style></head><body><main><div class="label">КАРТА 1 · ОБЩИЙ ПУЛ · 01.10.2026</div><h1>Fluxara Canyon</h1><p class="lead">295 запечённых экземпляров перенесены в 47 общих игровых моделей. Прежний каньонный стиль, дома, скалы, вода и окружение сохранены. Пять дополнительных кустов используют существующую общую библиотеку.</p><p><a href="../Fluxara%20Canyon.blend">Изменённый Blender-проект</a> · <a href="evidence/delivery-verification.json">Проверки</a></p><table><tr><th>Измерение</th><th>Результат</th></tr><tr><td>Папка до переноса</td><td>{MB(a["sourceBytes"])} МБ</td></tr><tr><td>Текущая карта плюс все новые общие модели</td><td>{MB(a["totalCandidateBytes"])} МБ; уменьшение на {MB(a["sourceBytes"]-a["totalCandidateBytes"])} МБ</td></tr><tr><td>Новые общие модели</td><td>{a["allNewSharedBytes"]:,} байт</td></tr><tr><td>Текстура общих моделей</td><td>Исходный атлас уже находился в установленном приложении; повторно проверен по SHA-256, дополнительной копии нет</td></tr><tr><td>Геометрия окружения с экземплярами</td><td>{a["oldSceneryTriangles"]:,} → {a["newLogicalSceneryTriangles"]:,}; добавлены только 900 треугольников пяти кустов</td></tr><tr><td>Распакованное приложение</td><td>{MB(d["live"]["appBytesAfter"])} МБ, Debug iOS Simulator</td></tr></table><p>До замены превью перенос геометрии и пять кустов уменьшили установленное приложение на 632 617 байт. Остальное уменьшение связано с новым превью. Размер IPA и скачивания из магазина здесь не измерялся.</p><h2>Скриншоты</h2>'
for n in shots:s+=f'<figure><a href="screenshots/{n}"><img src="screenshots/{n}" alt="{n}" loading="lazy"></a><figcaption>{n}</figcaption></figure>'
s+='<h2>Сохранность</h2><p>Дорожный меш, маршрут, контрольные линии, стартовые и игровые точки, музыка и остальные модели совпадают с исходными файлами. Первоначальные узлы сцены и физические материалы сохранены. В оставшемся меше окружения все записи вершин и порядок треугольников сохранены побайтово.</p><p>У перенесённых экземпляров локальные позиции восстановлены обратным преобразованием. Проверены топология, UV, цвета и соответствие мировой геометрии с погрешностью менее 0,001 м; у упакованных нормалей остаётся малая погрешность квантования. Новые кусты опираются на исходные зелёные поверхности: по 13 выборок на каждый. 1100 вершин новых моделей проверены по дорожному коридору; перекрытия не найдены. Это проверка вершин и выборок, а не непрерывная симуляция столкновений.</p><p>Blender-файл повторно открыт: недостающих текстур нет, 326 частей общих экземпляров совпадают с экспортными матрицами. После регистрации привязки материалов и объектов карт 6–10 также повторно проверены. Все используемые ресурсы существуют в физическом общем пакете.</p><h2>Проверка игры</h2><p>Исходник, версия после переноса и итог с пятью кустами прошли обычную гонку на один круг до естественного финиша. Принудительная победа не использовалась. Обратное направление, четыре круга события кампании и производительность не проверены. Превью — свежая камера осмотра в игровом движке без HUD; применены только центральная обрезка и масштабирование.</p><p class="note">Это результат первого этапа переноса первой карты. Общая работа по наполнению и переиспользованию всех карт 1–10 продолжается; визуальное согласование этой версии не записано.</p></main></body></html>'
(out/'index.html').write_text(s);missing=[v for v in re.findall(r'(?:src|href)="([^"]+)"',s) if not v.startswith('http') and not (out/v.replace('%20',' ')).exists()];assert not missing,missing;(out/'manifest.json').write_text(json.dumps({'brokenLocalLinks':missing,'screenshots':len(shots),'files':[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in out.rglob('*') if p.is_file() and p.name!='manifest.json']},indent=2));print('REPORT_READY',out)
