from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v15';repo=Path('/Users/motoricallc/Downloads/fluxara-drift');pack=repo/'FLUXARA_TRACK_ASSET_PACK';sources=pack/'sources/volcano-remake-fidelity-v15';sources.mkdir(exist_ok=True);mod=pack/'models/volcano-remake-fidelity-v15';canon=pack/'blender/FLUXARA_Track_Asset_Library.blend';pf=repo/'FLUXARA_TRACK_ASSET_POOL.json';a=json.loads((w/'asset-registration.json').read_text());pool=json.loads(pf.read_text());ledger=json.loads((r/'fidelity-v14/candidate-asset-ledger.json').read_text());proof=json.loads((w/'castle-atmosphere-changes.json').read_text());assert json.loads((w/'canonical-registration.json').read_text())['newObjects']==7;assert json.loads((w/'final-blend-verification.json').read_text())['sharedCastleBodyUsedByBothVariants'];assert(w/'canonical-bindings-verification.json').is_file();assert(w/'runtime-validation.json').is_file()
if not(w/'pool-before-v15.json').exists():shutil.copy2(pf,w/'pool-before-v15.json')
def info(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for name in ['build_fidelity_v15_castle_atmosphere.py','fix_fidelity_v15_library_layout.py','optimize_fidelity_v15_gate_roof.py','update_fidelity_v15_canonical_gate.py','verify_fidelity_v15_preservation.py','finalize_fidelity_v15.py','verify_fidelity_v15_native.py','register_fidelity_v15_canonical.py','verify_fidelity_v15_canonical.py','capture_fidelity_v15_drive.py','capture_fidelity_v15_inspection.py',Path(__file__).name]:shutil.copy2(r/name,sources/name)
for p in w.glob('*.json'):
 if not p.name.startswith('pool-before'):shutil.copy2(p,sources/p.name)
for folder in ['candidate','native','screenshots','iterations','original-component']:shutil.copytree(w/folder,sources/folder,dirs_exist_ok=True)
for key in ['roofedLibrary','battlementLibrary','sharedBodyLibrary','newGateRoofLibrary']:
 lib=Path(proof[key]);shutil.copytree(lib,sources/'runtime-libraries'/lib.name,dirs_exist_ok=True)
usage=[{'trackId':'fluxara-user-volcano-remake','candidate':'V15','status':'Sixteen pooled masonry tower placements, shared gate canopy and reshaped smoke. Source road and collision unchanged; candidate not integrated.'}];base={'sourceMap':'fluxara-user-volcano-remake','categories':['castle','smoke','lava'],'uses':usage};texture_name='fluxara_castle_brick_v15.jpg';tid='volcano-fidelity-v15-brick-texture-alias';oldtex=next(q for q in ledger['textures']if q.get('displayName')=='castelwall.jpg');texture=a['textures'][texture_name]
newtex={**base,'id':tid,'displayName':texture_name,'kind':'texture','reuseTier':'direct','canonicalPackPath':texture['packPath'],'physicalSourcePath':oldtex['canonicalPackPath'],'file':info(Path(texture['packPath'])),'dependencies':[oldtex['id']],'runtimePackagedPath':texture['source'],'runtimeIntegrated':False,'reason':'Byte-identical existing castle masonry image, one global runtime alias; old local candidate duplicate removed. Shared alias bytes included in map budget.'};newmats=[]
for q in a['newMaterialVariants']:newmats.append({**base,**q,'displayName':q['name'],'kind':'material','reuseTier':'adapt','canonicalPackPath':str(canon)+'#Material/'+q['name'],'physicalSourcePath':a['visualLibrary'],'dependencies':([tid]if q['textures']else[])+([q['sourceMaterialId']]if q.get('sourceMaterialId')else[]),'reason':q['adaptation']})
matids={q.get('name',q.get('displayName')):q['id']for q in ledger['materials']+newmats};newobj=[]
for q in a['newPrototypes']:
 deps=[matids[n]for n in q['materials']];newobj.append({**base,**q,'displayName':q['name'],'kind':'visual-object','reuseTier':'adapt','canonicalPackPath':str(canon)+'#Object/'+q['name'],'physicalSourcePath':a['visualLibrary'],'file':info(Path(a['visualLibrary'])),'dependencies':deps,'reason':q['role']});source=Path(q['sourceModel']);stored=mod/source.name;assert stored.read_bytes()==source.read_bytes();newobj.append({**base,'id':q['id']+'-runtime','displayName':source.name,'kind':'runtime-model','reuseTier':'adapt','canonicalPackPath':str(stored),'physicalSourcePath':str(source),'file':info(stored),'dependencies':deps,'runtimePackagedPath':str(source),'runtimeIntegrated':False,'reason':'Single exported source file. Shared castle body is physically stored in one nested library; cap files each stored once. Smoke keeps original map object bounds and transforms.'})
stored=mod/'volcano_track.spm';stored.write_bytes((w/'candidate/volcano_track.spm').read_bytes());newobj.append({**base,'id':'volcano-fidelity-v15-runtime-volcano-track','displayName':stored.name,'kind':'map-runtime-model','reuseTier':'adapt','canonicalPackPath':str(stored),'physicalSourcePath':str(w/'candidate/volcano_track.spm'),'file':info(stored),'dependencies':[tid],'reason':'Retained main road and decorative surfaces; original 14 tower clusters moved to exact map-only collision proxies, shared visible towers placed by coordinates.'})
for key,items in {'objects':newobj,'materials':newmats,'textures':[newtex]}.items():pool[key]=[q for q in pool[key]if not q['id'].startswith('volcano-fidelity-v15-')]+items;ledger[key]=[q for q in ledger[key]if not q['id'].startswith('volcano-fidelity-v15-')]+items
ci=info(canon)
def refresh(v):
 if isinstance(v,dict):
  if v.get('path')==str(canon)and'sha256'in v:v.update(ci)
  for x in v.values():refresh(x)
 elif isinstance(v,list):
  for x in v:refresh(x)
refresh(pool);pool['physicalPack']['blenderLibrary']=ci;pool['updated']=datetime.now(timezone.utc).isoformat();pool['assets']=pool['objects']+pool['materials']+pool['textures'];ids=[q['id']for key in ['objects','materials','textures']for q in pool[key]];assert len(ids)==len(set(ids));pres=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());ledger.update({'candidate':'V15 pooled brick castles, red roofs and dense smoke; original stone retained','status':'Current isolated candidate. Course and exact collision preserved, upper weight gates passed. Native, canonical and simulator evidence recorded; reference fidelity unfinished.','finalBlend':a['finalBlend'],'nativeSharedParts':len(a['nativeSharedInstances']),'preservation':pres,'budget':pres,'runtimeValidation':run,'deltaAssetCounts':{'objects':len(newobj),'materials':len(newmats),'textures':1},'productionIntegrated':False,'newImagePixels':False});ledger['assets']=ledger['objects']+ledger['materials']+ledger['textures'];ledger['mapRuntimeFiles']=[info(p)for p in(sources/'candidate').iterdir()if p.is_file()]
for q in proof['additionalTowerPlacements']:ledger['mapOnlyProtectedCollision'].append({'model':q['collider'],'sourceTowerTriangles':q['originalCollisionTriangles'],'shape':'exact','interchangeableScenery':False})
for q in ledger['assets']:
 assert q['id']in ids;assert Path(q['canonicalPackPath'].split('#')[0]).is_file(),q['id'];assert Path(q['physicalSourcePath'].split('#')[0]).exists(),q['id'];assert all(dep in ids for dep in q.get('dependencies',[])),q['id']
 if q.get('file'):assert info(Path(q['file']['path']))==q['file'],q['id']
audit={'newObjects':len(newobj),'newNativePrototypes':7,'newMaterials':len(newmats),'newTextureAliases':1,'newImagePixels':False,'allPhysicalPathsAndFileHashesMatch':True,'uniquePoolIds':len(ids),'totalLedgerAssetsIncludingHistoricalSources':len(ledger['assets']),'unresolvedDependencies':[],'canonical':ci,'nativeSharedParts':len(a['nativeSharedInstances']),'productionIntegrated':False};pf.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n');(w/'candidate-asset-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n');(w/'pool-audit.json').write_text(json.dumps(audit,indent=2))
for name in ['candidate-asset-ledger.json','pool-audit.json']:shutil.copy2(w/name,sources/name)
print('V15_POOL_CASTLE_AND_SMOKE_REGISTERED',audit,flush=True)
