from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v35';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v35';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text());assert run['naturalFinishObserved']and native['newFloorRuntimeTrianglePositionsMatch']==1686
for f in w.glob('*.json'):
 if not f.name.startswith(('pool-before','ski-dash-ledger-before')):shutil.copy2(f,e/f.name)
for version,names in [('v33',['mass-replacement-preflight.json','visual-rejection.json']),('v34',['valley-preflight.json','preservation-verification.json','cliff-clearance-verification.json','castle-supports.json','visual-rejection.json'])]:
 dest=out/'evidence'/('fidelity-'+version+'-experiment');dest.mkdir(exist_ok=True)
 for name in names:shutil.copy2(r/('fidelity-'+version)/name,dest/name)
figures=[]
for second,caption in [(40,'Проезд среди каменных колонн. Каменная фактура сохранена; пары общей модели стыкуются по 16 точкам. Кромки травы пока тонкие, а часть старой листвы выглядит подвешенной — это остаётся в работе.'),(140,'Спуск к нижнему повороту. Под трассой теперь лава вместо пустот. Виден оставшийся исходный фрагмент с грязевыми лужами: его окружение ещё нужно привести к общему стилю, сохранив игровое поведение.')]:
 name=f'fidelity-v35-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name);figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V35"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
for name,src in [('fidelity-v35-overview.png',w/'screenshots/smoke-diagnostic-all.png'),('fidelity-v35-natural-finish.png',w/'screenshots/natural-finish.png'),('fidelity-v35-ramp-80.png',w/'screenshots/drive-80s.png'),('fidelity-v34-rejected-gap.png',r/'fidelity-v34/screenshots/drive-40s.png')]:shutil.copy2(src,out/'screenshots'/name)
section=f'''<section id="fidelity-v35-draft"><h2>Последняя доработка — V35: каменные колонны и нижний ландшафт</h2>
<p>По замечанию «С текстурой камня было лучше» каменная фактура сохранена: 39&nbsp;938 байт, SHA-256 6c765884a7846501355a429f3548d2df78698798a97a0318aefe358d0bdafdfd. Новых файлов моделей или текстур для дополнительных экземпляров не потребовалось. Нижнее поле лавы и 15 опор башен используют уже существующие модели по координатам.</p>
<p>Из видимой старой массы убраны два компонента, 1&nbsp;508 треугольников; их точная геометрия сохранена в отдельной невидимой коллизии. Независимо проверено равенство исходных 2&nbsp;210 треугольников объединению оставшихся 702 видимых и 1&nbsp;508 невидимых. Остальные буферы основного меша, материал, UV и его общие габариты совпали с V32. Полотно, игровые точки и линии, quads/graph, сценарий и track.xml сохранены. Коллизии не оценивались только по наличию старого V26 файла: тот содержит 64 треугольника центральной опоры и не покрывает удалённую большую массу.</p>
<p>Первая попытка V33 оставила большие пустоты под дорогой и отклонена. В V34 лава размещена на высоте −60 м, на {b['lavaFloorRoadVerticalMarginMeters']:.3f} м ниже самого низкого защищённого дорожного фрагмента. Основания 82 скал удлинены вниз с сохранением прежней верхней точки, XZ и направления. Все 16 исходных башен сохранены; под 15 добавлена опора. Под оставшейся башней опора пересекала бы дорогу, поэтому этот экземпляр не добавлен.</p>
<p>Игровой кадр V34 выявил <a href="screenshots/fidelity-v34-rejected-gap.png">щели на старых небольших скалах</a>. Этот вариант не принят как визуально готовый. V35 переводит 58 старых групп на уже проверенную пару камня и травы V32: общий контур из 16 точек, перекрытие 0.08 м. Для этих 116 частей независимо проверены 25&nbsp;056 треугольников относительно 2&nbsp;032 дорожных; минимальное расстояние — {b['minimumOlderSeamPartRoadMarginMeters']:.3f} м. 24 крупные группы сохранены. Локальные размеры, центр и оси источников не менялись; масштабы и высоты добавленных декоративных экземпляров изменены намеренно. Две общие модели с используемой каменной текстурой по-прежнему весят 46&nbsp;337 байт; роста веса этого набора нет.</p>
<p>Итог рабочего варианта с новыми общими ресурсами и сохранёнными принятыми ранее вариантами — {b['candidateIncludingNewSharedBytes']:,} байт против {b['v1Bytes']:,} у интегрированного V1: экономия {b['savingBytesVsV1']:,} байт ({b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%). В подсчёт включены новый файл коллизии, все файлы карты и новые общие модели/текстуры. Дополнительный файл лавового поля не создаётся на каждое размещение. Размер новой сборки приложения не измерялся.</p>
<p>Blender проверен отдельно: 584 остальные сетки точно совпали с V32 по геометрии, UV, нормалям, цветам и материалам; 561 остальные матрицы также совпали. Наборы этих объектов различаются. Проверены 702 видимые и 1&nbsp;508 невидимые треугольников стены, а также 1&nbsp;686 треугольников трёх частей лавового поля. Его части в исходном Blender идут в обратном порядке относительно игровых буферов; соответствие исправлено и проверено, геометрия не менялась. Ведомость содержит 43 прототипа, 94 определения материалов и 430 общих размещённых частей. В канонический пул добавлены три уже существовавшие части лавы; прежние материалы, изображения и свечение окон зимних домов проверены. Пул: {audit['uniquePoolIds']} уникальных ID, ведомость карты: {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов; реальные пути, хеши и зависимости проверены.</p>
<p>Полный круг Time Trial естественно завершился <a href="screenshots/fidelity-v35-natural-finish.png">результатом #1</a>. Просмотрены игровые кадры 40, <a href="screenshots/fidelity-v35-ramp-80.png">80</a>, 140 и 190 секунд, а также <a href="screenshots/fidelity-v35-overview.png">отдельный обзор движка</a>. Скриншоты сохранены без ретуши. Временные карты и ресурсы убраны из приложения; исходные деревья, холмы и факелы не менялись. Опасное прохождение исходной рампы ранее наблюдалось и в V1; все возможные регрессии не исключены.</p>
<p class="note">Карта ещё не готова по референсу: тонкие травяные кромки, старая подвешенная листва и грязевые площадки, плоский дальний фон, крыши и атмосфера требуют доработки. Основная карта, пользовательский итоговый .blend и превью пока V1. Новая сборка, производительность, обратный режим и вся кампания не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v35/native/Volcano%20Remake.blend">Blender V35</a> · <a href="evidence/fidelity-v35/preservation-verification.json">Полотно и вес</a> · <a href="evidence/fidelity-v35/final-blend-verification.json">Blender</a> · <a href="evidence/fidelity-v35/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v35/pool-audit.json">Пул</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v35-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V32','Предыдущая доработка — V32');s=s.replace('<section id="fidelity-v32-draft">',section+'<section id="fidelity-v32-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v35/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v35'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V35 source/native/canonical/pool and natural full lap#1 checked;82 matchedcliff groups,15castle supports and reused lava valley by coordinates. Source stone pixels and road/control geometry retained. V33 coverage andV34old-rim variants rejected. Thin grass/old foliage/mud areas/castle roofing/sky fidelity unfinished; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V35','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateRegisteredNativePrototypes':43,'candidateNativeSharedParts':430,'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V35';data.pop('inProgressCandidate',None);data['status']='V35 source/native/canonical/pool and natural full lap#1 terminal verified. Source stone texture preserved.82matchedcliff groups,15castle support instances and existing Lavafield lower valley replace voids, original1508wallphysics exact. V33coverage andV34oldrim experiments rejected. Overallreferencefidelity/finalintegration notready: thin grass edges, originalfloating foliage/mud patches, distantterrain, castle roofs/sky/plume.';data['workingEvidence']['V35']='Terminal verified:58older groups reuse existingV32sealed pair, max1.44e-6m worldXZerror/.08m overlap,116parts min1.2155mroad clearance;82bodyfeet preservetopanchor,15supports min.63189m, floor16.137mbelowroad. Native584othergeometry/561othermatrices exactV32,43protos94mats430parts. Native lava-part buffer order corrected withoutgeometrychange. Pooledphysicalobjects/materials/sourceSPM hashes verified, no newSPM/textures payload. Natural#1,6,672,491B(-13.27% vsV1), fullreferencefidelity incomplete.';data['nextVisibleTarget']='Fix remaining grass edge silhouette and original floating foliage/mud-patch support around preserved course, then castle roofs and blue/gold sky/diagonal warm plume. Keep current stone pixels and exact original road/physics/control data. Inspect whole gameplay composition before integration, previews, and enrichment1-10.';plan.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('V35_REPORT_SAVED',len(m['files']),flush=True)
