from pathlib import Path
import json,shutil,hashlib,html,re
from PIL import Image,ImageStat
def valid_frame(p):
 im=Image.open(p).convert("RGB");w,h=im.size;return max(ImageStat.Stat(im.crop((w*.15,h*.15,w*.85,h*.85))).stddev)>6
r=Path(__file__).resolve().parent;out=r.parent/'fluxara-user-lap-catch-final/report'
for sub in ['screenshots','references','evidence']:(out/sub).mkdir(parents=True,exist_ok=True)
a=json.loads((r/'preservation-audit.json').read_text());d=json.loads((r/'delivery-verification.json').read_text());shutil.copy2(r/'references/figma-seventh.png',out/'references/reference.png');shots=[]
for name,title,note in [('current-game-20s.png','Заезд в новой палитре','Кадр игрового режима Ghost Geometry. Маршрут и позиции предметов исходные.'),('current-game-35s.png','Заезд и окружение','Игровой кадр текущей версии.'),('final-lap-50s.png','Завершение отдельного круга','Естественный результат отдельного круга. Кадр предшествует только последней перекраске городских фасадов и исправлению декоративных водопадов; это не прохождение всех 11 кругов кампании.'),('waterfall-check.png','Водопад на склоне','Поток исправлен и повторно осмотрен в движке: прилегает к округлому склону.'),('preview-castle.png','Замковое окружение','Осмотр в игровом движке камерой; это не кадр управляемого заезда.'),('preview-castle-wide.png','Общий стиль','Осмотр в игровом движке камерой; изображение не дорисовывалось.')]:
 p=r/'screenshots'/name
 if p.exists() and valid_frame(p):shutil.copy2(p,out/'screenshots'/name);shots.append((name,title,note))
sections=[]
for p in sorted((r/'screenshots').glob('section-*.png')):
 if valid_frame(p):shutil.copy2(p,out/'screenshots'/p.name);sections.append(p.name)
for name in ['preservation-audit.json','delivery-verification.json','final-blend-verification.json','layout-verification.json','pool-audit.json','section-captures.json','current-game-capture.json','final-full-capture.json','preview-update.json','waterfall-conformance.json','campaign-preview-verification.json']:
 if (r/name).exists():shutil.copy2(r/name,out/'evidence'/name)
style=(r.parent/'spell-lab-rework/report-style.css').read_text();MB=lambda n:f'{n/1e6:.2f}'.replace('.',',')
def fig(src,title,note=''):return f'<figure><a href="{src}"><img src="{src}" alt="{html.escape(title)}" loading="lazy"></a><figcaption><strong>{title}</strong><span>{note}</span></figcaption></figure>'
s=f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lap Catch — единый стиль</title><style>{style}</style></head><body><main><div class="label">FLUXARA DRIFT · КАРТА 07 · 01.10.2026</div><h1>Lap Catch</h1><p class="lead">Все исходные регионы приведены к одному замковому стилю: светлый камень, зелёные склоны, округлые деревья, башни с коралловыми поясами, арки, вода и флажки. Деление на отдельные визуальные биомы убрано по указанию пользователя.</p><div class="tags"><span>Вес −{(1-a['trackAndNewSharedBytes']/a['originalBytes'])*100:.2f}%</span><span>Треугольники +{a['triangleChangePercent']:.2f}%</span><span>{a['newSharedPlacementCount']} новых координатных размещений</span><span>Маршрут сохранён</span></div><p><a href="../Lap%20Catch.blend">Изменённый Blender-проект</a> · <a href="evidence/preservation-audit.json">Сохранность и бюджет</a> · <a href="evidence/delivery-verification.json">Ресурсы и сборка</a></p><h2>Референс</h2>{fig('references/reference.png','Figma 378:87','Замковые башни, зелёные скалы, светлые арки и коралловые акценты. Исходную геометрию дороги под картинку не перестраивали.')}<p><a href="https://www.figma.com/design/Pws4Hw0fwwTmTMf6OJvil8/Fluxara-drift?node-id=378-87">Референс в Figma</a></p><p class="note">Точное сходство с иллюстрацией и окончательное визуальное согласование не заявляются. Крупные исходные формы и рельеф сохранились; игровой свет в симуляторе проще референса.</p><h2>Игровые кадры</h2>'''
for name,title,note in shots:s+=fig('screenshots/'+name,title,note)
s+=f'''<h2>Вес и переиспользование</h2><table><tr><th>Измерение</th><th>Результат</th></tr><tr><td>Исходная папка карты</td><td>{MB(a['originalBytes'])} МБ</td></tr><tr><td>Текущая папка карты</td><td>{MB(a['trackFolderBytes'])} МБ</td></tr><tr><td>Все новые общие ресурсы этой карты</td><td>{a['newSharedBytes']:,} байт</td></tr><tr><td>Карта вместе с новыми общими ресурсами</td><td>{MB(a['trackAndNewSharedBytes'])} МБ</td></tr><tr><td>Треугольники с каждым экземпляром</td><td>{a['originalTrianglesIncludingSharedInstances']:,} → {a['newTrianglesIncludingSharedInstances']:,}; в пределах ±20%</td></tr><tr><td>Распакованное приложение</td><td>{MB(d['live']['appBytes'])} МБ, Debug iOS Simulator. Это не размер IPA или скачивания из App Store.</td></tr></table><p>Окружение добавлено ссылками на реальные общие модели и координатами. Новые башни, арки и каскады экспортированы в игровые библиотеки. Округлые деревья, кусты, холмы, цветы и флажки переиспользованы из общего пула. Оригинальная музыка сохранена. Исходные изображения, рецепты, реальные материалы и меши сохранены в физическом пакете; каталог не подменяет сами файлы.</p><h2>Проверки и ограничения</h2><p>Сверены исходные вершины, нормали и все треугольники. Разбиение на буферы изменено только для материалов; полотно не заменено, поверх него новый дорожный меш не наложен. graph.xml, quads.xml, track.xml, физические модели препятствий, игровые точки, линии, предметы и первоначальные преобразования размещений сохранены. Физические свойства исходных материалов перенесены на новые имена.</p><p>Проекция вершин всех новых размещений проверена по исходным 1499 дорожным четырёхугольникам. Отсутствующих текстур в повторно открытом Blender-файле нет; координаты связанных экземпляров совпадают с экспортом. Файлы проекта, сборки и установленного приложения сверены по SHA-256.</p><p class="note">Проверочный заезд с одним кругом завершился естественно. Полный заезд на 11 кругов автопилот не завершил за 400 секунд. Исходный вариант тоже не завершал полный прогон, но места остановки отличаются; отсутствие игровой регрессии по этому тесту не доказано. Полное завершение кампании остаётся непроверенным, карту нельзя считать полностью принятой. Осмотр камерой проверяет отображение участков, а не их прохождение игроком. Производительность не измерялась.</p>'''
if sections:
 s+='<details><summary>Осмотр остальных участков игровым движком</summary>'
 for name in sections:s+=fig('screenshots/'+name,name,'Камера осмотра; исходные геометрия и игровые данные в рабочей карте не изменялись.')
 s+='</details>'
s+='</main></body></html>';(out/'index.html').write_text(s);missing=[x for x in re.findall(r'(?:src|href)="([^"]+)"',s) if not x.startswith('http') and not (out/x.replace('%20',' ')).exists()];assert not missing,missing
(out/'manifest.json').write_text(json.dumps({'brokenLocalLinks':missing,'screenshots':len(shots)+len(sections),'files':[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in out.rglob('*') if p.is_file() and p.name!='manifest.json']},indent=2));print('REPORT_READY',out)
