from pathlib import Path
import bpy,json,math,xml.etree.ElementTree as E
from mathutils import Matrix,Euler
r=Path(__file__).resolve().parent;w=r/'fidelity-v12';a=json.loads((r/'fidelity-v11/asset-registration.json').read_text());bpy.ops.wm.open_mainfile(filepath=a['finalBlend']);bpy.context.preferences.filepaths.save_version=0;native=w/'native';native.mkdir(exist_ok=True)
placements=json.loads((w/'greenery-placements.json').read_text())['placements'];proto=bpy.data.objects['VRV4E_Prototype_fluxara_driftlib_round_bush_green_v2_main_0'];col=bpy.data.collections['Volcano Remake Shared Instances'];scene=E.parse(w/'candidate/scene.xml').getroot();added=[]
for row in placements:
 xml=next(e for e in scene.findall('library')if e.get('id')==row['id']);xyz=list(map(float,xml.get('xyz').split()));scale=list(map(float,xml.get('scale').split()));hpr=list(map(float,xml.get('hpr').split()));rot=Euler(tuple(math.radians(-v)for v in [hpr[0],hpr[2],hpr[1]]),'XZY');matrix=Matrix.Translation((xyz[0],xyz[2],xyz[1]))@rot.to_matrix().to_4x4()@Matrix.Diagonal((scale[0],scale[2],scale[1],1));o=bpy.data.objects.new(row['id']+'_'+proto.name,proto.data);col.objects.link(o);o.matrix_world=matrix;o['shared_runtime_library']=row['library'];o['source_prototype']=proto.name;o['source_xml']=E.tostring(xml,encoding='unicode');o['asset_id']=row['pooledPrototypeId'];a['nativeSharedInstances'].append({'name':o.name,'prototype':proto.name,'library':row['library'],'matrix':[list(v)for v in matrix],'sourcePlacementId':row['id']});added.append(o.name)
for o in bpy.data.objects:
 if o.get('source_model')and 'fidelity-v11/candidate' in o['source_model']:o['source_model']=o['source_model'].replace('fidelity-v11/candidate','fidelity-v12/candidate')
bpy.data.texts['scene.xml'].clear();bpy.data.texts['scene.xml'].write((w/'candidate/scene.xml').read_text());a.update({'finalBlend':str(native/'Volcano Remake.blend'),'newPrototypes':[],'newCoordinateGreeneryObjects':added,'status':'V12 coordinate greenery using existing shared bush prototype. All model and texture bytes unchanged; isolated candidate.'});bpy.ops.wm.save_as_mainfile(filepath=a['finalBlend']);(w/'asset-registration.json').write_text(json.dumps(a,indent=2));print('V12_NATIVE_SHARED_GREENERY_SAVED',len(added),flush=True)
