from pathlib import Path
import json,hashlib,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v12';pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK');sources=pack/'sources/volcano-remake-fidelity-v12';sources.mkdir(exist_ok=True);a=json.loads((w/'asset-registration.json').read_text());ledger=json.loads((r/'fidelity-v11/candidate-asset-ledger.json').read_text());proof=json.loads((w/'final-blend-verification.json').read_text());assert proof['newGreeneryLinkedToExistingSingleMesh']==64;assert proof['newPrototypeMeshes']==0;assert json.loads((w/'navigation-clearance.json').read_text())['all64PlacementBoundingSpheresClearOriginalQuads'];assert json.loads((w/'existing-game-leaf-texture-verification.json').read_text())['existingTexturePixelsExact']
def info(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
for name in ['build_fidelity_v12_greenery.py','finalize_fidelity_v12.py','verify_fidelity_v12_native.py','capture_fidelity_v12_drive.py','capture_fidelity_v12_inspection.py',Path(__file__).name]:shutil.copy2(r/name,sources/name)
for p in w.glob('*.json'):shutil.copy2(p,sources/p.name)
for folder in ['candidate','native','screenshots','iterations']:shutil.copytree(w/folder,sources/folder,dirs_exist_ok=True)
pf=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_POOL.json');pool=json.loads(pf.read_text());ids=[q['id']for key in ['objects','materials','textures']for q in pool[key]];assert len(ids)==len(set(ids));newuse={'trackId':'fluxara-user-volcano-remake','candidate':'V12','coordinatePlacementsAdded':64,'status':'Existing bush reused directly on green crests; prototype and texture unchanged. Candidate not integrated.','placementProof':str(sources/'greenery-placements.json')};asset=next(q for q in pool['objects']if q['id']=='volcano-fidelity-v4e-beeb9c6d7ade8d6c');asset['uses']=[u for u in asset.get('uses',[])if u.get('candidate')!='V12']+[newuse]
for q in ledger['assets']:
 assert q['id']in ids;assert all(dep in ids for dep in q.get('dependencies',[]));assert Path(q['canonicalPackPath'].split('#')[0]).is_file()
 if q.get('file'):assert info(Path(q['file']['path']))==q['file'],q['id']
for q in ledger['objects']:
 if q['id']==asset['id']:q['uses']=asset['uses']
ledger.update({'candidate':'V12 64 coordinate bushes on green crests, all existing textures retained','finalBlend':a['finalBlend'],'status':'Current isolated candidate. 64 shared bush placements; source models, textures, existing scene objects and protected gameplay geometry retained. Reference fidelity unfinished.','budget':json.loads((w/'budget.json').read_text()),'preservation':json.loads((w/'preservation.json').read_text()),'runtimeValidation':json.loads((w/'runtime-validation.json').read_text()),'mapRuntimeFiles':[info(p)for p in(sources/'candidate').iterdir()if p.is_file()],'deltaAssetCounts':{'objects':0,'materials':0,'textures':0},'coordinateGreeneryAdded':64,'nativeSharedParts':len(a['nativeSharedInstances']),'productionIntegrated':False});ledger['assets']=ledger['objects']+ledger['materials']+ledger['textures'];(w/'candidate-asset-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2))
audit={'allExistingAssetPathsAndHashesVerified':True,'uniquePoolIds':len(ids),'newPoolAssets':0,'existingSharedBushPrototype':'volcano-fidelity-v4e-beeb9c6d7ade8d6c','additionalCoordinateBushes':64,'totalNativeSharedInstanceParts':len(a['nativeSharedInstances']),'newTextures':0,'newSharedGameFiles':0,'alreadyInstalledBushAndLeafFilesExactProject':True,'reusedAssets':len(ledger['assets']),'productionIntegrated':False};(w/'pool-audit.json').write_text(json.dumps(audit,indent=2));pf.write_text(json.dumps(pool,ensure_ascii=False,indent=2)+'\n')
for name in ['candidate-asset-ledger.json','pool-audit.json']:shutil.copy2(w/name,sources/name)
print('V12_SHARED_REUSE_ARCHIVED',audit,flush=True)
