from pathlib import Path
import json,shutil,re
r=Path(__file__).resolve().parent;w=r/'fidelity-v12';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v12';e.mkdir(exist_ok=True);page=out/'index.html';b=json.loads((w/'budget.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text());pres=json.loads((w/'preservation.json').read_text());nav=json.loads((w/'navigation-clearance.json').read_text());assert run['candidateOneLapTimeTrial']['naturalFinishObserved'];assert native['newGreeneryLinkedToExistingSingleMesh']==64
for p in w.glob('*.json'):shutil.copy2(p,e/p.name)
figures=[]
for second in [40,80]:
 name=f'fidelity-v12-game-{second}s.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name);figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V12"></a><figcaption>Заезд V12 в iOS Simulator, {second} секунд после запуска. Каменная текстура сохранена; новые кусты используют общую модель.</figcaption></figure>')
name='fidelity-v12-greenery-overview.png';shutil.copy2(w/'screenshots/smoke-diagnostic-all.png',out/'screenshots'/name)
section=f'''<section id="fidelity-v12-draft"><h2>Последняя доработка — V12: окружение из пула</h2><p>На зелёных площадках и пологих склонах добавлены 64 куста из уже используемой общей библиотеки fluxara_driftlib_round_bush_green_v2. В карте хранятся координаты, углы и масштабы, а все 64 размещения ссылаются на одну модель. Новые меши, материалы и текстуры не создавались. Каменная текстура, красные крыши и меньшие дымовые шлейфы сохранены.</p><table><tr><th>Показатель</th><th>Результат</th></tr><tr><td>Карта и новые общие игровые ресурсы</td><td>{b['newBytesIncludingNewSharedRuntime']:,} байт; меньше V1 на {b['savedBytesAgainstPrevious']:,} байт</td></tr><tr><td>Добавленные файлы общих моделей/текстур</td><td>0. Рост размещений записан только в scene.xml.</td></tr><tr><td>Вес моделей вместе с текстурами</td><td>0% изменения; все исходные SPM и изображения совпадают с V11.</td></tr><tr><td>Треугольники со всеми размещениями</td><td>{b['candidateTriangles']:,}; справочно, без ограничения ±20% на сетку.</td></tr><tr><td>Части общих объектов в Blender</td><td>{native['sharedInstancesMatch']}; 64 новых части используют один прежний меш.</td></tr></table><p>Площадки выбраны по геометрии зелёного покрытия. Проверены опора куста на поверхность, расстояния между кустами и зазор полной ограничивающей сферы относительно треугольников дороги и деревянных поверхностей: минимум {pres['minimumRoadMarginMetres']:.2f} м. Дополнительная проверка всех 180 навигационных участков дала минимальный зазор {nav['minimumMarginMetres']:.2f} м. Существующие объекты и их размещения совпадают с V11; дорога, игровые точки и файлы управления сохранены. После открытия Blender подтверждены общие данные меша и неизменность прежних объектов.</p><p>Модель и текстура куста в установленном симуляторе побайтно совпадают с ресурсами проекта. Полный круг Time Trial с 64 кустами завершился естественно, результат #1. Полная кампания, обратный режим и FPS этим тестом не проверены.</p><p class="note">Визуальная доработка ещё продолжается: крупные формы вулкана, лава, замковые стены и дым пока далеки от референса. Основная карта, финальный .blend и игровое превью остаются V1; новый билд не создавался.</p><p><a href="../../volcano-remake-rework/fidelity-v12/native/Volcano%20Remake.blend">Blender V12</a> · <a href="evidence/fidelity-v12/greenery-placements.json">Координаты кустов</a> · <a href="evidence/fidelity-v12/budget.json">Вес</a> · <a href="evidence/fidelity-v12/navigation-clearance.json">Зазор от навигационной трассы</a> · <a href="evidence/fidelity-v12/runtime-validation.json">Заезд</a> · <a href="evidence/fidelity-v12/pool-audit.json">Переиспользование</a> · <a href="screenshots/{name}">Статический общий вид в движке</a></p>{''.join(figures)}</section>'''
s=re.sub(r'<section id="fidelity-v12-draft">.*?</section>','',page.read_text(),flags=re.S).replace('<section id="fidelity-v11-draft">',section+'<section id="fidelity-v11-draft">',1).replace('Последняя доработка — V11','Предыдущая доработка — V11');page.write_text(s);pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report']+list((pack/'sources').glob('volcano-remake-fidelity-*/report'))+[pack/'sources/volcano-remake-fidelity-v12/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v12'/Path(__file__).name);progress=r.parent/'shared-placement-1-10/progress.json';d=json.loads(progress.read_text());d['maps']['10'].update({'status':'V12 64 extra coordinate bushes using one existing model and texture. Existing geometry retained, native and asset reuse verified, natural one-lap TT #1. Overall reference fidelity unfinished; production and preview unchanged.','candidate':str(w),'candidateTrackBytes':b['candidateTrackBytes'],'candidateBytesIncludingNewSharedRuntime':b['newBytesIncludingNewSharedRuntime'],'candidateSavedBytesAgainstPrevious':b['savedBytesAgainstPrevious'],'candidateTriangleChangePercent':b['triangleChangePercentAgainstOriginal'],'candidateOneLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateAdditionalGreeneryInstances':64,'fullyAccepted':False});d['goalComplete']=False;progress.write_text(json.dumps(d,ensure_ascii=False,indent=2));print('V12_REPORT_UPDATED',flush=True)
