from pathlib import Path
import hashlib,json,re,shutil
r=Path(__file__).resolve().parent;w=r/'fidelity-v23';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v23';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());p=json.loads((w/'backdrop-changes.json').read_text())
assert run['naturalFinishObserved']and run['visualInspectionCompleted']and audit['newNativePrototypes']==1 and audit['newTextures']==0
for f in w.glob('*.json'):
    if not f.name.startswith('pool-before'):shutil.copy2(f,e/f.name)
figures=[]
for second,caption in [(40,'Каменная фактура и исходная дорога сохранены.'),(80,'На дальнем плане справа видна округлая зелёная площадка; узкие полосы вдоль дороги не менялись.')]:
    name=f'fidelity-v23-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name)
    figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V23"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
for name,src in [('fidelity-v23-overview.png',w/'screenshots/smoke-diagnostic-all.png'),('fidelity-v23-backdrop-overview.png',w/'screenshots/smoke-diagnostic-backdrops.png'),('fidelity-v22-backdrop-comparison.png',r/'backdrop-v22-comparison/screenshots/smoke-diagnostic-backdrops.png'),('fidelity-v23-natural-finish.png',w/'screenshots/natural-finish.png')]:shutil.copy2(src,out/'screenshots'/name)
section=f'''<section id="fidelity-v23-draft"><h2>Последняя доработка — V23: объём крупных площадок на заднем плане</h2>
<p>Две большие зелёные площадки, ранее состоявшие из шести и четырёх крупных граней, получили плавный внутренний подъём. Края сохранили прежние позиции; новые вершины подняты максимум на 35,62 и 32,17 м. Все остальные 1&nbsp;790 грани общей модели V20, их вершины, UV, нормали и цвета сохранены. В общей модели теперь 2&nbsp;710 треугольников. Она заменяет одно координатное размещение прежней общей модели; геометрия не копируется на каждый экземпляр.</p>
<p>Ранее намеченные компоненты 12/13/15 оказались узкими полосами вдоль дороги, поэтому их оставил без изменений и исправил план. Само полотно, проезды, исходная геометрия столкновений и все программные точки/линии сохранились. Все файлы карты V22 точно совпали, кроме имени одной библиотеки в scene.xml. Исходная общая библиотека V20 сохранена. Габарит активной геометрии всей общей модели, начало координат, оси и матрица размещения прежние; высоты отдельных двух площадок изменены внутри общего габарита.</p>
<p>Каменная текстура размером 39&nbsp;938 байт и её UV сохранены по замечанию пользователя. Прежняя зелёная палитра переиспользована; новых изображений, пикселей или материалов нет. Независимая проверка всех новых граней дала минимальное расстояние до 2&nbsp;032 защищённых треугольников проезда {b['independentAllNewFaceRoadTriangleMarginMeters']:.3f} м. Погрешность положения новых вершин краёв относительно исходных граничных сегментов — менее 0,0001 м.</p>
<table><tr><th>Измерение</th><th>Результат</th></tr>
<tr><td>Исходный декоративный регион с исходной реально использованной текстурой</td><td>{b['originalComponentWithTextureBytes']:,} байт</td></tr>
<tr><td>Новый общий рельеф + точная исходная физическая модель + используемая палитра</td><td>{b['adaptedVisibleAndOriginalCollisionWithTextureBytes']:,} байт; {b['modelWithTextureChangePercent']:.2f}%</td></tr>
<tr><td>Карта + все добавленные общие игровые ресурсы, включая сохранённые ранние варианты</td><td>{b['candidateIncludingNewSharedBytes']:,} байт</td></tr>
<tr><td>Интегрированный V1</td><td>{b['v1Bytes']:,} байт</td></tr>
<tr><td>Уменьшение относительно V1</td><td>{b['savingBytesVsV1']:,} байт; {b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%</td></tr>
<tr><td>Добавлено относительно V22</td><td>{b['changeBytesAgainstIntermediateV22']:,} байт</td></tr></table>
<p>Предел +20% проверен именно по модели с текстурой. Число полигонов не ограничивалось этим процентом. Базовый декоративный регион сопоставлен с моделью до переделки и её Rock13_col.jpg; это сравнение не с маленькой промежуточной палитрой. Размер приложения заново не измерялся.</p>
<p>В Blender проверены 8&nbsp;130 углов новой модели, 333 общие части и 180 навигационных квадов. Остальные 610 мешей совпали с V22 по геометрии, UV, нормалям, цветам, матрицам и материалам. Активны 34 прототипа и 88 материалов; старый прототип сохранён скрытым. Новый прототип добавлен в каноническую библиотеку с прежним материалом. Все {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов ведомости имеют реальные файлы, совпадающие размеры/хеши и разрешённые зависимости.</p>
<p>В симуляторе выполнен один полный круг Time Trial, один карт, seed 4, естественный результат <a href="screenshots/fidelity-v23-natural-finish.png">#1</a>. На сохранённых кадрах 40/80/140 карт находится на дороге; кадр результата снят на 190-й секунде после запуска. Это не доказывает отсутствие выездов между кадрами. Ранее в неизменённом V1 уже наблюдалось опасное прохождение рампы; его причина не исправлялась и все регрессии не исключены. Кадры сняты без ретуши. Временные карты и скопированные ресурсы удалены из установленного приложения, донорская библиотека не изменена; предупреждения материалов совпали с V22.</p>
<p>Два дорожных кадра ниже показывают текущий материал и окружение. Для формы дальних площадок отдельно сохранены диагностические виды из одинаковой камеры: <a href="screenshots/fidelity-v22-backdrop-comparison.png">V22</a> и <a href="screenshots/fidelity-v23-backdrop-overview.png">V23</a>. Они сняты в движке, но не являются игровыми кадрами. <a href="screenshots/fidelity-v23-overview.png">Общий вид</a> показывает сохраняющиеся недостатки композиции.</p>
<p class="note">Сходство с референсом ещё не достигнуто: большие каменные стены, повторяющиеся уступы, пропорции замка и освещение атмосферы требуют работы. Основная карта, итоговый пользовательский .blend и превью пока V1. Новая сборка приложения, производительность, обратный режим и вся кампания здесь не проверялись.</p>
<p><a href="../../volcano-remake-rework/fidelity-v23/native/Volcano%20Remake.blend">Blender V23</a> · <a href="evidence/fidelity-v23/backdrop-changes.json">Новый рельеф</a> · <a href="evidence/fidelity-v23/preservation-verification.json">Вес и сохранность</a> · <a href="evidence/fidelity-v23/final-blend-verification.json">Проверка Blender</a> · <a href="evidence/fidelity-v23/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v23/pool-audit.json">Общий пул</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v23-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('Последняя доработка — V22','Предыдущая доработка — V22');s=s.replace('<section id="fidelity-v22-draft">',section+'<section id="fidelity-v22-draft">',1);page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(f.relative_to(out)),'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in sorted(out.rglob('*'))if f.is_file()and f!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v23/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v23'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V23 rounds two broad distant caps, 610 other native meshes and all V22 candidate models/physics/controls/textures retained. Canonical/ledger and natural one-lap #1 verified. Narrow roadside strips intentionally unchanged. Large stone walls and lighting unfinished; production/final/preview V1.','candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V23','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateActiveNativePrototypes':34,'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V23';data.pop('inProgressCandidate',None);data['status']='V23 rounds large distant caps8/9; whole shared-model bounds and existing stone/green pixels retained. Weight6611088B. Native/canonical, timed gameplay and same-camera backdrop comparison complete. Overall reference match remains unfinished.'
for q in data['priorities']:
    if q['role']=='Rounded central cliff support and green terrain':q.update({'completedCandidate':'V23 partial','remaining':'Narrow roadside strips12/13/15 are intentionally preserved. Backdrop caps8/9 rounded in V23. Largest remaining discrepancies: massive stone-wall silhouettes, repeated cliff top composition, foreground vegetation, castle proportions and lighting. Prioritize these visible major forms; do not raise road strips.'})
plan.write_text(json.dumps(data,indent=2));print('V23_REPORT_UPDATED',len(m['files']),flush=True)
