from pathlib import Path
import json,shutil,re,hashlib
r=Path(__file__).resolve().parent;w=r/'fidelity-v21';out=r.parent/'fluxara-user-volcano-remake-final/report';e=out/'evidence/fidelity-v21';e.mkdir(exist_ok=True)
b=json.loads((w/'preservation-verification.json').read_text());run=json.loads((w/'runtime-validation.json').read_text());audit=json.loads((w/'pool-audit.json').read_text());native=json.loads((w/'final-blend-verification.json').read_text())
assert run['naturalFinishObserved'] and run['visualInspectionCompleted'] and audit['newNativePrototypes']==1 and audit['newTextures']==0
for p in w.glob('*.json'):
    if not p.name.startswith('pool-before'):shutil.copy2(p,e/p.name)
figures=[]
for second,caption in [(40,'Каменная фактура и прежний решётчатый проезд сохранены.'),(80,'Поворот замкового участка: прежняя дорога и ограждение. Центральная вершина лучше видна на общем диагностическом виде.')]:
    name=f'fidelity-v21-game-{second}.png';shutil.copy2(w/f'screenshots/drive-{second}s.png',out/'screenshots'/name)
    figures.append(f'<figure><a href="screenshots/{name}"><img src="screenshots/{name}" alt="Игровой кадр V21"></a><figcaption>iOS Simulator. {caption}</figcaption></figure>')
static='fidelity-v21-central-crest-overview.png';finish='fidelity-v21-natural-finish.png'
shutil.copy2(w/'screenshots/smoke-diagnostic-all.png',out/'screenshots'/static);shutil.copy2(w/'screenshots/natural-finish.png',out/'screenshots'/finish)
section=f'''<section id="fidelity-v21-draft"><h2>Последняя доработка — V21: округлая вершина центрального уступа</h2>
<p>Передняя центральная зелёная площадка из восьми крупных граней заменена округлой вершиной с плавным краем. Контур получен сглаживанием исходного восьмиугольного края внутрь его прежнего пятна; верх плавно поднимается до прежней максимальной высоты. Добавлен небольшой каменный стык с исходным уступом. Новая общая модель содержит 480 зелёных и 64 переходных каменных треугольника и ставится одной записью координат.</p>
<p>Сохранены все 64 исходные каменные грани центрального объекта: геометрия, UV, нормали, цвета и текущая текстура размером 39&nbsp;938 байт. Общие размеры полного центрального уступа из первоначальных 72 граней, начало координат и оси не изменились. Зелёная вершина сама получила новую форму; утверждение о сохранении габарита относится к полному исходному объекту вместе с его каменным основанием. Исходные восемь граней столкновений сохранены в отдельной точной физической модели. Дорога, другие проезды, игровые точки/линии и сценарии не изменены. Проверенное минимальное расстояние от всех новых граней до 2&nbsp;032 защищённых треугольников проезда — {b['independentCrestRoadTriangleMarginMeters']:.3f} м.</p>
<p>Зелёная палитра и каменная текстура переиспользованы из общего пула. Новых игровых файлов текстур, пикселей, материалов и изображений Blender нет. Все прочие файлы V20, 58 уступов, 32 холма и клубы дыма сохранены. Первую широкую эллиптическую форму отверг после просмотра в движке: она выглядела нависающим диском. Проба и остановленный после 40 секунд запуск находятся только в архиве итераций. Итоговый V21 использует более узкий контур по исходному краю.</p>
<table><tr><th>Измерение</th><th>Результат</th></tr>
<tr><td>Полный исходный центральный объект из 72 граней с исходной текстурой до переделки</td><td>{b['originalCentralObjectModelWithTextureBytes']:,} байт</td></tr>
<tr><td>Новая вершина + сохранённая каменная часть + исходные столкновения + обе фактически используемые текстуры</td><td>{b['adaptedCentralObjectIncludingRetainedStoneAndCollisionWithTexturesBytes']:,} байт; {b['modelWithTextureChangePercent']:.2f}%</td></tr>
<tr><td>Карта со всеми добавленными общими игровыми ресурсами и сохранёнными ранними собственными вариантами</td><td>{b['candidateIncludingNewSharedBytes']:,} байт</td></tr>
<tr><td>Исходный интегрированный V1</td><td>{b['v1Bytes']:,} байт</td></tr>
<tr><td>Уменьшение относительно V1</td><td>{b['savingBytesVsV1']:,} байт; {b['savingBytesVsV1']/b['v1Bytes']*100:.2f}%</td></tr>
<tr><td>Разница с промежуточным V20</td><td>+{b['changeBytesAgainstIntermediateV20']:,} байт</td></tr></table>
<p>Предел +20% проверен по весу полного исходного объекта с исходной реально использованной текстурой Lava_004_COLOR.jpg из модели до переделки. Все 72 исходные грани сопоставлены по позициям. Сохранённая каменная часть включена в новый вес через отдельный SPM для учёта размера, вместе с его заголовком; этот файл не добавляется в приложение. Число полигонов не ограничивалось ±20%. Вес приложения здесь не измерялся.</p>
<p>При повторном открытии Blender 605 прочих мешей точно совпали с V20 по геометрии, UV, нормалям, цветам, матрицам и материалам. В изменённом смешанном меше сохранены 596 прежних граней, их позиции, UV, цвета, матрица, материалы и нормали. Проверены {native['newIndexedCornersCheckedIncludingOriginalCollider']:,} углов новой вершины и исходного физического меша, 333 общие части и 180 навигационных квадов. Один новый прототип с прежними материалами добавлен в каноническую библиотеку. Все {audit['totalLedgerAssetsIncludingHistoricalSources']} ресурсов ведомости имеют реальные файлы с проверенными хешами и зависимостями.</p>
<p>Выполнен полный круг Time Trial в симуляторе: один карт, один круг, seed 4, естественный результат <a href="screenshots/{finish}">#1</a>. На 80-й секунде карт прижимается к стене, на 140-й виден выезд к лаве; до итогового кадра на 190-й секунде он достиг финиша. Этот прогон подтверждает достижение результата, но не безошибочное прохождение AI или отсутствие прежних проблем маршрута. Ниже два реальных игровых кадра без ретуши. Новая вершина видна на <a href="screenshots/{static}">общем диагностическом виде в движке</a>; эти два дорожных кадра сами по себе не доказывают сходство её формы с референсом. Временная карта и её временные ресурсы удалены из установленного приложения. Предупреждения о материалах совпадают с V20.</p>
<p class="note">Работа над соответствием референсу ещё не завершена: остаются плоские площадки рядом с дорогой, повторяющиеся круглые шапки уступов, пропорции замка, освещение дыма и атмосфера. Основная карта, итоговый пользовательский .blend и превью пока V1. Нет заявления о новой сборке приложения, производительности, обратном режиме или полной проверке кампании.</p>
<p><a href="../../volcano-remake-rework/fidelity-v21/native/Volcano%20Remake.blend">Blender V21</a> · <a href="evidence/fidelity-v21/crest-changes.json">Новая вершина</a> · <a href="evidence/fidelity-v21/preservation-verification.json">Вес и сохранность</a> · <a href="evidence/fidelity-v21/final-blend-verification.json">Проверка Blender</a> · <a href="evidence/fidelity-v21/runtime-validation.json">Игровой круг</a> · <a href="evidence/fidelity-v21/pool-audit.json">Общий пул</a></p>{''.join(figures)}</section>'''
page=out/'index.html';s=re.sub(r'<section id="fidelity-v21-draft">.*?</section>','',page.read_text(),flags=re.S);s=s.replace('<section id="fidelity-v20-draft">',section+'<section id="fidelity-v20-draft">',1).replace('Последняя доработка — V20','Предыдущая доработка — V20');page.write_text(s)
manifest=out/'manifest.json';m=json.loads(manifest.read_text());m['files']=[{'path':str(p.relative_to(out)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}for p in sorted(out.rglob('*'))if p.is_file()and p!=manifest];manifest.write_text(json.dumps(m,ensure_ascii=False,indent=2))
pack=Path('/Users/motoricallc/Downloads/fluxara-drift/FLUXARA_TRACK_ASSET_PACK')
for dest in [pack/'sources/volcano-remake-reference-v1/report',pack/'sources/volcano-remake-fidelity-v21/report']:shutil.copytree(out,dest,dirs_exist_ok=True)
shutil.copy2(Path(__file__),pack/'sources/volcano-remake-fidelity-v21'/Path(__file__).name)
progress=r.parent/'shared-placement-1-10/progress.json';data=json.loads(progress.read_text());data['maps']['10'].update({'status':'V21 rounds central crest along original rim; original 64 stone faces/UVs and 8 collision faces retained, central object bounds exact. Native/canonical verified, natural one-lap TT #1. Near-road green terrain, repeated caps and lighting unfinished; production/final/preview V1.',
'candidate':str(w),'candidateTrackBytes':b['candidateMapBytes'],'candidateBytesIncludingNewSharedRuntime':b['candidateIncludingNewSharedBytes'],'candidateSavedBytesAgainstPrevious':b['savingBytesVsV1'],'candidateOneLapNaturalFinish':True,'lastFullLapVerifiedCandidate':'V21','lastFullLapNaturalFinish':True,'candidateProductionIntegrated':False,'candidateActiveNativePrototypes':34,'fullyAccepted':False});data['goalComplete']=False;progress.write_text(json.dumps(data,ensure_ascii=False,indent=2))
plan=r/'next-fidelity-batch.json';data=json.loads(plan.read_text());data['baseCandidate']='V21';data['status']='V21 rounds actual central eight-face crest inward along original rim. Current stone pixels/UVs, original collision and object bounds retained. Weight 6545565B. Near-road green forms, repeated caps and atmosphere unfinished.'
for q in data['priorities']:
    if q['role']=='Rounded central cliff support and green terrain':q.update({'completedCandidate':'V21 partial','done':'Central eight-face crest replaced by a smooth inscribed rounded top with stone transition, one ghost library. All original 64 stone faces and eight collision faces retained, object composite box/axes/origin unchanged. Sixteen other green terrain components rounded in V20.','remaining':'Near-road terrain components 12/13/15 remain planar. 58 repeating disc-capped cliffs and background wall silhouettes still differ from reference. Improve actual foreground forms, plant composition and lighting.'})
plan.write_text(json.dumps(data,indent=2));print('V21_REPORT_TWO_GAME_FRAMES_AND_FULL_LAP_UPDATED',len(m['files']),flush=True)
